sway-core/src/engine_threading.rs
sway-core/src/language/ty/declaration/enum.rs
sway-core/src/language/ty/declaration/struct.rs
sway-core/src/semantic_analysis/namespace/trait_map.rs
sway-core/src/type_system/info.rs
sway-core/src/type_system/trait_constraint.rs
sway-core/src/type_system/type_argument.rs
sway-core/src/type_system/type_parameter.rs
sway-types/src/integer_bits.rs

This PR is a subset of #3744. It adds a `OrdWithEngines` for the types required in #3744. Note---this isn't a necessary change into master right at this current moment, just simply a way of breaking up #3744 😄

Implement `OrdWithEngines` for some types

---

sway-ast/src/attribute.rs
sway-ast/src/keywords.rs
sway-core/src/language/parsed/module.rs
sway-core/src/language/ty/module.rs
sway-core/src/lib.rs
sway-core/src/semantic_analysis/module.rs
sway-error/src/error.rs
sway-error/src/parser_error.rs
sway-parse/src/attribute.rs
sway-parse/src/item/mod.rs
sway-parse/src/keywords.rs
sway-parse/src/lib.rs
sway-parse/src/module.rs
sway-parse/src/token.rs
swayfmt/src/error.rs
swayfmt/src/formatter/mod.rs
swayfmt/src/parse.rs
swayfmt/src/utils/language/attribute.rs
swayfmt/src/utils/map/comments.rs
swayfmt/src/utils/map/newline.rs
swayfmt/tests/mod.rs

This adds the `HashBangToken` (`#!`) which will support nested module doc comments as well as inner doc comments for annotated items.

Support inner doc attributes with `#!` & `//!` syntax

---

sway-lib-std/src/bytes.sw

Added the `mut` keyword to `append()` in the `Bytes` type in the standard library. This causes an internal compiler error for the [`String`](https://github.com/FuelLabs/sway-libs/tree/master/libs/string) type. https://github.com/FuelLabs/sway/issues/4109 should disallow both the syntax and resolve the internal compiler error.
Closes #4108

Add `mut` keyword to `append()` in the `Bytes` type

---

Cargo.lock
forc-plugins/forc-tx/Cargo.toml
forc-plugins/forc-tx/src/lib.rs
forc-plugins/forc-tx/src/main.rs

This introduces a `Command::parse` constructor that emulates the behaviour of the `clap` parse constructor in order to provide a more consistent clap-like CLI experience. For context, we cannot use the generated `parse` command due to limitations in clap's ability to handle trailing subcommands as mentioned in #3804.
We switch to using `thiserror` in the library in order to allow for handling error cases (necessary for the new `parse` constructor) and to provide cleaner, more detailed error cause traces.
The help and version output no longer panic, and now behave like regular clap applications. Closes #3886.
Also adds an example command invocation to the end of the `--help` output.

`forc-tx`: Improve error handling using `thiserror`. Fix `panic!`ing version/help output.

---

sway-parse/src/attribute.rs
sway-parse/src/item/mod.rs
sway-parse/src/token.rs
swayfmt/tests/mod.rs

Ran on test branch & working as intended. Only beginning of file `//!` is collected as `DocComment` with `DocStyle::Inner` which is only parsed at the beginning of the `Module` parsing stage. This ensures that any `//!` found after the module docs will be treated as normal comments for now. Ref #4112 for tracking further progress in allowing inner doc comments for `Item`.

Limit inner doc comment attributes to `Module`

---

swayfmt/src/items/item_configurable/mod.rs
swayfmt/src/items/item_configurable/tests.rs
swayfmt/src/items/mod.rs
swayfmt/src/module/item.rs
swayfmt/src/utils/language/punctuated.rs
test/src/e2e_vm_tests/test_programs/should_fail/configurables_are_immutable/Forc.toml
test/src/e2e_vm_tests/test_programs/should_fail/configurables_are_immutable/src/main.sw
test/src/e2e_vm_tests/test_programs/should_fail/configurables_are_immutable/test.toml
test/src/e2e_vm_tests/test_programs/should_fail/configurables_in_lib/Forc.toml
test/src/e2e_vm_tests/test_programs/should_fail/configurables_in_lib/src/main.sw
test/src/e2e_vm_tests/test_programs/should_fail/repeated_configurable/src/main.sw
test/src/e2e_vm_tests/test_programs/should_pass/language/configurable_consts/Forc.toml
test/src/e2e_vm_tests/test_programs/should_pass/language/configurable_consts/src/main.sw

Closes #3679
This is based on how `storage` blocks are handled.. Most of the code is copied from `item_storage`. We should probably consider making as much as that code common between the two because `storage` and `configurable` blocks look pretty much the same.
Making this change now so that the formatter does not panic when we add an example using `configurable` under `sway/examples`.

Support for configurable blocks in the formatter

---

sway-core/src/semantic_analysis/storage_only_types.rs
test/src/e2e_vm_tests/test_programs/should_fail/storage_types/src/main.sw
test/src/e2e_vm_tests/test_programs/should_fail/storage_types/test.toml

Fixes #4040 
There is an exception for `self` parameters, to avoid the error being thrown for impl of the actual storage types (in storage.sw). I'm not sure if that's the best way to add that exception. Reviewers please advice. [Edit: This is fixed, thanks @anton-trunov ]

Check for storage types in impl method params

---

sway-lsp/tests/lib.rs

just adding a missing go to test for structs.
works towards #3989

add missing go to def tests for structs

---

Cargo.lock
forc-plugins/forc-client/Cargo.toml
forc-plugins/forc-client/src/cmd/deploy.rs
forc-plugins/forc-client/src/cmd/run.rs
forc-plugins/forc-client/src/op/deploy.rs
forc-plugins/forc-client/src/op/run.rs
forc-plugins/forc-tx/src/lib.rs

This allows for specifying a `--salt` for the top-level contract member when running `forc deploy`. Right now, we only enable this for *packages*, and not for workspaces with more than one package due to some ambiguities that arise (see comment note in code). I'll open an issue to track relaxing this constraint a little. Edit: opened https://github.com/FuelLabs/sway/issues/4117.
I noticed we also had no way of specifying maturity, so have added a `--maturity` flag for this as well.
These flags are shared with the `forc-tx` crate in order to try and provide some consistency (in help output and flag representation) across our CLI tooling.
Ideally we'd like to ship this feature in the Sway release that ends up in the fuelup beta-3 toolchain - otherwise users following the quick-start guide …

feat: Add salt flag to `forc deploy`, maturity flag to `deploy` and `run`

---

docs/book/src/forc/workspaces.md

closes #4102.
Tiny doc PR adding missing essential commands that now supports workspaces

docs: updated docs with missing supported workspace commands

---

sway-core/src/language/parsed/expression/asm.rs
sway-core/src/language/ty/expression/asm.rs
sway-lsp/src/traverse/parsed_tree.rs
sway-lsp/src/traverse/typed_tree.rs

Collects `Expression` variants in `AsmRegisterDeclaration` and `TyAsmRegisterDeclaration` if there are any. 
Closes #3715

Collect `Expression` from asm register decls

---

sway-core/src/type_system/info.rs
sway-core/src/type_system/unify_check.rs
test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/return_struct/Forc.lock
test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/return_struct/Forc.toml
test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/return_struct/json_abi_oracle.json
test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/return_struct/src/data_structures.sw
test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/return_struct/src/interface.sw
test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/return_struct/src/main.sw
test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/return_struct/test.toml

The issue is that currently call paths of structs and enums are based on module path which can differ depending on the order of imports.
The solution was to revert to the old behavior of comparing only the type name contained in the suffix.
Closes #4125

Fixes struct and enum call path comparison to use suffix.

---

forc-plugins/forc-fmt/src/main.rs

Fixes the same issue found here: https://github.com/FuelLabs/sway/pull/4038#discussion_r1105153934, but missed out in other locations. This has caused new PRs to not fail on `forc-fmt --check` even if they contained formatting violations, see: https://github.com/FuelLabs/sway/pull/4129

fix(fmt): forc-fmt check

---

test/src/sdk-harness/test_projects/storage_vec/testgen.rs

imports for the abigen-generated types were missing in success and failure modules.

fix imports

---

sway-lsp/src/capabilities/hover.rs
sway-lsp/src/core/session.rs
sway-lsp/src/core/token.rs
sway-lsp/src/traverse/typed_tree.rs
sway-lsp/src/utils/attributes.rs
sway-lsp/tests/fixtures/tokens/abi/.gitignore
sway-lsp/tests/fixtures/tokens/abi/Forc.toml
sway-lsp/tests/fixtures/tokens/abi/src/main.sw
sway-lsp/tests/lib.rs

Adds goto and hover tests for ABI's. Also cleaned up the typed_tree module by storing a ref to namespace in the type instead of passing it around everywhere. 
Found a bug where we weren't collecting attributes for `AbiDeclaration`. Hover docs now works on these types.
works towards #3989 
closes #4065

Add LSP tests for `TyAbiDeclaration`

---

sway-core/src/semantic_analysis/ast_node/declaration/trait_fn.rs

Small PR to remove an unnecessary call to remove an extra export of methods defined for trait fn return types.

Remove unnecessary call to export methods defined for trait fn return types.

---

Cargo.lock
forc-pkg/Cargo.toml
forc-pkg/src/lock.rs
forc-pkg/src/pkg.rs
forc-pkg/src/source/git.rs
forc-pkg/src/source/mod.rs
forc-tracing/src/lib.rs
forc-util/src/lib.rs

We now print with the following format *prior* to compiling a package:
```
Compiling <ty> <name> (<src>)
```
Rather than only printing `Compiled` after compilation is complete.
Closes #3780.
This also aims to improve the formatting of the output a little by using ansi_term styling to distinguish between action, program kind, package name and source more clearly.
The fetching, adding and removing actions have had their formatting updated to match. E.g.

feat(forc-pkg): Print *before* compiling each package. Only print after on warnings/error.

---

sway-lsp/src/core/session.rs

The memory footprint was growing on each keystroke in the language server. This reinitializes the engines before each subsequent compilation in order to clear existing memory. 
closes #4144

Clear memory from type and decl engines

---

forc-test/src/lib.rs
forc/src/cli/commands/test.rs

closes #2411.
This PR adds used gas information to the output of `forc test`. An example run can be seen below:
This is done automatically without any flags. I felt like this should be the default way but open to suggestions if you feel like it should be behind a flag like `--gas-usage`.
Also by accessing `TestResult` struct's new "used gas" field, we can add this information into vscode plugin just like #513. We do not have a line by line gas cost information just yet but we could show the whole test's used gas info next to the run button or something in vscode. Thoughts @JoshuaBatty @sdankel 
Please let me know if anyone has any requests around the flag and the way we are printing the used gas. Maybe @nfurfaro could have some ideas as the prime user of `forc-test` 😄

feat: display gas used for unit tests

---

docs/book/src/introduction/standard_library.md
sway-lib-std/src/lib.sw
sway-lsp/tests/lib.rs

Adds a link to the `std` docs in the standard library section of the sway book & links the source code in the root docstring of the `std` library itself.

Add `std` docs to the sway book

---

docs/book/src/introduction/sway_quickstart.md

Remove the invalid link to Developer Quickstart Guide in the official Sway docs and replace it with the valid one.

Update the invalid link to Developer Quickstart Guide in the Sway Docs.

---

sway-core/src/engine_threading.rs
sway-core/src/language/ty/declaration/enum.rs
sway-core/src/language/ty/declaration/struct.rs
sway-core/src/semantic_analysis/namespace/trait_map.rs
sway-core/src/type_system/info.rs
sway-core/src/type_system/trait_constraint.rs
sway-core/src/type_system/type_argument.rs
sway-core/src/type_system/type_parameter.rs

Simple refactor to remove re-borrows of `Engines`, which is a `Copy` type.
~~- [ ] I have linked to any relevant issues.~~
~~- [ ] I have commented my code, particularly in hard-to-understand areas.~~
~~- [ ] I have updated the documentation where relevant (API docs, the reference, and the Sway book).~~
~~- [ ] I have added tests that prove my fix is effective or that my feature works.~~

Remove re-borrow of `Engines`, which is a `Copy` type.

---

forc-plugins/forc-fmt/src/main.rs

closes #4163
In a previous refactor PR that I submitted the error propagation was accidentally suppressed, causing the formatter to not exit with 1 on error.

fix(forc-fmt): propagate error on failure

---

.github/workflows/ci.yml

closes #3447
Failed the first commit deliberately just to [demonstrate the failure case](https://github.com/FuelLabs/sway/actions/runs/4341593516/jobs/7581384965) (there's a mistyped newline in that job, fixed in the following commit), added a little message just to explain why we may not want `fuels` deps in `forc-pkg` - let me know if it is adequately explained!

ci: check for `fuels` deps in `forc-pkg`

---

sway-core/src/decl_engine/engine.rs

Fix a bug in the new decl engine implementation where the specific functions for certain type ids were generic over every id, which could allow for misuse.

Fix decl engine accepting wrongly typed indices

---

forc-pkg/src/pkg.rs
forc-pkg/src/source/member.rs
forc-pkg/src/source/mod.rs

Fixes an issue where member source types unintentionally omitted entries from the manifest map during the fetch traversal after the source refactor in #4168.
Tested locally with the `fuels-rs` test suite using the steps described in #4235.
Closes #4235.
This patch will likely also apply to other large workspaces too, we might want to consider cutting a patch release soon after landing.

fix(forc-pkg): Unify member source types, fix manifest entries, fix #4235

---

sway-core/src/abi_generation/evm_json_abi.rs
sway-core/src/abi_generation/fuel_json_abi.rs
sway-core/src/ir_generation/convert.rs
sway-core/src/semantic_analysis/node_dependencies.rs
sway-core/src/type_system/id.rs
sway-core/src/type_system/info.rs
sway-core/src/type_system/substitute.rs

This PR adds the `TypeInfo::TypeParam` variant as part of #3744, but there are no instances of `TypeInfo::TypeParam` created. To be clear, it's not my preference to add a variant without additional code to test it, but if the compiler detects this variant it will reject the code during IR generation.

Add the `TypeInfo::TypeParam` variant but don't use it yet.

---

sway-core/src/control_flow_analysis/dead_code_analysis.rs
sway-core/src/language/ty/ast_node.rs
sway-core/src/language/ty/declaration/declaration.rs
sway-core/src/language/ty/program.rs
sway-core/src/semantic_analysis/namespace/module.rs
sway-core/src/semantic_analysis/namespace/root.rs

Small PR to remove a couple unneeded uses of `CompileResult`.

Remove a couple unneeded uses of `CompileResult`.

---

docs/book/src/basics/variables.md
templates/sway-test-rs/template/Cargo.toml
test/src/sdk-harness/Cargo.lock
test/src/sdk-harness/Cargo.toml
test/src/sdk-harness/test_projects/configurables_in_contract/.gitignore
test/src/sdk-harness/test_projects/configurables_in_contract/Forc.lock
test/src/sdk-harness/test_projects/configurables_in_contract/Forc.toml
test/src/sdk-harness/test_projects/configurables_in_contract/mod.rs
test/src/sdk-harness/test_projects/configurables_in_contract/src/main.sw
test/src/sdk-harness/test_projects/configurables_in_script/.gitignore
test/src/sdk-harness/test_projects/configurables_in_script/Forc.lock
test/src/sdk-harness/test_projects/configurables_in_script/Forc.toml
test/src/sdk-harness/test_projects/configurables_in_script/mod.rs
test/src/sdk-harness/test_projects/configurables_in_script/src/main.sw
test/src/sdk-harness/test_projects/harness.rs
test/src/sdk-harness/test_projects/logging/mod.rs
test/src/sdk-harness/test_projects/predicate_data_simple/mod.rs
test/src/sdk-harness/test_projects/predicate_data_struct/mod.rs
test/src/sdk-harness/test_projects/script_data/mod.rs
test/src/sdk-harness/test_projects/storage_vec/mod.rs
test/src/sdk-harness/test_projects/tx_fields/mod.rs

Closes #4206 
Three main changes: 
* Add new configuration-time constants tests to `sdk-harness`. This is important to make sure there are no regression in the backend.
* Add a new example for `configurable`
* Document `configurable`
* Had to bump to `fuels 0.37` to be able to update `configurable` variables from the SDK.

Bump to fuels `v0.37` and add a test and docs for `configurable` blocks

---

forc-pkg/src/pkg.rs
forc/src/cli/commands/test.rs
test/src/e2e_vm_tests/harness.rs
test/src/e2e_vm_tests/mod.rs

This introduces the `CompiledPackage` and `CompiledContractDependency` types in order to more accurately model the inputs and outputs of the `compile` function.
We also move the `name` and `target` fields from `BuiltPackage` into the `PackageDescriptor`, construct the descriptor earlier in the build process, and use the descriptor to consolidate more of the `compile` function arguments.
I started on refactoring some of the ABI generation related code, but realised that this might involve a more dedicated effort and opened #4208.

refactor(forc-pkg): Attempt to simplify build/compile fns by introducing dedicated types

---

forc-plugins/forc-doc/src/descriptor.rs
forc-plugins/forc-doc/src/render.rs
sway-core/src/control_flow_analysis/dead_code_analysis.rs
sway-core/src/ir_generation/function.rs
sway-core/src/language/ty/ast_node.rs
sway-core/src/language/ty/declaration/declaration.rs
sway-core/src/semantic_analysis/ast_node/code_block.rs
sway-core/src/semantic_analysis/ast_node/declaration/declaration.rs
sway-core/src/semantic_analysis/storage_only_types.rs
sway-core/src/type_system/binding.rs
sway-core/src/type_system/engine.rs
sway-lsp/src/capabilities/code_actions/mod.rs
sway-lsp/src/capabilities/code_actions/struct_decl/mod.rs
sway-lsp/src/capabilities/hover.rs
sway-lsp/src/core/token_map.rs
sway-lsp/src/traverse/dependency.rs
sway-lsp/src/traverse/typed_tree.rs
sway-lsp/src/utils/debug.rs

This PR fixes a regression to `TyDeclaration::StructDeclaration` and `TyDeclaration::EnumDeclaration` and removes the `DeclRef`s that they were holding.

Use `DeclId` directly for `TyDeclaration::StructDeclaration` and `TyDeclaration::EnumDeclaration`.

---

sway-parse/src/attribute.rs
sway-parse/src/item/mod.rs
sway-parse/src/lib.rs
sway-parse/src/module.rs
sway-parse/src/path.rs
sway-parse/src/test_utils.rs

This PR adds `mod sway_parse::test_utils` containing two utils, `fn parse<T>` and `fn parse_to_end<T>`, to replace non-generic utils like `fn parse_item`  or `fn parse_path_expr`.

Share utils between sway-parse unit tests

---

sway-core/src/decl_engine/id.rs

This basically gets rid of `PhantomData` noise in the default debug print.
Before:
`Constant(DeclRef { name: ID, id: DeclId(0, PhantomData<sway_core::language::ty::declaration::constant::TyConstantDeclaration>), decl_span: Span { as_str(): "ID" } })`
After:
`Constant(DeclRef { name: ID, id: DeclId(0), decl_span: Span { as_str(): "ID" } })`

Improve debug printing for `DeclId`.

---

sway-core/src/transform/to_parsed_lang/convert_parse_tree.rs
sway-core/src/type_system/unify_check.rs
test/src/e2e_vm_tests/test_programs/should_fail/wrongly_sized_tuple_destructuring/.gitignore
test/src/e2e_vm_tests/test_programs/should_fail/wrongly_sized_tuple_destructuring/Forc.lock
test/src/e2e_vm_tests/test_programs/should_fail/wrongly_sized_tuple_destructuring/Forc.toml
test/src/e2e_vm_tests/test_programs/should_fail/wrongly_sized_tuple_destructuring/src/main.sw
test/src/e2e_vm_tests/test_programs/should_fail/wrongly_sized_tuple_destructuring/test.toml
test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/call_basic_storage/src/main.sw

Fix #4270
Changed the way we convert the parse tree for tuple destructuring to add
an annotation of a tuple of the proper size of placeholder types.
e.g.:
```sway
let (a, b): (bool, u64) = c;
```
now gets desugared to something like
```
let __tuple: (bool, u64) = c
let __tuple: (_, _) = __tuple
let a: bool = __tuple.0;
let b: u64 = __tuple.1;
```
In the bad case (if `c` is something like `(bool, u64, u64)` it would no
longer type check for lack of being unifiable with `(_, _)`.
This required a small modification to the unification check to allow
placeholders on the right side.

Error out on wrongly sized tuple destructuring

---

Cargo.lock
sway-core/Cargo.toml
sway-core/src/build_config.rs
test/src/e2e_vm_tests/mod.rs
test/src/e2e_vm_tests/test_programs/should_pass/midenvm/midenvm_trivial/Forc.toml
test/src/e2e_vm_tests/test_programs/should_pass/midenvm/midenvm_trivial/test.toml
test/src/main.rs

We had two implementations for converting a string to a `BuildTarget` and they didn't match. (One accepted "miden-vm" or "midenvm" and the other "miden" or "midenvm".) Now only "midenvm" is accepted and we use the same codepath everywhere.

Make string representations of build targets consistent

---

sway-core/src/decl_engine/engine.rs
sway-core/src/decl_engine/id.rs
sway-core/src/decl_engine/ref.rs
sway-core/src/language/ty/declaration/declaration.rs
sway-core/src/language/ty/declaration/trait.rs
sway-core/src/language/ty/expression/expression_variant.rs
sway-core/src/semantic_analysis/ast_node/declaration/abi.rs
sway-core/src/semantic_analysis/ast_node/declaration/declaration.rs
sway-core/src/semantic_analysis/ast_node/expression/match_expression/typed/typed_scrutinee.rs
sway-core/src/semantic_analysis/ast_node/expression/typed_expression/function_application.rs
sway-core/src/semantic_analysis/ast_node/expression/typed_expression/method_application.rs
sway-core/src/semantic_analysis/namespace/trait_map.rs
sway-core/src/type_system/id.rs
sway-core/src/type_system/mod.rs
sway-core/src/type_system/substitute.rs

This PR updates the `DeclEngine` API to use more abstract implementations of `get`, `insert`, and `replace`. The goal of this PR is to move the `get` method into a separate trait so that there can be individual implementations for `DeclId` and `DeclRef`. In this PR there is no need to introduce different behavior between the two implementations, but there will be in the future.

Update `DeclEngine` API to use more abstract methods.

---

sway-core/src/decl_engine/ref.rs
sway-core/src/decl_engine/template.rs
sway-core/src/language/ty/declaration/declaration.rs
sway-core/src/language/ty/module.rs
sway-core/src/language/ty/program.rs
sway-core/src/monomorphize/constraint.rs
sway-core/src/monomorphize/gather/declaration.rs
sway-core/src/monomorphize/instruct/declaration.rs
sway-core/src/monomorphize/instructions.rs
sway-core/src/monomorphize/solve/solver.rs
sway-core/src/semantic_analysis/ast_node/code_block.rs
sway-core/src/semantic_analysis/ast_node/declaration/declaration.rs
sway-core/src/type_system/substitute.rs

Simple rename of `TypeSubstList` to `SubstList`.

Rename `TypeSubstList` to `SubstList`.

---

sway-lsp/src/capabilities/document_symbol.rs
sway-lsp/src/capabilities/semantic_tokens.rs
sway-lsp/src/core/token.rs
sway-lsp/src/traverse/parsed_tree.rs
sway-lsp/src/traverse/typed_tree.rs

Fixes incorrect semantic token definitions for `Self` and `self` tokens so they match how `rust-anaylzer` treats these tokens. Also adds simple docs for the variants in `SymbolKind`. 
closes #4058 
closes #4062

Fix semantic definitions for `Self` and `self` tokens

---

sway-core/src/language/ty/expression/scrutinee.rs
sway-core/src/semantic_analysis/ast_node/expression/match_expression/analysis/pattern.rs
sway-core/src/semantic_analysis/ast_node/expression/match_expression/typed/matcher.rs
sway-core/src/semantic_analysis/ast_node/expression/match_expression/typed/typed_scrutinee.rs
sway-lsp/src/traverse/typed_tree.rs

This PR refactors `TyScrutinee` to use `DeclRef`, where needed.

Refactor `TyScrutinee` to use `DeclRef`.

---

sway-core/src/semantic_analysis/ast_node/expression/typed_expression/enum_instantiation.rs
sway-core/src/semantic_analysis/ast_node/expression/typed_expression/struct_instantiation.rs
sway-core/src/type_system/engine.rs
sway-core/src/type_system/unify/unifier.rs

This method was obsolete and was adding unnecessary complexity, so this PR removes it 😄

Remove the obsolete `unify_adt` method.

---

sway-core/src/control_flow_analysis/dead_code_analysis.rs
test/src/e2e_vm_tests/test_programs/should_fail/type_alias_shadowing_methods/test.toml
test/src/e2e_vm_tests/test_programs/should_pass/dca/impl_unused_fn/Forc.lock
test/src/e2e_vm_tests/test_programs/should_pass/dca/impl_unused_fn/Forc.toml
test/src/e2e_vm_tests/test_programs/should_pass/dca/impl_unused_fn/src/main.sw
test/src/e2e_vm_tests/test_programs/should_pass/dca/impl_unused_fn/test.toml

When all of the impl methods are unused the whole impl block was marked as unused.
Now the compiler shows a DCA warning for the unused methods instead of a single warning for the impl block.
Closes #4311

Fixes DCA warning in impl block instead of method.

---

swayfmt/src/items/item_trait/mod.rs
swayfmt/src/items/item_trait/tests.rs

Closes #4359 
Closes #4360 
Simple fix because we weren't including the attributes into the formatting.

fix(fmt): item trait comment/annotation formatting

---

docs/book/src/introduction/installation.md

The current installation steps have rust and rustup dependencies at the bottom of the page, and its not clear to the user that they need it in order to install fuelup. This PR moves those instructions to the top of the page to make it intuitive.

streamline installation steps

---

Cargo.lock
forc-pkg/Cargo.toml
forc-plugins/forc-client/Cargo.toml
forc-plugins/forc-doc/Cargo.toml
forc-plugins/forc-fmt/Cargo.toml
forc-plugins/forc-lsp/Cargo.toml
forc-plugins/forc-tx/Cargo.toml
forc-test/Cargo.toml
forc-tracing/Cargo.toml
forc-util/Cargo.toml
forc/Cargo.toml
sway-ast/Cargo.toml
sway-core/Cargo.toml
sway-error/Cargo.toml
sway-ir/Cargo.toml
sway-ir/sway-ir-macros/Cargo.toml
sway-lsp/Cargo.toml
sway-parse/Cargo.toml
sway-types/Cargo.toml
sway-utils/Cargo.toml
swayfmt/Cargo.toml

Also ran `cargo update` because this is a breaking release.
Pending:

Bump to `v0.36.0`

---

sway-core/src/control_flow_analysis/dead_code_analysis.rs
sway-core/src/language/ty/declaration/declaration.rs
sway-core/src/semantic_analysis/ast_node/expression/match_expression/typed/typed_scrutinee.rs
sway-core/src/semantic_analysis/namespace/module.rs
sway-core/src/semantic_analysis/storage_only_types.rs
sway-core/src/type_system/ast_elements/binding.rs
sway-lsp/src/traverse/typed_tree.rs

This PR refactors the "EnumVariant" variant to use a `DeclRef` instead of a separate `DeclId` and `Template<SubstList>`.

Use a `DeclRef` for the "EnumVariant" variant.

---

.github/workflows/ci.yml

`cargo-test-lib-std` is only the job that seems to benefit from the faster runner. This is still quite beneficial though because this job is the bottleneck in our CI. I noticed a reduction from 16min to 8min or so.

Switch the `cargo-test-lib-std` CI job to use `buildjet-4vcpu-ubuntu-2204` (Speeding up CI ~2X)

---

sway-core/src/semantic_analysis/ast_node/declaration/function.rs
sway-core/src/semantic_analysis/ast_node/declaration/function/function_parameter.rs
test/src/e2e_vm_tests/test_programs/should_fail/abi_ref_mut/test.toml
test/src/e2e_vm_tests/test_programs/should_fail/mutable_fn_args_impl_self/Forc.lock
test/src/e2e_vm_tests/test_programs/should_fail/mutable_fn_args_impl_self/Forc.toml
test/src/e2e_vm_tests/test_programs/should_fail/mutable_fn_args_impl_self/json_abi_oracle.json
test/src/e2e_vm_tests/test_programs/should_fail/mutable_fn_args_impl_self/src/main.sw
test/src/e2e_vm_tests/test_programs/should_fail/mutable_fn_args_impl_self/test.toml

Closes https://github.com/FuelLabs/sway/issues/4438.

Fix ref mut parameter checking to apply to all function parameters.

---

sway-lib-std/src/u256.sw
test/src/e2e_vm_tests/test_programs/should_pass/stdlib/u256_mul_test/src/main.sw

There were issues in `U256` multiplication due to overflowing. Logic is fixed to take this into account
Related issue: https://github.com/FuelLabs/sway/issues/4376

U256 c fix

---

forc-plugins/forc-client/src/op/deploy.rs
forc-plugins/forc-client/src/op/run.rs
forc-plugins/forc-client/src/util/pkg.rs

closes #4374
@kayagokalp rightfully mentioned in the issue that the package descriptor is already contained within the `BuiltPackage` struct, which means we do not need this representation anymore:
> This is a nice abstractions but it made me think a little and I think returning Vec of (PackageManifestFile, Arc<BuiltPackage>) might be unnecessary at the first place from built_pkg_with_manifest function.
> 
> Every built package contains a package descriptor which contains the related package manifest so returning a tuple is kind of a data duplication.

chore: deprecate `built_pkgs_with_manifest()`

---

sway-lsp/src/capabilities/code_actions/mod.rs
sway-lsp/src/capabilities/code_actions/struct_decl/struct_new.rs
sway-lsp/src/capabilities/rename.rs
sway-lsp/src/core/mod.rs
sway-lsp/src/core/session.rs
sway-lsp/src/core/token_map.rs
sway-lsp/src/core/token_map_ext.rs
sway-lsp/src/server.rs
sway-lsp/tests/fixtures/renaming/src/test_mod.sw

This pull request implements the LSP highlighting capability, which allows for improved code readability. The addition includes:
- Implementing a custom iterator for the `TokenMap`, along with a new associated `TokenMapExt` trait.
- `all_references_of_token` has been implemented as an iterator. This allows us to filter the tokens that are operated on to be only those in the current file. for example.
```rust
self.token_map
.tokens_for_file(&url)
.all_references_of_token(&token, engines)
.map(|(ident, _)| get_range_from_span(&ident.span()))
.collect();
```
closes #2258

Add the LSP highlighting capability.

---

forc-util/src/lib.rs
forc/src/cli/commands/addr2line.rs
forc/src/cli/commands/build.rs
forc/src/cli/commands/check.rs
forc/src/cli/commands/clean.rs
forc/src/cli/commands/completions.rs
forc/src/cli/commands/contract_id.rs
forc/src/cli/commands/init.rs
forc/src/cli/commands/new.rs
forc/src/cli/commands/parse_bytecode.rs
forc/src/cli/commands/plugins.rs
forc/src/cli/commands/predicate_root.rs
forc/src/cli/commands/template.rs
forc/src/cli/commands/test.rs
forc/src/cli/commands/update.rs
forc/src/cli/mod.rs
forc/src/main.rs
forc/src/ops/forc_build.rs
forc/src/ops/forc_init.rs

closes #4420.
This PR introduces `ForcResult` and `ForcError` which enables us to return with custom exit code via propagating the desired exit code alongside the error message. Using `ForcResult` we can exit with different return code for different cases. Cargo uses similar approach for similar purposes.

refactor: Introduce `ForcResult` and `ForcError` to propagate return code with error message 

---

forc-util/src/lib.rs
forc/src/main.rs

closes #4461.
We introduced `ForcResult` in #4455. While implementing it I took a look at the cargo's design and saw that they also have `CargoCliResult` which did not make a lot of sense then but it looks like without that piece we cannot format the error nicely because of rust's orphan rule. This PR introduces `ForcCliResult` which enables us to return nice and clean errors.

refactor: better error formatting for `ForcResult`

---

sway-lsp/src/core/session.rs
sway-lsp/src/core/token.rs
sway-lsp/src/traverse/mod.rs
sway-lsp/src/traverse/typed_tree.rs

This PR finishes off migrating to use the `Parse` trait during AST traversal that was started in #4220. Once again, the diff is quite big but it's just essentially moving the logic that was there into the trait impl's.
closes #3799

LSP: Rewrite `TyProgram` traversal to use the `Parse` trait.

---

sway-lsp/src/capabilities/hover.rs
sway-lsp/tests/lib.rs

Closes https://github.com/FuelLabs/sway/issues/3967 https://github.com/FuelLabs/sway/issues/3966

Fix hover docs for self and boolean keywords

---

.github/workflows/ci.yml
sway-ast/src/brackets.rs

rust 1.69 is [released](https://blog.rust-lang.org/2023/04/20/Rust-1.69.0.html), this PR configures our CI to use 1.69 and fixes new lints raised by clippy v1.69.

ci: bump ci to use rust 1.69.0

---

Cargo.lock
forc-pkg/Cargo.toml
forc-plugins/forc-client/Cargo.toml
forc-plugins/forc-doc/Cargo.toml
forc-plugins/forc-fmt/Cargo.toml
forc-plugins/forc-lsp/Cargo.toml
forc-plugins/forc-tx/Cargo.toml
forc-test/Cargo.toml
forc-tracing/Cargo.toml
forc-util/Cargo.toml
forc/Cargo.toml
sway-ast/Cargo.toml
sway-core/Cargo.toml
sway-error/Cargo.toml
sway-ir/Cargo.toml
sway-ir/sway-ir-macros/Cargo.toml
sway-lsp/Cargo.toml
sway-parse/Cargo.toml
sway-types/Cargo.toml
sway-utils/Cargo.toml
swayfmt/Cargo.toml

See here for context: https://github.com/FuelLabs/sway/pull/4492#issuecomment-1520949069
This follows a re-release of 0.37.1 as 0.37.3: https://github.com/FuelLabs/sway/releases/tag/v0.37.3
The outcome of all this is that ideally, users previously on 0.37.1 will now pull 0.37.3 next time they run `cargo update` and will not encounter any breakage. Those ready to update can point to 0.38.0 after this is published.
Also runs `cargo update` in order to update deps to their latest patch release.

Re-publish 0.37.2 as 0.38.0 due to breaking changes

---

.github/workflows/ci.yml

Closes #4495 
Further explanation is on #4495, but the gist of it is that sometimes the verify tags step may fail but we do not get this feedback until all other jobs are already run since the check has all the other jobs as a pre-requisite.
Extracting this step out would give us immediate feedback instead of requiring us to wait 20-30 minutes. We may also add more pre-publish checks here.

ci: extract out verify_tags step from publish job into its own job

---

Cargo.lock
test/src/sdk-harness/Cargo.toml

CI is blocked by a breaking change in fuel-core 0.17.11

Run `cargo update`

---

sway-core/src/language/call_path.rs
sway-core/src/semantic_analysis/ast_node/expression/match_expression/typed/typed_scrutinee.rs
sway-core/src/semantic_analysis/ast_node/expression/typed_expression/method_application.rs
sway-core/src/transform/to_parsed_lang/convert_parse_tree.rs
sway-core/src/type_system/ast_elements/type_parameter.rs
sway-core/src/type_system/mod.rs
test/src/e2e_vm_tests/test_programs/should_pass/language/generic_impl_self_where/Forc.lock
test/src/e2e_vm_tests/test_programs/should_pass/language/generic_impl_self_where/Forc.toml
test/src/e2e_vm_tests/test_programs/should_pass/language/generic_impl_self_where/json_abi_oracle.json
test/src/e2e_vm_tests/test_programs/should_pass/language/generic_impl_self_where/src/main.sw
test/src/e2e_vm_tests/test_programs/should_pass/language/generic_impl_self_where/src/traits.sw
test/src/e2e_vm_tests/test_programs/should_pass/language/generic_impl_self_where/src/traits/nested_traits.sw
test/src/e2e_vm_tests/test_programs/should_pass/language/generic_impl_self_where/test.toml
test/src/e2e_vm_tests/test_programs/should_pass/language/where_clause_methods/Forc.lock
test/src/e2e_vm_tests/test_programs/should_pass/language/where_clause_methods/Forc.toml
test/src/e2e_vm_tests/test_programs/should_pass/language/where_clause_methods/json_abi_oracle.json
test/src/e2e_vm_tests/test_programs/should_pass/language/where_clause_methods/src/main.sw
test/src/e2e_vm_tests/test_programs/should_pass/language/where_clause_methods/test.toml

When where clauses were used in impl self methods with a generic parameter from
impl<T> an error was thrown saying `cannot find type "T" in this scope`
Parent type parameters that are used in method where clauses are now added to `FunctionDeclaration.type_parameters`.
This is needed for `TypeParameter::gather_decl_mapping_from_trait_constraints` to work properly as we need to have a type parameter with constraints. The generated decl_mapping is used by `type_check_method_application` to replace decls from trait constraints.
Closes #3333

Adds support for where clauses in impl self methods.

---

docs/book/src/forc/manifest_reference.md
docs/book/src/introduction/forc_project.md
forc-pkg/src/manifest.rs
sway-core/src/asm_generation/programs/final.rs

This change does three things.
First it repairs the output of the `--finalize-asm` build option so it actually outputs readable asm.
Second it updates the documentation on build profiles and in all occurences of `--print-finalize-asm` to use the new flag, use the correct names of build profile options and adds documentation for the new flags. Fixes #4481
Third, it lets the deserialization of the flags to use default values when the flags for a certain build profile are not all defined, so users can define a new build profile to tweak a small number of options and get the least surprising behavior.

Fix `--finalized-asm` output and docs

---

sway-ir/src/optimize/inline.rs
test/src/e2e_vm_tests/test_programs/should_pass/language/arg_demotion_inline/Forc.lock
test/src/e2e_vm_tests/test_programs/should_pass/language/arg_demotion_inline/Forc.toml
test/src/e2e_vm_tests/test_programs/should_pass/language/arg_demotion_inline/src/main.sw
test/src/e2e_vm_tests/test_programs/should_pass/language/arg_demotion_inline/test.toml
test/src/e2e_vm_tests/test_programs/should_pass/unit_tests/stack_indexing_overflow/Forc.lock

We currently don't support compiling functions with more than 6 args. Such functions are inlined. However, the inliner heuristic that checks this fails to say "inline" if there are 6 args, but the return type will be demoted later on, adding an additional arg. Fix that.
Fixes #4477.

Inlining heuristic: return value demotion adds arg

---

sway-lib-std/src/u256.sw

The `Ord` implementation for `U256` is incorrect and would have some values be both inferior and superior to each other at once which, among other things, breaks division.
Fixes #4513

Fix ordering bug in `U256`

---

sway-lib-std/src/storage/storage_vec.sw
test/src/e2e_vm_tests/test_programs/should_pass/empty_fields_in_storage_struct/Forc.toml
test/src/e2e_vm_tests/test_programs/should_pass/empty_fields_in_storage_struct/src/main.sw

Only some of the read/writes in `StorageVec` were updated to use `field_id` in https://github.com/FuelLabs/sway/pull/4537. For example, there are two writes when inserting, the length and value itself. Only the value was updated meaning the lengths would still be overwriting one another.
Tests to ensure both values and lengths are updated separately have been added.

Fix `StorageVec` bugs with use of `field_id`

---

sway-ir/src/printer.rs
test/src/ir_generation/tests/addr_of.sw
test/src/ir_generation/tests/eq.sw
test/src/ir_generation/tests/gt.sw
test/src/ir_generation/tests/is_reference_type.sw
test/src/ir_generation/tests/lt.sw
test/src/ir_generation/tests/ptr_add.sw
test/src/ir_generation/tests/ptr_sub.sw
test/src/ir_generation/tests/size_of.sw
test/src/ir_generation/tests/size_of_val.sw
test/src/ir_generation/tests/state_load_quad.sw
test/src/ir_generation/tests/state_load_word.sw
test/src/ir_generation/tests/state_store_quad.sw
test/src/ir_generation/tests/state_store_word.sw

Add missing tests for the ir generation of all intrinsics and fix a bug in the ir printer that elided the output value for `state_store_word`, `state_store_quad` and `state_load_quad`.

Add intrinsics tests

---

sway-core/src/asm_generation/fuel/checks.rs
sway-core/src/lib.rs
sway-ir/src/optimize/inline.rs
sway-ir/src/pass_manager.rs
test/src/ir_generation/mod.rs

Now that jumps are allowed in predicates, this change uses the regular inlining pass and its heuristics instead of just inlining everything, which slowed down compilation significantly.

Remove aggressive predicate inlining

---

.github/workflows/ci.yml

closes #4577.
Because of an upstream issue in `cargo-generate`, which can be seen from https://github.com/cargo-generate/cargo-generate/issues/942, our CI is blocked. Until the fix lands we need the `--locked` flag added to install step.

ci: use `--locked` while installing `cargo-generate`

---

sway-core/src/semantic_analysis/ast_node/declaration/enum.rs
sway-core/src/semantic_analysis/ast_node/declaration/function.rs
sway-core/src/semantic_analysis/ast_node/declaration/function/function_parameter.rs
sway-core/src/semantic_analysis/ast_node/declaration/impl_trait.rs
sway-core/src/semantic_analysis/ast_node/declaration/struct.rs
sway-core/src/semantic_analysis/ast_node/declaration/trait.rs
sway-core/src/semantic_analysis/ast_node/expression/typed_expression/enum_instantiation.rs
sway-core/src/semantic_analysis/ast_node/expression/typed_expression/struct_instantiation.rs
sway-core/src/type_system/ast_elements/type_parameter.rs
sway-core/src/type_system/id.rs
sway-error/src/error.rs
test/src/e2e_vm_tests/test_programs/should_fail/where_clause_traits/Forc.lock
test/src/e2e_vm_tests/test_programs/should_fail/where_clause_traits/Forc.toml
test/src/e2e_vm_tests/test_programs/should_fail/where_clause_traits/src/main.sw
test/src/e2e_vm_tests/test_programs/should_fail/where_clause_traits/test.toml
test/src/e2e_vm_tests/test_programs/should_pass/language/where_clause_traits/Forc.lock
test/src/e2e_vm_tests/test_programs/should_pass/language/where_clause_traits/Forc.toml
test/src/e2e_vm_tests/test_programs/should_pass/language/where_clause_traits/json_abi_oracle.json
test/src/e2e_vm_tests/test_programs/should_pass/language/where_clause_traits/src/main.sw
test/src/e2e_vm_tests/test_programs/should_pass/language/where_clause_traits/test.toml

With these changes where clauses are enabled for traits. This commit also adds error handling when an `impl` is created for a generic trait with where clause.
Generic traits are not supported yet on super traits or where clauses, when the support is added we should also perform the bounds check there.
Fixes #4560
Fixes #970

Enables where clauses for traits.

---

forc-pkg/src/manifest.rs
forc-pkg/src/pkg.rs
forc-plugins/forc-client/src/op/deploy.rs
forc-plugins/forc-client/src/op/run.rs
forc-plugins/forc-doc/src/main.rs
forc-test/src/lib.rs
forc/src/cli/commands/check.rs
forc/src/cli/commands/test.rs
forc/src/cli/shared.rs
forc/src/ops/forc_build.rs
forc/src/ops/forc_check.rs
forc/src/ops/forc_contract_id.rs
forc/src/ops/forc_predicate_root.rs
sway-core/src/build_config.rs
sway-core/src/lib.rs
sway-core/src/semantic_analysis/ast_node/expression/typed_expression.rs
sway-core/src/semantic_analysis/ast_node/expression/typed_expression/method_application.rs
sway-core/src/semantic_analysis/ast_node/mod.rs
sway-core/src/semantic_analysis/namespace/module.rs
sway-core/src/semantic_analysis/namespace/namespace.rs
sway-core/src/semantic_analysis/namespace/root.rs
sway-core/src/semantic_analysis/program.rs
sway-core/src/semantic_analysis/type_check_context.rs
sway-core/src/type_system/ast_elements/binding.rs
sway-core/src/type_system/engine.rs
sway-lsp/src/core/session.rs
test/src/e2e_vm_tests/harness.rs
test/src/ir_generation/mod.rs

Set experimental module privacy rules as the default and remove the experimental flag.
Closes #4506

Stabilize module privacy

---

.github/workflows/gh-pages.yml

Updates to `forc doc` changed the output structure of generated docs. This updates the publish directory so that mdbook can find the `index.html`.

fix: `std` publish directory

---

.github/workflows/gh-pages.yml

I missed the deploy path in #4590 , which currently makes the `/master/std` path break. This fixes that.

fix: `std` publish directory -- deploy step

---

.github/workflows/ci.yml

The checkout step was failing on a PR running from my fork because the PAT token is not setup in that case. This fixes that issue.

Fix forc-run-benchmarks checkout steps for non-PR CI builds

---

sway-core/src/semantic_analysis/ast_node/expression/intrinsic_function.rs
sway-lib-core/src/primitive_conversions.sw

This PR cleans up stdlib warnings that have accumulated.

Cleanup stdlib warnings

---

test/src/e2e_vm_tests/test_programs/should_pass/language/trait_method_qualified/src/main.sw

related to issues #4383 and #4563

Test dot method calls disambiguation with `self`

---

sway-lsp/src/core/session.rs
sway-lsp/src/core/sync.rs
sway-lsp/src/utils/keyword_docs.rs

This PR changes how we are watching for directory changes in the language server. Previously we were using tokio, this has now been changed to use a regular thread and `std::mpsc::channel`. We are about to move away from an `async` framework in the language server so this is a small effort towards removing reliance on tokio.

make dir watcher use std::thread instead of async

---

sway-lib-std/src/token.sw

The parameters to those functions take ContractId and Address respectively. Not Identity

Wrong example in documentation fixed

---

ci_checks.sh

closes #4678.
This PR updates `ci_checks.sh` so that `clippy` warnings are treated as errors, just like the CI. This improves the correspondence between ci and the `ci_checks.sh` script.

chore: make `clippy` warnings errors in `ci_checks` script

---

sway-lib-std/src/outputs.sw
test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/call_basic_storage/src/main.sw
test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/caller_context_test/src/main.sw
test/src/sdk-harness/Forc.lock
test/src/sdk-harness/Forc.toml
test/src/sdk-harness/test_artifacts/tx_output_predicate/Forc.lock
test/src/sdk-harness/test_artifacts/tx_output_predicate/Forc.toml
test/src/sdk-harness/test_artifacts/tx_output_predicate/src/main.sw
test/src/sdk-harness/test_projects/tx_fields/mod.rs

Added getters for the `GTF_OUTPUT_COIN_ASSET_ID` and `GTF_OUTPUT_COIN_TO` opcodes. These have been highly requested by external teams for use in predicates.
Note: The `output_asset_to()` getter currently returns a `b256` rather than an `Identity`. This should be updated when https://github.com/FuelLabs/sway/issues/4569 is resolved.

Add `GTF_OUTPUT_COIN_ASSET_ID` and `GTF_OUTPUT_COIN_TO` opcode getters

---

Cargo.toml
forc-plugins/forc-client/Cargo.toml

Fixes the following warning by moving `default-features = false` to workspace level:
```
warning: /Users/kayagokalp/fuel/dev/sway/forc-plugins/forc-client/Cargo.toml: `default-features` is ignored for fuel-core-client, since `default-features` was not specified for `workspace.dependencies.fuel-core-client`, this could become a hard error in the future
```

chore: fix default-feature warning for forc-client

---

docs/book/src/common-collections/storage_map.md

Storage naps sound fun, but I think we meant storage maps here.

Fix documentation typo

---

sway-lib-std/src/bytes.sw
sway-lib-std/src/low_level_call.sw
sway-lib-std/src/storage/storage_bytes.sw
test/src/sdk-harness/test_projects/storage_bytes/src/main.sw

The current use of converting `Bytes` to and from `raw_slice` and `Vec` use a special define function. This should use the `From` trait.
> Note: This is a breaking change.

Refactor `Bytes` type to use `From` trait

---

Cargo.lock
forc-pkg/Cargo.toml

Bumps git2-rs to 0.17.2, so that forc requires libgit2 v1.6.4 to compile. This is needed as fuel.nix flake is in a deadlock; sysinfo dependency introduced in #4564 requires us to bump macos sdk versions while libgit2 v0.1.5.1 fails to compile with the bumped SDK version.

chore: bump git2-rs version to 0.17.2 and required libgit2 to v1.6.4

---

docs/reference/src/code/Forc.lock
docs/reference/src/code/language/style-guide/pattern_matching/Forc.toml

Style guide example is blocking new releases because it tries to use an unpublished version of std

Fix style guide example not using local std

---

sway-lib-std/src/lib.sw
sway-lib-std/src/string.sw

Create a minimal, forward compatible unicode string type that only accepts ASCII input and doesn't provide mutation of codepoints.
This should provide Sway-Standards with a proper black box type to use while still giving us a good platform to later implement a proper, `char` based unicode string without compatibility issues.
Follow-up from #4710

Minimal String type

---

Cargo.toml

I noticed the following warning was printing to the console when building `forc`
```
warning: profile package spec `sway-lsp` in profile `dev` did not match any packages
```
This flag isn't being used as we are using tracing now in the language server to set debug levels so we can safely remove this from the workspace `Cargo.toml`.

remove unused debug flag

---

sway-lsp/src/lib.rs
sway-lsp/src/server.rs

Inlay hints haven't been working for me, and I see this error in the LSP server logs:
```
Got a textDocument/inlayHint request, but it is not implemented
[Trace - 10:53:49 AM] Received response 'textDocument/inlayHint - (11)' in 1ms. Request failed: Method not found (-32601).
[Error - 10:53:49 AM] Request textDocument/inlayHint failed.
```
This change fixes it for me locally.

Fix inlay hints

---

examples/storage_variables/src/main.sw

Document clarification around ensuring .unwrap_or(0) is used for storage read examples.

Doc storage read unwrap_or clarification.

---

sway-lib-std/src/string.sw

Add a convenience method to convert string literals to the tentative dynamically sized `String` like so:
```sway
String::from_ascii_str("Lorem Ipsum")
```

Conversion from `str` literals to `String`

---

.github/workflows/ci.yml

rust v1.70 is [released](https://blog.rust-lang.org/2023/06/01/Rust-1.70.0.html) and probably most of us are using that version. This PR bumps CI to that version.

ci: bump rust version to 1.70

---

sway-lib-std/src/block.sw
test/src/e2e_vm_tests/test_programs/should_pass/stdlib/block_height/src/main.sw
test/src/sdk-harness/test_artifacts/block_test_abi/src/main.sw
test/src/sdk-harness/test_projects/block/src/main.sw

The fuel specification consistently refers to the block height as an unsigned 32 bit integer, which is also what the SDK uses, this change brings the Sway standard library in line with the spec.

Fix block height type to conform to spec

---

Cargo.lock
forc-plugins/forc-client/Cargo.toml
forc-plugins/forc-client/src/cmd/deploy.rs
forc-plugins/forc-client/src/cmd/run.rs
forc-plugins/forc-client/src/op/deploy.rs
forc-plugins/forc-client/src/op/run.rs
forc-plugins/forc-client/src/util/tx.rs

closes #4743.
This PR integrates forc-wallet and forc-deploy together so that forc-deploy can offer to sign your transactions without running a second terminal window. Below there are some inputs and outputs after this change.
```console
forc-deploy --random-salt
```
```console
Contract id: 0x77e0c380dff45759d1a16b6add83d0fd38e8d86ddd0c96cd5117c82b6d958edb
Please provide the password of your encrypted wallet vault at "/Users/kayagokalp/.fuel/wallets/.wallet":
```
At this point if the user enters wrong password:
```console
Contract id: 0x77e0c380dff45759d1a16b6add83d0fd38e8d86ddd0c96cd5117c82b6d958edb
Please provide the password of your encrypted wallet vault at "/Users/kayagokalp/.fuel/wallets/.wallet":
Error: Failed to access forc-wallet vault. Please check your password
```
If the user …

feat: integrate forc-wallet and forc-deploy

---

forc-plugins/forc-client/src/op/deploy.rs
forc-plugins/forc-client/src/util/tx.rs

closes #4043.
Improves error message by stating the failure reason clearly if the reason is insufficient funds. If the transaction is failing due to insufficient funds we are outputing:
```console
Contract id: 0xa8f18533afc18453323bdf17c83750c556916ab183daacf46d7a8d3c633a40ee
Please provide the password of your encrypted wallet vault at "/Users/kayagokalp/.fuel/wallets/.wallet":
Do you accept to sign this transaction with fuel1egx2nvm4395gukm8uyh4zzxdlx3hht9ulu6n67nhwq57zs74camskx7klp [y/N]:y
Error: Deployment failed due to insufficient funds. Please be sure to have enough coins to pay for deployment transaction.
```
We will have a balance checking mechanism before signing the transaction for test-net which would make this error only visible to manual signers and people that are working …

feat: improve error message in case of insufficient funds

---

forc-plugins/forc-client/src/cmd/deploy.rs
forc-plugins/forc-client/src/op/deploy.rs
test/src/e2e_vm_tests/harness.rs

closes #4758.
This PR makes --random-salt the default behaviour of forc-deploy, if salt information is passed, the passed salt would be used but otherwise, random-salt would be implied by default. Also adds --default-salt for CI so that in CI we can always create the same contract id if we want to. Useful for reproducible deployments.

feat: make `--random-salt` default to forc-deploy and remove it as a flag

---

forc-plugins/forc-client/src/cmd/deploy.rs
forc-plugins/forc-client/src/lib.rs
forc-plugins/forc-client/src/op/deploy.rs
forc-plugins/forc-client/src/util/mod.rs

closes #4759.
Adds --target parameter to forc-deploy which can take `beta-2`, `beta-3` or `latest`. If nothing is specified it defaults to `latest`. If `beta-2` or `beta-3` is specified, preset values are used for node-url and gas price so that users can deploy with a single parameter. So `forc deploy --target beta-3` would work but since forc-deploy is not compatible with beta-3 that feature will fail until we have a beta-4 released.
Also adds `--testnet` flag which is translated into a `--target beta-3`. So once a beta network release is done with this additions, users will be able to simply use
```console
forc deploy --testnet
```
to deploy to the latest test-net supported by that forc-deploy version

 feat: add `--target` and `--testnet` parameters to `forc-deploy`

---

test/src/e2e_vm_tests/test_programs/should_pass/unit_tests/regalloc_spill/Forc.lock
test/src/e2e_vm_tests/test_programs/should_pass/unit_tests/regalloc_spill/Forc.toml

closes #4774.
This PR removes std library dependency for regalloc unit test so that we can publish a new version without blocking our CI. In general we should either not depend on std or we should only depend it by explicitly depending on it by path. Otherwise we cannot bump version in our repo.
unblocks: #4767

fix: remove dependency on std for `regalloc_spill` unit test

---

sway-core/src/language/ty/ast_node.rs
test/src/e2e_vm_tests/test_programs/should_pass/language/generic_where_in_impl_self2/Forc.lock
test/src/e2e_vm_tests/test_programs/should_pass/language/generic_where_in_impl_self2/Forc.toml
test/src/e2e_vm_tests/test_programs/should_pass/language/generic_where_in_impl_self2/json_abi_oracle.json
test/src/e2e_vm_tests/test_programs/should_pass/language/generic_where_in_impl_self2/src/main.sw
test/src/e2e_vm_tests/test_programs/should_pass/language/generic_where_in_impl_self2/test.toml

We were not calling replace_decl for variable declarations.
This was making some trait method calls to not be replaced.
Unblocks #4701
Fixes #4773

Fixes missing replace_decl for variable declarations.

---

sway-ir/src/optimize.rs
sway-ir/src/optimize/constants.rs
sway-ir/src/parser.rs
test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/call_basic_storage/src/main.sw
test/src/ir_generation/mod.rs
test/src/ir_generation/tests/let_const_init.sw
test/src/ir_generation/tests/local_const_init.sw
test/src/main.rs

Closes https://github.com/FuelLabs/sway/issues/4708.
This PR does NOT change the IR generation for expressions. Instead, it implements constant folding for unary and binary operators. The idea is that  IR generation will be kept simple and stable, and all optimizations are pushed onto the opt passes.
To better test this, this PR also changes some implementation details on IR generation tests:
1 - `filecheck` directives are now collected and tested in groups. This allows a new "::check-ir-optimized::", that can be configured with the passes you want to test, or just fallback to "o1".
2 - `filechecker` explanations are now pretty-printed, and can be printed when `verbose=true`. This allows the test to be checked more easily.
`breaking` label because of this change: …

constcombine pass optimizing unary and binary operators

---

sway-core/src/semantic_analysis/ast_node/declaration/abi.rs
sway-core/src/semantic_analysis/ast_node/expression/typed_expression/method_application.rs
sway-error/src/error.rs
test/src/e2e_vm_tests/test_programs/should_fail/contract_calls_its_method/Forc.lock
test/src/e2e_vm_tests/test_programs/should_fail/contract_calls_its_method/Forc.toml
test/src/e2e_vm_tests/test_programs/should_fail/contract_calls_its_method/src/main.sw
test/src/e2e_vm_tests/test_programs/should_fail/contract_calls_its_method/test.toml

close #1491
We add ABI methods to the namespace (this is going to be useful for the super-ABI feature) and filter out same contract method calls during method application typechecking, instead of not adding ABI methods to the namespace and providing a bit confusing error message like `No method named "method1" found for type "contract".`

Improve error message when contract calls its own method

---

sway-lib-std/src/u256.sw

The `From` trait already lets one to decompose a `u256` into four 64-bit words. Also, there is no `compose` for `u256` (unlike `b256`, which has both at the moment).

stdlib: remove `decompose` function for `u256`

---

sway-lib-core/src/ops.sw
sway-lib-std/src/flags.sw
sway-lib-std/src/u128.sw
test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/call_basic_storage/src/main.sw
test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/call_increment_contract/src/main.sw

- Changes `disable_panic_on_overflow()` function to return the flags set prior to calling the function
- Adds a `set_flags` function that simply sets the given value to the flag register
- Changed u64 `overflowing_add` and `overflowing_mul` to use the new functions
- Adds equivalent functions for unsafe-math flag aswell
- Additional documentation for all functions in the library
closes #4355

Improve flag library functionality

---

examples/Forc.lock
examples/ownership/Forc.toml
examples/ownership/src/main.sw

It was noted that in the case of a breaking change to the std-lib, the external Ownership library would need to be updated, which depended on the std-lib creating a circular dependency.
The external library has been removed from the example and a skeleton of its implementation has been added with a link to the actual implementation.

Remove dependency on external library for Ownership example

---

sway-lib-std/src/storage/storable_slice.sw
sway-lib-std/src/storage/storage_api.sw
sway-lib-std/src/storage/storage_bytes.sw
sway-lib-std/src/storage/storage_key.sw
sway-lib-std/src/storage/storage_map.sw
sway-lib-std/src/storage/storage_string.sw
sway-lib-std/src/storage/storage_vec.sw

Updating the storage inline docs to follow the new SRC-2 inline docs standard. Note that this is being merged into the staging branch
Closes the following tasks of https://github.com/FuelLabs/sway/issues/4812 
storage/storable_slice.sw
storage/storage_api.sw
storage/storage_bytes.sw
storage/storage_key.sw
storage/storage_map.sw
storage/storage_string.sw
storage/storage_vec.sw

Update all storage inline docs to follow SRC-2 standard

---

.github/workflows/ci.yml

Unused dependency check is failing as nightly version that we use for that step is too old for fuels-program v0.44 dependency which is being added in a separate PR. (failing PR: #4771)

ci: bump nightly rust version to 2023-04-01

---

sway-core/src/asm_generation/fuel/functions.rs
sway-core/src/asm_generation/fuel/register_allocator.rs
sway-ir/src/optimize/dce.rs
sway-ir/src/optimize/inline.rs
sway-ir/tests/dce/dce3.ir
test/src/e2e_vm_tests/test_programs/should_pass/language/configurable_consts/json_abi_oracle.json
test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/array_of_structs_caller/src/main.sw
test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/call_abi_with_tuples/src/main.sw
test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/call_basic_storage/src/main.sw
test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/call_contract_with_type_aliases/src/main.sw
test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/call_increment_contract/src/main.sw
test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/caller_context_test/src/main.sw
test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/nested_struct_args_caller/src/main.sw
test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/storage_access_caller/src/main.sw
test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/token_ops_test/src/main.sw
test/src/ir_generation/tests/fn_call.sw

This was required previously, but after the IR refactoring (#4336), this is no longer required, and actually worsens things.
Fixes #4747. For the two tests mentioned there, (both based on https://github.com/hashcloak/fuel-crypto/) the compile time now comes down from 
1. 30m -> 16s
2. 180m -> 31s
Also fixes two bugs uncovered:
1. Bug in DCE - Fixes #4763. (https://github.com/FuelLabs/sway/pull/4823/commits/1b512b87d2273ecd7d34da4a67b40f2f43305123)
2. Bug in interaction b/w asm gen and reg alloc spiller (https://github.com/FuelLabs/sway/pull/4823/commits/7a404967e732af52bd60e36766df461688c01fff).

Don't force inliner in case of ref type function args

---

sway-core/src/language/parsed/module.rs
sway-core/src/lib.rs
sway-core/src/semantic_analysis/module.rs
sway-lsp/src/server_state.rs
sway-lsp/src/traverse/parsed_tree.rs

This PR replaces collecting the dummy spans for the module kind token with the span of the module kind. 
These were introduced in #4232. This was causing an issue in the language server where we were unable to debug parsed tokens as warnings if the span was all 0's. 
closes #4809

Collect module kind span for ParseModule

---

forc-pkg/src/pkg.rs
sway-core/src/abi_generation/evm_abi.rs
sway-core/src/abi_generation/fuel_abi.rs
sway-core/src/abi_generation/mod.rs

This PR clears up usage of terms "ABI" (our actual ABI) and "JSON ABI" (the JSON representation of our ABI).
What we really actually have here is the "Rust ABI" but we can drop the "Rust" and just call it "ABI".
Other ABIs would be the "TypeScript ABI" generated by fuels-ts, and the "GraphQL ABI" I'm planning to work on.

Correct usage of terms "ABI" and "JSON ABI"

---

sway-core/src/lib.rs

These have been introduced in https://github.com/FuelLabs/sway/commit/b33b63c1081ac7f6e932c7747a5aa6aacc36cae4.

Fix clippy warnings introduced recently.

---

sway-lsp/tests/utils/src/lib.rs

~~Temporarily removing the `publish_diagnostics_dead_code_warning` test so it unblocks our CI until I can work out how to fix it.~~
Managed to fix the test while this was open. We now no longer timeout waiting for the requests and instead await until they are ready. 
Closes #4855

Fix flaky lsp test: publish_diagnostics_dead_code_warning

---

sway-lib-core/src/primitive_conversions.sw
sway-lib-core/src/primitives.sw
sway-lib-core/src/raw_ptr.sw
sway-lib-std/src/address.sw
sway-lib-std/src/b512.sw
sway-lib-std/src/bytes.sw
sway-lib-std/src/contract_id.sw
sway-lib-std/src/identity.sw
sway-lib-std/src/option.sw
sway-lib-std/src/result.sw
sway-lib-std/src/string.sw
sway-lib-std/src/u128.sw
sway-lib-std/src/u256.sw
sway-lib-std/src/vec.sw
sway-lib-std/src/vm/evm/evm_address.sw

In Rust, when implementing traits the type `Self` is used instead of the concrete type. This provides a more flexible and generic API design and it promotes code reusability and simplifies the creation of fluent interfaces. The same has now been done for Sway.

Use the `Self` annotation in implementation blocks

---

sway-core/src/language/call_path.rs

avoids the extra `String` alloc from `to_string()`.
Closes #2225

Update `CallPath<T>` impl of `Display`

---

sway-lib-core/src/storage.sw
sway-lib-std/src/storage/storage_api.sw
sway-lib-std/src/storage/storage_bytes.sw
sway-lib-std/src/storage/storage_string.sw

It was noted that the most recent updates to the storage docs did not include imports for examples. This has been added.
Documentation of the `StorageKey` type has also been included, completing the storage.sw task of https://github.com/FuelLabs/sway/issues/4812

Updates to storage docs to meet SRC-2 inline docs standard

---

sway-lib-std/src/address.sw
sway-lib-std/src/contract_id.sw
sway-lib-std/src/identity.sw
sway-lsp/tests/lib.rs

Updated the `contract_id.sw`, `address.sw`, and `identity.sw` files to meet the SRC-2 inline documentation standard.
This PR completes the following tasks of https://github.com/FuelLabs/sway/issues/4812 
- address.sw
- contract_id.sw
- identity.sw

Update inline docs of address, contract id, and identity to meet SRC-2 standards

---

sway-lsp/src/core/sync.rs
sway-lsp/src/handlers/notification.rs
sway-lsp/src/server.rs
sway-lsp/src/server_state.rs

This PR just bubbles up any errors to be logged in the server module rather that in the `did_change` `did_open` or `did_save` methods. Also made the resync temp folder with workspace logic it's own method on `sync`.

refactor did_* lsp notifications to log errors in server module

---

sway-core/src/decl_engine/mapping.rs
sway-core/src/decl_engine/mod.rs
sway-core/src/decl_engine/ref.rs
sway-core/src/decl_engine/replace_decls.rs
sway-core/src/language/ty/ast_node.rs
sway-core/src/language/ty/code_block.rs
sway-core/src/language/ty/declaration/constant.rs
sway-core/src/language/ty/declaration/function.rs
sway-core/src/language/ty/expression/expression.rs
sway-core/src/language/ty/expression/expression_variant.rs
sway-core/src/language/ty/expression/reassignment.rs
sway-core/src/language/ty/expression/struct_exp_field.rs
sway-core/src/semantic_analysis/ast_node/declaration/impl_trait.rs
sway-core/src/semantic_analysis/ast_node/declaration/trait.rs
sway-core/src/semantic_analysis/ast_node/expression/typed_expression/function_application.rs
sway-core/src/semantic_analysis/ast_node/expression/typed_expression/method_application.rs
sway-core/src/semantic_analysis/namespace/namespace.rs
sway-core/src/type_system/ast_elements/type_parameter.rs
test/src/e2e_vm_tests/test_programs/should_pass/language/generic_tuple_trait/src/main.sw

When a single method uses multiple trait implementation errors are thrown by the compiler similar issue occurs when a method requires a trait implementation and then calls another method that requires another implementation of the same trait.
This PR fixes both issues by filtering traits to be replaced by the arguments type used and trait method self type, and by gathering decl mapping of nested methods.
Fixes #4852

Fixes replace_decls issue with nested and multiple types.

---

.github/workflows/gh-pages.yml

The regular runner runs out of memory at this point, switching to this one should solve this problem.

Use buildjet runner for gh-pages workflow

---

swayfmt/src/comments.rs
swayfmt/src/formatter/mod.rs
swayfmt/src/items/item_fn/mod.rs
swayfmt/src/items/item_impl/tests.rs
swayfmt/src/parse.rs

Closes https://github.com/FuelLabs/sway/issues/4824
- Added a test. I had to modify the test macro for it to recognize comments in test cases.

Fix indentation for closing brace after comment

---

sway-ast/src/expr/mod.rs
sway-parse/src/attribute.rs
sway-parse/src/expr/mod.rs
sway-parse/src/module.rs
sway-parse/src/parser.rs
sway-parse/tests/noop_script.rs
swayfmt/src/items/item_fn/tests.rs
swayfmt/src/utils/language/expr/code_block.rs
swayfmt/src/utils/language/expr/conditional.rs
swayfmt/src/utils/language/literal.rs

Closes https://github.com/FuelLabs/sway/issues/4935
- In order to write comments for the else block when it only contains a comment, I had to add the span to `CodeBlockContents`

Fix formatting conditionals with comments

---

swayfmt/src/comments.rs
swayfmt/src/formatter/mod.rs
swayfmt/src/formatter/shape.rs
swayfmt/src/items/item_abi.rs
swayfmt/src/items/item_configurable/mod.rs
swayfmt/src/items/item_enum/mod.rs
swayfmt/src/items/item_fn/mod.rs
swayfmt/src/items/item_impl/mod.rs
swayfmt/src/items/item_storage/mod.rs
swayfmt/src/items/item_struct/mod.rs
swayfmt/src/items/item_trait/mod.rs
swayfmt/src/items/item_use/mod.rs
swayfmt/src/utils/language/attribute.rs
swayfmt/src/utils/language/expr/asm_block.rs
swayfmt/src/utils/language/expr/code_block.rs
swayfmt/src/utils/language/expr/collections.rs
swayfmt/src/utils/language/expr/conditional.rs
swayfmt/src/utils/language/expr/mod.rs
swayfmt/src/utils/language/expr/struct_field.rs
swayfmt/src/utils/language/pattern.rs
swayfmt/src/utils/language/punctuated.rs
swayfmt/src/utils/language/where_clause.rs

Simply adding some utility functions in the formatter to make the code easier to read.

Refactor indent utilies for readability

---

docs/reference/src/documentation/introduction/installation/cargo.md
docs/reference/src/documentation/introduction/installation/index.md
docs/reference/src/documentation/introduction/installation/source.md
docs/reference/src/index.md

related to #4946.
Directly using `/latest` instead of exact versioning does not work for some reason. To unblock bump PRs (one waiting, #4945) this PR disables link checks at links which uses exact latest versions. We should find a way to point to `latest` without using an exact version.

docs-ci: temporarily disable check-links for exact version usages in docs

---

forc-plugins/forc-client/src/util/tx.rs

closes #4861.
This PR derives first account after creating a fresh wallet via forc-deploy so that we have at least one account available for users to chose from.

feat: derive first account with forc-deploy after creating a wallet

---

forc-plugins/forc-client/src/lib.rs
forc-plugins/forc-client/src/util/tx.rs

closes #4862.
waiting for #4905 to be merged first.
With this PR, we are now pointing empty accounts to beta-4 faucet with their address already inserted so that people can click on it and get funded.
```console
Please provide the password of your encrypted wallet vault at "/Users/kayagokalp/.fuel/wallets/.wallet": 
Error: Your wallet does not have any funds to pay for the transaction.
If you are interacting with a testnet consider using the faucet.
-> beta-4 network faucet: https://faucet-beta-4.fuel.network/?address=fuel1l6su7ldka75ntmz7vx05tfznshxjpa4ftt4p537vl2ck45a5p5tsmwjevm
If you are interacting with a local node, consider providing a chainConfig which funds your account.
```

feat: forc-client points empty accounts to beta-4 faucet

---

sway-error/src/parser_error.rs
sway-parse/src/attribute.rs
test/src/e2e_vm_tests/test_programs/should_fail/annotated_missing_item/Forc.lock
test/src/e2e_vm_tests/test_programs/should_fail/annotated_missing_item/Forc.toml
test/src/e2e_vm_tests/test_programs/should_fail/annotated_missing_item/src/main.sw
test/src/e2e_vm_tests/test_programs/should_fail/annotated_missing_item/test.toml

This PR closes https://github.com/FuelLabs/sway/issues/4968. The problem here is that doc comments are special in the sense that they demand an item after. 
I am following the `rustc` error message of my machine, but rust playground message is a little different. Not sure which way we want to go.
https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=34097e067111a355e70767be7965952c

better error message for doc comment without an item

---

docs/book/src/sway-program-types/libraries.md

`nft` module in `sway-libs` moved and some of our links are dead after https://github.com/FuelLabs/sway-libs/pull/185. This PR fixes links so that they pointing to the new position. This blocks our CI.

docs: fix nft example links in docs

---

sway-core/src/type_system/ast_elements/binding.rs

The type resolution function calls this function at a later stage, hence this one is not needed.
This makes trait map sizes smaller and saves a bunch of type ids.
Partially resolves issue #5002

Remove extra insert_trait_implementation_for_type

---

sway-lsp/src/capabilities/diagnostic.rs
sway-lsp/src/core/session.rs
sway-lsp/src/server_state.rs
sway-lsp/tests/fixtures/diagnostics/multi_file/Forc.toml
sway-lsp/tests/fixtures/diagnostics/multi_file/expected.json
sway-lsp/tests/fixtures/diagnostics/multi_file/src/adt_tests.sw
sway-lsp/tests/fixtures/diagnostics/multi_file/src/complex_tests.sw
sway-lsp/tests/fixtures/diagnostics/multi_file/src/main.sw
sway-lsp/tests/fixtures/diagnostics/multi_file/src/or_patterns.sw
sway-lsp/tests/fixtures/diagnostics/multi_file/src/primitive_tests.sw
sway-lsp/tests/lib.rs

Closes https://github.com/FuelLabs/sway/issues/5027
Now instead of caching the `Diagnostics` object, we cache a mapping of file path -> `Diagnostics`
When we publish diagnostics, we only publishing the diagnostics for the given URI, not for the entire project. I added a test where there are no diagnostics in the main.sw file, but a bunch of diagnostics in the other files in the project.

Fix diagnostics in multi file projects

---

sway-lib-std/src/storage/storage_map.sw

Currently, any type may be included as a key value to the `StorageMap<K, V>` type. This presents an issue as the type must be hashable in order to generate the key. 
A where clause has been added to the function definition.
This should open the door for using heap types(`String`, `Bytes`) as key values for the `StorageMap` type however, this will require additional compiler changes.

Ensure generic values used with a `StorageMap` are hashable

---

sway-lib-std/src/string.sw

The `Eq` implementation seems to have been missing since moving the `String` type from sway-libs to the standard library.

Add `Eq` implementation for `String`

---

sway-core/src/ir_generation/compile.rs
sway-core/src/language/call_path.rs
sway-core/src/language/ty/declaration/function.rs
sway-core/src/semantic_analysis/ast_node/declaration/function.rs
sway-core/src/semantic_analysis/ast_node/declaration/trait_fn.rs
sway-core/src/semantic_analysis/ast_node/mod.rs
test/src/e2e_vm_tests/test_programs/should_pass/stdlib/assert_eq_u256_revert/.gitignore
test/src/e2e_vm_tests/test_programs/should_pass/stdlib/assert_eq_u256_revert/Forc.lock
test/src/e2e_vm_tests/test_programs/should_pass/stdlib/assert_eq_u256_revert/Forc.toml
test/src/e2e_vm_tests/test_programs/should_pass/stdlib/assert_eq_u256_revert/json_abi_oracle.json
test/src/e2e_vm_tests/test_programs/should_pass/stdlib/assert_eq_u256_revert/src/main.sw
test/src/e2e_vm_tests/test_programs/should_pass/stdlib/assert_eq_u256_revert/test.toml

The issue was occurring because `get_items_for_type_and_trait_name` was comparing an absolute call path to an external relative call path, when the second should also be absolute.
`compile_fn` now checks if method is trait dummy.
These changes should avoid the silent failures where a dummy method is used,
instead of the proper implementation.
Closes #4989

Fixes assert_eq always passing for U256

---

templates/sway-test-rs/template/Cargo.toml
templates/sway-test-rs/template/tests/harness.rs

- Bumps the test harness for the [quickstart](https://github.com/FuelLabs/fuel-docs/blob/master/src/quickstart/smart-contract.md) to match beta-4
- Adds [changes ](https://github.com/FuelLabs/fuel-docs/pull/102) suggested by @segfault-magnet for storage initialization on rust sdk testing. Due to the sdk storage initialization issue [fuels-rs/issues/111](https://github.com/FuelLabs/fuels-rs/issues/1117)

feat: sway-test-rs load store config & beta-4 bump

---

sway-lsp/benches/lsp_benchmarks/compile.rs
sway-lsp/src/core/session.rs

This PR splits the compilation and traversal stages into separate functions. This allows us to benchmark each part separately from the other. 
related to #5001 
The current measurements are below.
| Request Type/Method    | Time  
|------------------------|-----------|
| compile   | 2.4822s   |
traverse   | 422ms   |

Split compilation and traversal stages

---

Cargo.lock
sway-lsp/Cargo.toml
sway-lsp/src/core/session.rs
sway-lsp/src/core/token_map.rs
sway-lsp/src/traverse/lexed_tree.rs
sway-lsp/src/traverse/parsed_tree.rs
sway-lsp/src/traverse/typed_tree.rs

This PR introduces using rayon's parallel iterators when traversing the lexed and parsed AST's. I initially extended this to also occur on the typed AST but was running into deadlock issues with how DashMap works. 
closes #4959
| Request Type/Method    | Previous  | New      | Improvement % |
|------------------------|-----------|----------|---------------|
| compile_and_traverse   | 2.7732s   | 2.5632s  | 7.57%         |
**edit**
I've split the compilation and traversal stages so they can be benchmarked independently. Here are the actual traversal performance results.
| Request Type/Method    | Previous  | New      | Improvement % |
|------------------------|-----------|----------|---------------|
| traverse   | 422ms   | 211ms  | 50.0%         |

Parallelize traversing AST's in the language server

---

sway-lsp/src/capabilities/hover/mod.rs
sway-lsp/src/core/token.rs
sway-lsp/src/core/token_map.rs
sway-lsp/src/traverse/typed_tree.rs

This is a minor PR to fix all the clippy warnings

Fix clippy warnings

---

sway-lib-std/src/call_frames.sw
sway-lib-std/src/contract_id.sw
test/src/sdk-harness/test_artifacts/call_frames_test_abi/src/main.sw
test/src/sdk-harness/test_projects/call_frames/mod.rs
test/src/sdk-harness/test_projects/call_frames/src/main.sw

Adds a `ContractId::this()` method, equivalent to `std::call_frames::contract_id()`. For ease of use.

Add a "this" method to ContractId

---

swayfmt/src/formatter/mod.rs
swayfmt/tests/mod.rs

Fixed formatting of `Module` doc comments

---

forc-util/src/lib.rs
sway-core/src/semantic_analysis/ast_node/expression/typed_expression.rs
sway-error/src/diagnostic.rs
sway-error/src/error.rs
sway-error/src/warning.rs
test/src/e2e_vm_tests/test_programs/should_fail/match_expressions_duplicate_variables/test.toml
test/src/e2e_vm_tests/test_programs/should_fail/match_expressions_non_exhaustive/test.toml
test/src/e2e_vm_tests/test_programs/should_fail/shadowing/shadowed_consts_and_vars/test.toml
test/src/e2e_vm_tests/test_programs/should_fail/shadowing/shadowed_consts_and_vars_alias/test.toml
test/src/e2e_vm_tests/test_programs/should_pass/language/match_expressions_unreachable_catch_all_last_arm/test.toml
test/src/e2e_vm_tests/test_programs/should_pass/language/match_expressions_unreachable_catch_all_middle_arm/test.toml
test/src/e2e_vm_tests/test_programs/should_pass/language/match_expressions_unreachable_last_arm/test.toml
test/src/e2e_vm_tests/test_programs/should_pass/language/match_expressions_unreachable_middle_arm/test.toml

This PR implements the decisions made in the [Expressive Diagnostics RFC](https://github.com/FuelLabs/sway-rfcs/blob/master/rfcs/0011-expressive-diagnostics.md) and adapts the existing diagnostics:
- _Issue_ is removed from the header and placed in code.
- _Help_ can also be in code.
- Wording is simplified.
Closes #5075.

Adjust existing Diagnostic API according to the Expressive Diagnostics RFC

---

docs/book/src/sway-program-types/libraries.md

Replaced broken links and docs of outdated NFT library with Ownership library.

Fix Check Links tests

---

Cargo.lock
forc-pkg/Cargo.toml
forc-pkg/src/pkg.rs
forc-pkg/src/source/git/mod.rs
forc-pkg/src/source/ipfs.rs
forc-plugins/forc-fmt/src/main.rs
forc-util/Cargo.toml
forc-util/src/lib.rs
sway-lsp/Cargo.toml
sway-lsp/benches/lsp_benchmarks/requests.rs
sway-lsp/src/core/document.rs
sway-lsp/src/core/session.rs
sway-lsp/src/error.rs
sway-lsp/src/handlers/notification.rs
sway-lsp/src/handlers/request.rs
sway-lsp/src/server.rs
sway-lsp/tests/integration/lsp.rs

This PR adds 3 things:
1. Adds a benchmark for the format LSP request.
2. Calls `session.wait_for_parsing();` before computing the `code_lens` request. This fixes the original issue reported in #4893 where run buttons where being placed incorrectly after formatting. 
3. If a file open in a code editor contains unsaved changes we write a lock file to `.forc/lsp_locks/`. This file is removed when the file is saved and there are no pending changes. If `forc-fmt` is run in a terminal we check if the path has a lock file associated with it. If unsaved changes are detected we bail from formatting with an error message instructing the user to save changes before continuing. See video below.
https://github.com/FuelLabs/sway/assets/1289413/75e6fddc-adbc-4796-aeb9-985574ae8dcc
closes #4893

Synchronize code_lens request & provide better UX for `forc-fmt` <> `sway-lsp` interaction.

---

Cargo.lock
sway-error/src/lex_error.rs
sway-parse/Cargo.toml
sway-parse/src/token.rs

Forbid directional formatting characters from
[UAX #9](https://www.unicode.org/reports/tr9/#Directional_Formatting_Characters) in literals to fix #5047.
This is similar to rustc's `text_direction_codepoint_in_literal` lint. Such characters are already implicitly forbidden in other parts of the syntax.

Forbid bidirectional flow control characters in literals

---

sway-lib-std/src/inputs.sw
sway-lib-std/src/storage/storage_api.sw
test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/call_basic_storage/src/main.sw
test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/call_increment_contract/src/main.sw
test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/storage_access_caller/src/main.sw

There is a TODO in the storage API to use the appropriate conversions between b256 <-> u256 when available. This PR resolves this TODO and removes an unused import.

Implement TODO in Storage API 

---

sway-lib-std/src/identity.sw
sway-lib-std/src/outputs.sw
sway-lib-std/src/storage/storage_string.sw
sway-lib-std/src/vec.sw

Replaces instances of the syntax `Option::Some` and `Option::None` with `Some` and `None` respectively. This follows Rust syntax more closely and homogenizes the use of `Option`s throughout the std lib.

Code quality updates for `Option` usage throughout the std lib

---

docs/book/src/advanced/assembly.md
docs/book/src/testing/unit-testing.md
sway-core/src/asm_generation/evm/evm_asm_builder.rs
sway-core/src/language/ty/declaration/declaration.rs

chore/docs: improve wording and fix typos

---

sway-parse/src/lib.rs
sway-parse/src/parser.rs
sway-parse/src/token.rs

Fix parser panics in edge cases

---

swayfmt/src/constants.rs
swayfmt/src/utils/map/newline.rs
swayfmt/tests/mod.rs

This is part of #5052
There was a bug in the formatter whenever a comment as followed by a doc-comment, this was due the `insert_after_span` was not allowed to return a negative offset (due types constraints). But sometimes this function should let their callee know to remove some bytes.

Fix fmt whitespaces between comments and doc comments

---

swayfmt/src/comments.rs
swayfmt/src/formatter/mod.rs
swayfmt/src/items/item_abi/mod.rs
swayfmt/src/items/item_configurable/mod.rs
swayfmt/src/items/item_enum/mod.rs
swayfmt/src/items/item_fn/mod.rs
swayfmt/src/items/item_impl/mod.rs
swayfmt/src/items/item_storage/mod.rs
swayfmt/src/items/item_struct/mod.rs
swayfmt/src/items/item_trait/mod.rs
swayfmt/src/items/item_use/mod.rs
swayfmt/src/utils/language/attribute.rs
swayfmt/src/utils/language/expr/asm_block.rs
swayfmt/src/utils/language/expr/code_block.rs
swayfmt/src/utils/language/expr/collections.rs
swayfmt/src/utils/language/expr/conditional.rs
swayfmt/src/utils/language/expr/mod.rs
swayfmt/src/utils/language/expr/struct_field.rs
swayfmt/src/utils/language/pattern.rs
swayfmt/src/utils/language/punctuated.rs
swayfmt/src/utils/language/where_clause.rs

Closes #5179 
What this does:
- Centralizes the use case of `ItemTraitItem`'s format method
- Fixes indentation problems around `Annotated<T>`
- Adds a `write_ident_into_buffer` method which checks if the buffer is already indented
- Adds documentation for methods the interact with the indentation of the formatter to avoid confusion on what they actually do

bug: Fix formatting for `ItemTraitItem` and `Annotated<T>`

---

templates/sway-test-rs/template/Cargo.toml
templates/sway-test-rs/template/tests/harness.rs

- Bump harness template to v0.48.0 for [intro-to-sway guide](https://github.com/FuelLabs/docs-hub/pull/55)
- Used auto loading [storage slots ](https://github.com/FuelLabs/fuels-rs/pull/1120)

feat: Bumping template to use fuels v0.48.0

---

swayfmt/src/comments.rs
swayfmt/src/items/item_fn/mod.rs
swayfmt/src/items/item_impl/mod.rs
swayfmt/tests/mod.rs

Fixes #5060 
Empty implementations have a bug with new lines

Fix new lines into empty implementation

---

sway-lib-std/src/math.sw
sway-lib-std/src/u128.sw
test/src/e2e_vm_tests/test_programs/should_pass/stdlib/exponentiation_test/src/main.sw
test/src/sdk-harness/test_artifacts/pow/src/main.sw
test/src/sdk-harness/test_projects/exponentiation/mod.rs

The exponent type should not mirror the type of the value being exponentiated and should be an unsigned integer. This follows the Rust convention of using `u32`.

Use `u32` as exponent in `Power` instead of `Self`

---

Cargo.lock
forc-pkg/src/manifest.rs
forc-plugins/forc-fmt/src/main.rs
forc-util/Cargo.toml
forc-util/src/lib.rs
forc/src/ops/forc_clean.rs
sway-utils/Cargo.toml
sway-utils/src/helpers.rs
swayfmt/Cargo.toml
swayfmt/src/config/manifest.rs

This PR just moves the dir helpers that were in `forc-util` to `sway-utils`. I need access to these methods in an upcoming PR and having them in `forc-util` introduces a mind field of circular dependencies.

refactor: Move dir helpers from `forc-util` to `sway-utils`

---

sway-lib-std/src/contract_id.sw

The following changes remove the use of the `std::hash::sha256` function in place of assembly to hash the `ContractId` and `SubId` of an asset. As the values hashed are of static length, we can perform the hashing in assembly avoiding the conversion to `Bytes` and concatenation of the two values done in `sha256()`
These changes result in a **93%** reduction in gas usage.

Optimize gas for `AssetId::new()` and `AssetId::default()` functions

---

sway-lib-std/src/ecr.sw

Only success test cases exist for the newly added `ed19` and `ecr1` opcodes exist. Revert cases have been added to the inline tests.
Closes #5220

Add revert cases for new ecr functionality

---

sway-core/src/asm_lang/allocated_ops.rs
sway-core/src/asm_lang/virtual_ops.rs
sway-core/src/semantic_analysis/ast_node/expression/typed_expression.rs
sway-core/src/transform/to_parsed_lang/convert_parse_tree.rs
sway-error/src/error.rs
sway-error/src/warning.rs
sway-ir/src/printer.rs
test/src/e2e_vm_tests/test_programs/should_fail/asm_read_from_uninitialized_reg/Forc.lock
test/src/e2e_vm_tests/test_programs/should_fail/asm_read_from_uninitialized_reg/Forc.toml
test/src/e2e_vm_tests/test_programs/should_fail/asm_read_from_uninitialized_reg/src/main.sw
test/src/e2e_vm_tests/test_programs/should_fail/asm_read_from_uninitialized_reg/test.toml
test/src/e2e_vm_tests/test_programs/should_fail/storage_conflict/src/main.sw
test/src/e2e_vm_tests/test_programs/should_fail/storage_conflict/test.toml

This PR closes https://github.com/FuelLabs/sway/issues/4997. The problem here is that "asm blocks registers" without initializers are considered uninitialized. There is no fallback to "capture" an available variable. This could be easily done, but that would leave us with no obvious syntax for unitialized registers.
With this in mind this PR solves the compiler bug with two diagnostics:
1 - uninitialized registers cannot be read before they are written. This generates an error:
```
5 |     let _ = asm(r1) {
|                 ^^ Unitialized register is being read before being written
6 |         r1: u64
7 |     };
```
2 - a warning when a unitialized register shadows an available variable with the same name. This is almost for sure a problem, and it is better the name the registe with …

Error for uninitialized register on asm blocks

---

forc-plugins/forc-fmt/src/main.rs
sway-lib-std/src/hash.sw

Fixes #5059 
While doing this I also updated `forc-fmt` to have a better error message being printed to the stdout
Before:
```bash
error: Formatting skipped due to error.
error: Failed to compile /Users/cr-fuel/projects/fuel/sway/sway-lib-std/src/hash.sw
```
Now:
```bash
error: Formatting skipped due to error.
error: Failed to compile /Users/cr-fuel/projects/fuel/sway/sway-lib-std/src/hash.sw
Cannot format raw hashbang attribute,
If this is intended to be a doc comment try using the `//!` syntax instead
```

Fix hash.sw, replaced `#![foo]` for `#[foo]`

---

forc-pkg/src/manifest.rs

This PR is needed to make https://github.com/FuelLabs/fuels-rs/pull/1163 green. We can configure the sway branch for the CI, but not the stdlib. With this, we will be able to edit github CI config and point to whichever sway version we want.

allow implicit stdlib to be configured with env vars

---

examples/cei_analysis/src/main.sw
examples/storage_vec/src/main.sw
examples/vec/src/main.sw
swayfmt/src/utils/language/expr/mod.rs
swayfmt/src/utils/language/statement.rs
swayfmt/tests/mod.rs

Improve breaking method calls into multiple lines following Rust rules.
A two parts method call is never broken into multiple lines, longer chains are broken if they are long enough (counting their arguments).

Improve inline arguments formatting

---

sway-core/src/semantic_analysis/ast_node/expression/typed_expression/enum_instantiation.rs
test/src/e2e_vm_tests/test_programs/should_pass/language/integer_type_inference/src/main.sw

This PR fixes a internal compiler error when `Enum` instantiation infer literals as `Numeric` needlessly. This creates a problem because `u8` are not `u64` in the IR and `Numeric` automatically decays into `u64` ( see `decay_numeric`).
Example:
```
let a: Option<u8> = Option::Some(1); // Error
let b: Option<u8> = Option::Some(1u8); // OK
```

Use type context when type_check enum instantiation

---

sway-core/src/asm_generation/fuel/data_section.rs
sway-lsp/tests/fixtures/auto_import/Forc.toml
sway-lsp/tests/fixtures/benchmark/Forc.toml
sway-lsp/tests/fixtures/completion/Forc.toml
sway-lsp/tests/fixtures/diagnostics/dead_code/Forc.toml
sway-lsp/tests/fixtures/diagnostics/multi_file/Forc.toml
sway-lsp/tests/fixtures/renaming/Forc.toml
sway-lsp/tests/fixtures/runnables/Forc.toml
sway-lsp/tests/fixtures/tokens/abi/Forc.toml
sway-lsp/tests/fixtures/tokens/consts/Forc.toml
sway-lsp/tests/fixtures/tokens/enums/Forc.toml
sway-lsp/tests/fixtures/tokens/fields/Forc.toml
sway-lsp/tests/fixtures/tokens/functions/Forc.toml
sway-lsp/tests/fixtures/tokens/impls/Forc.toml
sway-lsp/tests/fixtures/tokens/matches/Forc.toml
sway-lsp/tests/fixtures/tokens/modules/Forc.toml
sway-lsp/tests/fixtures/tokens/paths/Forc.toml
sway-lsp/tests/fixtures/tokens/storage/Forc.toml
sway-lsp/tests/fixtures/tokens/structs/Forc.toml
sway-lsp/tests/fixtures/tokens/traits/Forc.toml
sway-lsp/tests/fixtures/tokens/turbofish/Forc.toml
sway-lsp/tests/fixtures/tokens/variables/Forc.toml
sway-lsp/tests/fixtures/tokens/where_clause/Forc.toml
test/src/e2e_vm_tests/test_programs/should_pass/language/configurable_consts/json_abi_oracle.json
test/src/e2e_vm_tests/test_programs/should_pass/language/configurable_consts/src/main.sw

This PR solves a problem that Data Section alignment was being calculated even for "internal" entries, like entries inside collections. This creates problems with things like 
```sway
const a: [u8; 4] = [1, 2, 3, 4];
```
See https://github.com/FuelLabs/fuels-ts/blob/309608dc9902a225f685327fc4107deee0349039/apps/docs-snippets/projects/echo-configurables/src/main.sw as an example.
Now the alignment is correctly calculated only for "root" entries , allowing "internal" entries to be as packed as they desire.

fix fuel data section alignment

---

forc-plugins/forc-client/src/cmd/deploy.rs
forc-plugins/forc-client/src/op/deploy.rs

Closes https://github.com/FuelLabs/sway/issues/2010
Notes: 
- I couldn't use `from_reader` to deserialize the file contents due to this issue: https://github.com/FuelLabs/fuel-vm/pull/643

Allow user to override initial storage slots in forc-deploy

---

sway-lib-std/src/auth.sw
sway-lib-std/src/inputs.sw
test/src/e2e_vm_tests/test_programs/should_fail/predicate_log/src/main.sw
test/src/sdk-harness/test_artifacts/tx_contract/src/main.sw
test/src/sdk-harness/test_projects/tx_fields/mod.rs

close #5029
Changes the misleading name `input_owner` to `input_coin_owner`
Requesting a review and addition of the `Breaking` tag from @Braqzen

Rename input_owner to input_coin_owner

---

sway-lib-std/src/hash.sw

Adds a trait implementation of the Hash type for the u256 primitive

Add u256 Hash trait impl

---

Cargo.lock
docs/reference/src/documentation/introduction/installation/cargo.md
docs/reference/src/documentation/introduction/installation/index.md
docs/reference/src/documentation/introduction/installation/source.md
docs/reference/src/index.md
forc-pkg/Cargo.toml
forc-plugins/forc-client/Cargo.toml
forc-plugins/forc-crypto/Cargo.toml
forc-plugins/forc-doc/Cargo.toml
forc-plugins/forc-fmt/Cargo.toml
forc-plugins/forc-lsp/Cargo.toml
forc-plugins/forc-tx/Cargo.toml
forc-test/Cargo.toml
forc-tracing/Cargo.toml
forc-util/Cargo.toml
forc/Cargo.toml
sway-ast/Cargo.toml
sway-core/Cargo.toml
sway-error/Cargo.toml
sway-ir/Cargo.toml
sway-ir/sway-ir-macros/Cargo.toml
sway-lsp/Cargo.toml
sway-parse/Cargo.toml
sway-types/Cargo.toml
sway-utils/Cargo.toml
swayfmt/Cargo.toml
test/src/e2e_vm_tests/test_programs/should_fail/trait_cannot_find_in_scope_issue/Forc.lock
test/src/e2e_vm_tests/test_programs/should_fail/trait_cannot_find_in_scope_issue/Forc.toml

waiting on 
* #5274 
* #5273
* #5281

Bump to v0.48.0

---

Cargo.lock
forc-plugins/forc-lsp/Cargo.toml
forc-plugins/forc-lsp/src/main.rs
sway-lsp/Cargo.toml
sway-lsp/benches/bench_main.rs
sway-lsp/benches/lsp_benchmarks/compile.rs
sway-lsp/benches/lsp_benchmarks/mod.rs

closes #5372
Thanks for the idea @Voxelot , we seem to be getting nice performance wins across all our benchmarks with this change!
| Benchmark                | Avg Duration Before (ms or s) | Avg Duration After (ms or s) | Speed Increase (%) |
|--------------------------|-------------------------------|------------------------------|--------------------|
| compile                  | 5.53213 s                     | 4.64997 s                    | 15.931             |
| traverse                 | 170.646 ms                    | 162.067 ms                   | 5.0397             |
| did_change_with_caching  | 15.332 s                      | 15.4923 s                    | -1.04545           |
| semantic_tokens          | 20.766 ms                     | 15.981 ms                    | 23.053 …

Use Jemalloc in `forc-lsp` and LSP benchmarks for greater performance.

---

sway-core/src/semantic_analysis/module.rs
sway-core/src/semantic_analysis/program.rs
sway-error/src/error.rs
test/src/e2e_vm_tests/test_programs/should_fail/module_cyclic_reference/Forc.lock
test/src/e2e_vm_tests/test_programs/should_fail/module_cyclic_reference/Forc.toml
test/src/e2e_vm_tests/test_programs/should_fail/module_cyclic_reference/src/a.sw
test/src/e2e_vm_tests/test_programs/should_fail/module_cyclic_reference/src/b.sw
test/src/e2e_vm_tests/test_programs/should_fail/module_cyclic_reference/src/lib.sw
test/src/e2e_vm_tests/test_programs/should_fail/module_cyclic_reference/test.toml
test/src/e2e_vm_tests/test_programs/should_pass/language/module_dep/Forc.lock
test/src/e2e_vm_tests/test_programs/should_pass/language/module_dep/Forc.toml
test/src/e2e_vm_tests/test_programs/should_pass/language/module_dep/src/a.sw
test/src/e2e_vm_tests/test_programs/should_pass/language/module_dep/src/b.sw
test/src/e2e_vm_tests/test_programs/should_pass/language/module_dep/src/lib.sw
test/src/e2e_vm_tests/test_programs/should_pass/language/module_dep/test.toml
test/src/e2e_vm_tests/test_programs/should_pass/language/module_dep_multiple/Forc.lock
test/src/e2e_vm_tests/test_programs/should_pass/language/module_dep_multiple/Forc.toml
test/src/e2e_vm_tests/test_programs/should_pass/language/module_dep_multiple/src/a.sw
test/src/e2e_vm_tests/test_programs/should_pass/language/module_dep_multiple/src/b.sw
test/src/e2e_vm_tests/test_programs/should_pass/language/module_dep_multiple/src/c.sw
test/src/e2e_vm_tests/test_programs/should_pass/language/module_dep_multiple/src/lib.sw
test/src/e2e_vm_tests/test_programs/should_pass/language/module_dep_multiple/test.toml
test/src/e2e_vm_tests/test_programs/should_pass/language/module_dep_self/Forc.lock
test/src/e2e_vm_tests/test_programs/should_pass/language/module_dep_self/Forc.toml
test/src/e2e_vm_tests/test_programs/should_pass/language/module_dep_self/src/a.sw
test/src/e2e_vm_tests/test_programs/should_pass/language/module_dep_self/src/lib.sw
test/src/e2e_vm_tests/test_programs/should_pass/language/module_dep_self/test.toml

This PR implements a new module evaluation system to allow order-independent mod statements when importing modules.
It supports these sort of mod patterns to compile:
`a.sw`:
```rust
library;
use ::b::*;
pub fn a() { b::b(); }
```
`b.sw`:
```rust
library;
pub fn b() {}
```
`lib.sw`:
```rust
library;
mod a;
mod b;
fn main() -> u32 {
b::b();
0
}
```
To make this work, we now analyze the submodule structure first, creating a dependency graph that we later use to inform the module evaluation order.
We also now check for cyclic dependencies using the same graph, and report them when they are found.
Closes https://github.com/FuelLabs/sway/issues/409.

Implement order-independent module evaluation

---

sway-lsp/Cargo.toml
sway-lsp/benches/lsp_benchmarks/compile.rs
sway-lsp/benches/lsp_benchmarks/mod.rs
sway-lsp/benches/lsp_benchmarks/requests.rs
sway-lsp/benches/lsp_benchmarks/token_map.rs
sway-lsp/src/capabilities/on_enter.rs
sway-lsp/src/core/document.rs
sway-lsp/src/core/session.rs
sway-lsp/src/core/sync.rs
sway-lsp/src/handlers/notification.rs
sway-lsp/src/handlers/request.rs
sway-lsp/src/server.rs
sway-lsp/src/server_state.rs
sway-lsp/src/utils/keyword_docs.rs
sway-lsp/tests/integration/code_actions.rs
sway-lsp/tests/integration/lsp.rs
sway-lsp/tests/lib.rs

Aligned the language server's I/O operations with the `tower-lsp` async framework by adopting Tokio's asynchronous I/O primitives instead of ones from `std::fs`.

Refactor Language Server I/O to Use Tokio Async Primitives

---

.gitignore

Prevent people from accidentally checking in the Forc.lock files in sway LSP tests.
Follow up to https://github.com/FuelLabs/sway/pull/5294

Ignore Forc.lock in LSP tests

---

sway-lib-std/src/vm/evm/evm_address.sw

Closes #5291 
Adds the `Hash` trait for `EvmAddress`.

Implements the `Hash` trait for `EvmAddress`

---

docs/book/src/introduction/standard_library.md
docs/reference/src/SUMMARY.md
docs/reference/src/code/operations/assertions/src/lib.sw
docs/reference/src/documentation/misc/prelude.md
docs/reference/src/documentation/operations/assertions/assert-ne.md
docs/reference/src/documentation/operations/assertions/index.md
sway-lib-std/src/assert.sw
sway-lib-std/src/error_signals.sw
sway-lib-std/src/prelude.sw
test/src/e2e_vm_tests/test_programs/should_pass/stdlib/assert_ne/.gitignore
test/src/e2e_vm_tests/test_programs/should_pass/stdlib/assert_ne/Forc.lock
test/src/e2e_vm_tests/test_programs/should_pass/stdlib/assert_ne/Forc.toml
test/src/e2e_vm_tests/test_programs/should_pass/stdlib/assert_ne/json_abi_oracle.json
test/src/e2e_vm_tests/test_programs/should_pass/stdlib/assert_ne/src/main.sw
test/src/e2e_vm_tests/test_programs/should_pass/stdlib/assert_ne/test.toml
test/src/e2e_vm_tests/test_programs/should_pass/stdlib/assert_ne_revert/.gitignore
test/src/e2e_vm_tests/test_programs/should_pass/stdlib/assert_ne_revert/Forc.lock
test/src/e2e_vm_tests/test_programs/should_pass/stdlib/assert_ne_revert/Forc.toml
test/src/e2e_vm_tests/test_programs/should_pass/stdlib/assert_ne_revert/json_abi_oracle.json
test/src/e2e_vm_tests/test_programs/should_pass/stdlib/assert_ne_revert/src/main.sw
test/src/e2e_vm_tests/test_programs/should_pass/stdlib/assert_ne_revert/test.toml

Closes #5321
Added an assertion that mirrors the existing `assert_eq(x, y)` function. The `assert_ne(x, y)` function asserts that the two passed values are not equal. This removes the need for the workaround `assert(x != y)`. 
Documentation was updated in all areas that `assert_eq()` is referenced. Tests were created similarly to the `assert_eq()` tests. The function was also added to [`prelude.sw`](https://github.com/brandonsurh/sway/blob/9ee4b7a85d54cf19aea29ad63fdfb992d17d95ce/sway-lib-std/src/prelude.sw#L20).

Added `assert_ne(x, y)` function

---

sway-core/src/decl_engine/engine.rs
sway-core/src/type_system/ast_elements/type_parameter.rs
sway-core/src/type_system/engine.rs
sway-core/src/type_system/info.rs
sway-core/src/type_system/unify/unifier.rs

The current GC implementation was not cleaning up `parents` in the decl engine and also was missing the `id_map` in the type engine. This also changes the `slab` in the type engine to hold a `TypeSourceInfo` instead of having seperate maps. 
The `type_info` in the `TypeSourceInfo` is now an `Arc`.

Revert TE `slab` to hold `TypeSourceInfo` and perform GC on DE `parents` and TE `id_map`

---

Cargo.lock
sway-types/Cargo.toml
sway-types/src/span.rs

This PR introduces a significant performance improvement to the `line_col` function by integrating the `bytecount` crate, leading to more efficient newline character counting in strings. Here are the results of the `sway-lsp` benchmarks. 🚀 
| Type                      | Previous Duration | Current Duration | Speedup        | Improvement % |
|---------------------------|-------------------|------------------|----------------|---------------|
| highlight                 | 108.30 ms         | 14.704 ms        | 7.36x          | +86.44%       |
| tokens_at_position        | 41.317 ms         | 6.9646 ms        | 5.93x          | +83.14%       |
| parent_decl_at_position   | 41.319 ms         | 6.9321 ms        | 5.96x          | +83.22%       |
| traverse                  | 165.60 ms …

Major Performance Boost in `line_col` Function with `bytecount` Integration

---

forc-plugins/forc-client/tests/Forc.lock
forc-plugins/forc-client/tests/Forc.toml

It seems like we accidentally depend on released version of std in forc-client deployment cli tests (more specifically the test folder https://github.com/FuelLabs/sway/tree/master/forc-plugins/forc-client/tests). This PR fixes it to point local version of std so that release PRs such as #5452 won't get blocked.

fix: point std to local version for forc-client cli tests

---

sway-core/src/ir_generation/function.rs
test/src/e2e_vm_tests/test_programs/should_pass/language/u256/u256_operators/src/main.sw

Convert numeric literals to U256 based on inferred expression type

---

sway-lsp/src/core/session.rs
sway-lsp/src/core/token_map.rs
sway-lsp/src/traverse/dependency.rs
sway-lsp/src/traverse/typed_tree.rs

Traversing the typed tokens from `sway-lib-std` now goes from `3.957833ms` → `1.372ms`. Collecting typed tokens on the benchmark project goes from `139.6ms` → `127.7ms`.
I noticed that there are transient contentions when reading items from the `TokenMap` with this change. As such, I've implemented a new function on the `TokenMap` called `try_get_mut_with_retry`. This method tries to access the value up to 8 times if the lock is still held using the backoff and retry pattern. 
related to #5445

LSP Optimization: Use rayon for `parse_ast_to_typed_tokens` function

---

sway-lsp/src/core/session.rs
sway-lsp/src/core/token_map.rs
sway-lsp/src/traverse/typed_tree.rs

Use `rayon` par_iters in the `traverse::typed_tree` module. We are already doing this in `traverse::parsed_tree`, this just brings this over to the typed_tree module as well.
Branched off #5473. <s>Will want to merge that first then will take this out of draft.</s>
Collecting typed tokens on the benchmark project goes from `120.508917ms` → `14.853125ms`
related to https://github.com/FuelLabs/sway/issues/5445

LSP Optimization: Add par_iters to the `traverse::typed_tree` module

---

.github/workflows/ci.yml

Due to an upstream issue, publish crates step is failing this is changing the step to our fork.

ci: switch katyo/publish-crates@v2 to xgreenx/publish-crates@v1

---

sway-core/src/ir_generation/const_eval.rs
sway-core/src/ir_generation/function.rs
sway-core/src/semantic_analysis/ast_node/declaration/storage.rs
test/src/e2e_vm_tests/test_programs/should_fail/configurables_are_not_const/Forc.lock
test/src/e2e_vm_tests/test_programs/should_fail/configurables_are_not_const/Forc.toml
test/src/e2e_vm_tests/test_programs/should_fail/configurables_are_not_const/src/main.sw
test/src/e2e_vm_tests/test_programs/should_fail/configurables_are_not_const/test.toml

Don't allow configurables to be used in const expressions except as
storage and configurable initializers.
Fix #5272
Fix #5261

Forbid configurables in constants

---

sway-lsp/tests/fixtures/auto_import/Forc.toml

There isn't a good reason to target the local std-lib for these tests, targeting the git tag helps reduce churn on people working on the std-lib.

Change auto_import test to use git tag of std lib

---

sway-lsp/benches/lsp_benchmarks/compile.rs
sway-lsp/benches/lsp_benchmarks/mod.rs
sway-lsp/src/core/session.rs
sway-lsp/src/server_state.rs

We no longer write TokenMap or Metrics into an intermediate copy and then back to the original in `write_parse_result`. Instead, we write to them directly during traversal if the compilation was successful. 
related to #5445 
| Metric   | Before    | After     | Change (%)       |
|----------|-----------|-----------|------------------|
| traverse & write | 122.018ms | 74.353ms  | -39.07%          |

LSP Optimization: Remove `ParseResult` and write to session types directly

---

sway-core/src/semantic_analysis/namespace/items.rs
sway-core/src/semantic_analysis/namespace/module.rs
sway-error/src/error.rs
test/src/e2e_vm_tests/test_programs/should_fail/deduplication_of_shadowing_errors/Forc.lock
test/src/e2e_vm_tests/test_programs/should_fail/deduplication_of_shadowing_errors/Forc.toml
test/src/e2e_vm_tests/test_programs/should_fail/deduplication_of_shadowing_errors/json_abi_oracle.json
test/src/e2e_vm_tests/test_programs/should_fail/deduplication_of_shadowing_errors/src/lib.sw
test/src/e2e_vm_tests/test_programs/should_fail/deduplication_of_shadowing_errors/src/main.sw
test/src/e2e_vm_tests/test_programs/should_fail/deduplication_of_shadowing_errors/test.toml

Fix missing shadowing errors due to error deduplication

---

sway-lsp/Cargo.toml

The extra config in Cargo.toml is because of this issue: bheisler/criterion.rs#275
Once merged, this PR should be working: https://github.com/FuelLabs/sway/pull/5546
This doesn't affect running benchmarks locally.

Support for criterion-compare-prs gh action

---

sway-core/src/query_engine/mod.rs

This was added as an optimization in #5472. However, it seems to be the cause of a transient bug that is causing the language server to crash outlined in #5531. 
We should revert this optimization until we understand how to avoid this crash from happening. cc @tritao

Remove Arcs from QE

---

test/src/e2e_vm_tests/test_programs/should_pass/language/where_clause_functions/src/main.sw

PR #3818 is no longer necessary and this PR proves that the test cases added on in already pass on master without any additional change.

Adds test case that covers PR #3818.

---

.github/workflows/ci.yml

closes #5542 
Switch to use buildjet cache for steps using buildjet runners.

ci: use buildjet cache for steps using buildjet runners

---

docs/book/src/SUMMARY.md
docs/book/src/lsp/index.md
docs/book/src/lsp/troubleshooting.md

Adds a doc page for troubleshooting LSP. If users report an issue with LSP, we can direct them here to save time.

Add page for LSP troubleshooting

---

sway-core/src/ir_generation/function.rs
sway-core/src/language/ty/expression/expression_variant.rs
sway-core/src/semantic_analysis/ast_node/expression/typed_expression.rs
sway-core/src/semantic_analysis/ast_node/expression/typed_expression/struct_field_access.rs
sway-core/src/semantic_analysis/ast_node/expression/typed_expression/tuple_index_access.rs
sway-core/src/semantic_analysis/namespace/items.rs
sway-core/src/type_system/engine.rs
sway-core/src/type_system/info.rs
sway-error/src/error.rs
test/src/e2e_vm_tests/test_programs/should_pass/language/references/dereferencing_operator_dot_on_tuples/Forc.lock
test/src/e2e_vm_tests/test_programs/should_pass/language/references/dereferencing_operator_dot_on_tuples/Forc.toml
test/src/e2e_vm_tests/test_programs/should_pass/language/references/dereferencing_operator_dot_on_tuples/json_abi_oracle.json
test/src/e2e_vm_tests/test_programs/should_pass/language/references/dereferencing_operator_dot_on_tuples/src/impls.sw
test/src/e2e_vm_tests/test_programs/should_pass/language/references/dereferencing_operator_dot_on_tuples/src/main.sw
test/src/e2e_vm_tests/test_programs/should_pass/language/references/dereferencing_operator_dot_on_tuples/test.toml
test/src/e2e_vm_tests/test_programs/should_pass/language/references/dereferencing_operator_star/src/main.sw
test/src/e2e_vm_tests/test_programs/should_pass/language/references/referencing_function_parameters/src/main.sw

This PR implements tuple element access operator `.` for [references](https://github.com/FuelLabs/sway-rfcs/blob/ironcev/amend-references/files/0010-references.sw). The overall effort related to references is tracked in #5063.
`.` is defined for references to tuples using this recursive definition: `<reference>.<element index> := (*<reference>).<element index>`.
This eliminates the need for the dereferencing operator `*` when working with references to tuples:
```Sway
let t = (1, 2, 3);
let r = &&&t;
assert((***r).0 == r.0);
```
```Sway
let r = &&& ( &&(1, 2), &(3, 4) );
assert(r.0.0 == 1);
assert(r.1.1 == 4);
```
Additionally, the PR:
- creates `Diagnostic` for the `TupleIndexOutOfBounds` error.
- harmonizes the appearance of the `TupleIndexOutOfBounds` error in the element access and …

Dereferencing operator `.` on tuple element access

---

.github/workflows/docs.yml

This makes it so the Docs CI checks only happen when a PR includes changes to files under `docs/`

Only run docs CI checks when docs have changed

---

Cargo.lock
forc-pkg/src/manifest.rs
forc-pkg/src/pkg.rs
forc-plugins/forc-doc/src/main.rs
forc/src/ops/forc_check.rs
sway-core/src/build_config.rs
sway-core/src/lib.rs
sway-lsp/Cargo.toml
sway-lsp/benches/lsp_benchmarks/compile.rs
sway-lsp/benches/lsp_benchmarks/mod.rs
sway-lsp/src/core/session.rs
sway-lsp/src/core/token_map.rs
sway-lsp/src/handlers/notification.rs
sway-lsp/src/server_state.rs
sway-lsp/tests/fixtures/benchmark/src/main.sw
sway-lsp/tests/lib.rs

This PR does 3 optimizations. The timings below are measured against the LSP benchmarking project.
1. Disable running DCA & control flow analysis, for did_change events `39.544ms`
2. Disable running collect_types_metadata for did_change events `3.522ms`
3. Only write the diagnostics res to self.diagnostics.write() on did_open & did_save `21.135ms`
I also had to increase the frequency that we are calling GC to every 3rd keystroke as during stress tests I was occasionally getting stack overflows otherwise.
related to #5445

Disable DCA and writing diagnostics on did_change events

---

.github/workflows/ci.yml

`build-mdbook` was failing on multiple PRs with 
```
Run cargo install --locked --debug --path ./forc
error: binary `forc` already exists in destination
Add --force to overwrite
```
https://github.com/FuelLabs/sway/actions/runs/7819113568/attempts/1?pr=5569
https://github.com/FuelLabs/sway/actions/runs/7816891674/job/21336246772?pr=5565
`cargo install` keeps track of which binaries it has installed in ~/.cargo/crates.toml and ~/.cargo.crates2.json. By using the entire cached `cargo` directory, cargo is able to tell that it has previously installed the binaries and install correctly.

Fix build-mdbook CI failure

---

sway-lib-std/src/math.sw

simple changes that uses newton's method for sqrt and decomposition to `u64` for `log2` - `log` builds up on `log2` for `u256`
This should fix #5329
Ping @SwayStar123

u256: log, log2 and sqrt impl (#5329)

---

forc-pkg/src/manifest.rs
forc-pkg/src/pkg.rs
forc-util/src/lib.rs
sway-core/src/build_config.rs

Solves [1] and [2] of https://github.com/FuelLabs/sway/issues/5607
fuel target
other targets

Format release targets output

---

forc-plugins/forc-debug/tests/server_integration.rs

This test is failing on PRs. Disabling for now while I investigate the root cause.

Temporarily disable `test_server_launch_mode`

---

sway-lib-core/src/storage.sw
sway-lib-std/src/storage/storage_bytes.sw
sway-lib-std/src/storage/storage_key.sw
sway-lib-std/src/storage/storage_map.sw
sway-lib-std/src/storage/storage_string.sw
sway-lib-std/src/storage/storage_vec.sw
test/src/e2e_vm_tests/test_programs/should_fail/generics_in_contract/src/main.sw
test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/call_basic_storage/src/main.sw
test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/call_storage_enum/src/main.sw

Updates the following heap types to have private struct variables:
- `StorageSlot`
As private fields can only be accessed from within the same file, the `new()`, `slot()`, `offset()`, and `field_id()` functions have been moved to core.
Note: This PR merges into a staging branch

Encapsulation of Storage Types

---

sway-lib-std/src/b512.sw
sway-lib-std/src/ecr.sw
sway-lib-std/src/u128.sw
sway-lib-std/src/u256.sw
sway-lib-std/src/vm/evm/ecr.sw
sway-lib-std/src/vm/evm/evm_address.sw
test/src/e2e_vm_tests/test_programs/should_pass/language/complex_cfg/src/main.sw
test/src/e2e_vm_tests/test_programs/should_pass/language/empty_method_initializer/src/main.sw
test/src/e2e_vm_tests/test_programs/should_pass/stdlib/assert_eq/json_abi_oracle.json
test/src/e2e_vm_tests/test_programs/should_pass/stdlib/assert_ne/json_abi_oracle.json
test/src/e2e_vm_tests/test_programs/should_pass/stdlib/b512_struct_alignment/src/main.sw
test/src/e2e_vm_tests/test_programs/should_pass/stdlib/b512_test/src/main.sw
test/src/e2e_vm_tests/test_programs/should_pass/stdlib/u128_div_test/src/main.sw
test/src/e2e_vm_tests/test_programs/should_pass/stdlib/u128_mul_test/src/main.sw
test/src/e2e_vm_tests/test_programs/should_pass/stdlib/u128_test/src/main.sw

Updates the following numeric types to have private struct variables:
- `B512`
- `U128`
As `U256` is deprecated this type has not been updated. 
This PR also renames the `B512` field from `bytes` to `bits` and renames the `EvmAddress` field from `bytes` to `bits` with a field accessor function.
Note: This PR merges into a staging branch

Encapsulation Numeric Types

---

sway-core/src/decl_engine/ref.rs
sway-core/src/decl_engine/replace_decls.rs
sway-core/src/language/ty/ast_node.rs
sway-core/src/language/ty/code_block.rs
sway-core/src/language/ty/declaration/constant.rs
sway-core/src/language/ty/declaration/function.rs
sway-core/src/language/ty/expression/expression.rs
sway-core/src/language/ty/expression/expression_variant.rs
sway-core/src/language/ty/expression/reassignment.rs
sway-core/src/language/ty/expression/struct_exp_field.rs

This PR solves a problem for https://github.com/FuelLabs/sway/pull/5427. When compiling the Rust SDK, the type below hangs the compiler inside`find_parent`. 
```sway
#[allow(dead_code)]
struct MegaExample<T, U> {
a: ([U; 2], T),
b: Vec<([EnumWGeneric<StructWTupleGeneric<StructWArrayGeneric<PassTheGenericOn<T>>>>; 1], u32)>,
}
```
Now, propagating when a change is made, not only the example compiles, but we should also be able to optimize compilation in general.
In small benchmarks I made here, compiling the Rust SDK had a 2% improvement (from `0m8.404s` to `0m8.258s`).

Make `replace_decl`s to know when a change was introduced

---

.github/workflows/ci.yml
sway-lsp/tests/lib.rs

This PR refines our testing approach for `sway-lsp` to ensure tests run sequentially, addressing potential async test interference. Key enhancements include:
- Implemented a `run_async` macro to facilitate running async tests within a synchronous environment, minimizing the boilerplate code and improving test readability.
- Updated the GitHub Actions workflow to include a dedicated job for `sway-lsp`, utilizing `-p sway-lsp -- --test-threads=1` to enforce sequential execution of tests. This removes LSP tests from the `cargo-test-workspace` job.

Enhance LSP Testing Strategy for Better Reliability

---

docs/book/src/blockchain-development/access_control.md
docs/book/src/sway-program-types/libraries.md
docs/reference/src/documentation/operations/reentrancy.md

Paths have changed in Sway-Standards and Sway-Libs resulting in dead links.
Required for any other PRs to have passing CI.

Fix dead links

---

sway-core/src/type_system/unify/unify_check.rs
test/src/e2e_vm_tests/test_programs/should_pass/language/method_unambiguous/Forc.lock
test/src/e2e_vm_tests/test_programs/should_pass/language/method_unambiguous/Forc.toml
test/src/e2e_vm_tests/test_programs/should_pass/language/method_unambiguous/src/main.sw
test/src/e2e_vm_tests/test_programs/should_pass/language/method_unambiguous/test.toml

`find_method_for_type` was throwing an error when multiple implementations of a method exist receiving different kinds of unsigned int. This was caused by the coercion comparison which returned true while comparing any uint size to any other uint size.
The solution was to change the UnifyCheck on Coercion to only return true to same size uints.
Fixes #5798

Fixes compiler asking for unnecessary disambiguation for trait methods.

---

docs/book/src/lsp/troubleshooting.md

Add a troubleshooting section for slow performance in the LSP server advising users on steps to mediate it.

docs: add troubleshooting for slow performance

---

forc-pkg/src/manifest/mod.rs

This PR adds a ad-hoc solution for #5811. Basically checks if the fetched package is 'std' and if so, only package from 'sway-lib-std' folder is accepted for that package.

fix: make sure to check std is taken from sway-lib-std folder

---

sway-lib-std/src/primitive_conversions/u32.sw

Adds implementation for From<u8> and From<u16> for u32
Partially addresses #5797

From<u8, u16> for u32

---

sway-lib-std/src/primitive_conversions/u64.sw

Adds implementations for From<u8>, From<u16>, From<u32> for u64
Partially addresses #5797

From<u8, u16, u32> for u64 implementations

---

sway-core/src/ir_generation/const_eval.rs
sway-core/src/language/parsed/declaration.rs
sway-core/src/language/parsed/declaration/abi.rs
sway-core/src/language/parsed/declaration/constant.rs
sway-core/src/language/parsed/declaration/enum.rs
sway-core/src/language/parsed/declaration/function.rs
sway-core/src/language/parsed/declaration/impl_trait.rs
sway-core/src/language/parsed/declaration/storage.rs
sway-core/src/language/parsed/declaration/struct.rs
sway-core/src/language/parsed/declaration/trait.rs
sway-core/src/language/parsed/declaration/type_alias.rs
sway-core/src/language/parsed/declaration/variable.rs
sway-core/src/semantic_analysis/ast_node/declaration/declaration.rs
sway-core/src/semantic_analysis/ast_node/declaration/impl_trait.rs
sway-core/src/semantic_analysis/ast_node/declaration/supertrait.rs
sway-core/src/semantic_analysis/ast_node/expression/match_expression/typed/typed_scrutinee.rs
sway-core/src/semantic_analysis/ast_node/expression/typed_expression.rs
sway-core/src/semantic_analysis/ast_node/expression/typed_expression/method_application.rs
sway-core/src/semantic_analysis/ast_node/expression/typed_expression/struct_instantiation.rs
sway-core/src/semantic_analysis/coins_analysis.rs
sway-core/src/semantic_analysis/namespace/lexical_scope.rs
sway-core/src/semantic_analysis/namespace/mod.rs
sway-core/src/semantic_analysis/namespace/module.rs
sway-core/src/semantic_analysis/namespace/namespace.rs
sway-core/src/semantic_analysis/namespace/trait_map.rs
sway-core/src/semantic_analysis/type_check_context.rs
sway-core/src/type_system/ast_elements/trait_constraint.rs
sway-core/src/type_system/ast_elements/type_parameter.rs
sway-lsp/src/capabilities/completion.rs

This PR unifies the codepaths in trait map and name resolution code so they can work for both parsed and typed declarations.
It does this by introducing wrapper types for the output of resolving of names.
This is an intermediate step to being able to use this code on the new symbol resolving pass.
While this adds a little bit of minor bloat to the code, I think it's an acceptable further step to be able to do re-use the code in steps before type-checking.

Refactor trait map and module symbol resolution code to allow usage for parsed declarations

---

sway-core/src/semantic_analysis/namespace/trait_map.rs
test/src/e2e_vm_tests/reduced_std_libs/sway-lib-std-vec/reduced_lib.config

Partially fixes https://github.com/FuelLabs/sway/issues/5781.
This reduces the problem of millions of `TypeInfo`s being created.
For more details see: https://github.com/FuelLabs/sway/pull/5782

Cache in front of check_if_trait_constraints_are_satisfied_for_type

---

sway-lib-std/src/constants.sw

The example wont compile as the function returns a assetid instead of b256, the proposed changes fixes it so the example should compile now.

Fix ZERO_B256 docs

---

docs/book/spell-check-custom-words.txt
docs/book/src/SUMMARY.md
docs/book/src/blockchain-development/native_assets.md
docs/book/src/examples/liquidity_pool.md
examples/native_asset/src/main.sw

- Additional docs covering Native Assets including:
- EVM vs FuelVM Assets
- What `AssetId` is
- How to use `AssetId`
- What `SubId` is
- What the default asset is
- How to mint coins
- How to burn coins
- How to transfer coins
- How to check contract balances
- How to check transaction values
- How to receive assets in contracts
- ERC-20 equivalent example
- ERC-1155 equivalent example
- The Liquidity Pool example has been moved to its own section in examples
These changes were originally included in https://github.com/FuelLabs/sway/pull/5806 but have been pulled out into a separate PR

Expand Native Asset Docs

---

sway-core/src/concurrent_slab.rs

Partially addresses https://github.com/FuelLabs/sway/issues/5781.
This reduces the time spent retrieving items in slabs.
For more details see: https://github.com/FuelLabs/sway/pull/5782

change ConcurrentSlab to use Vec

---

sway-core/src/decl_engine/mapping.rs
sway-core/src/decl_engine/ref.rs
sway-core/src/language/ty/expression/expression_variant.rs
test/src/e2e_vm_tests/test_programs/should_pass/language/mega_example/Forc.lock
test/src/e2e_vm_tests/test_programs/should_pass/language/mega_example/Forc.toml
test/src/e2e_vm_tests/test_programs/should_pass/language/mega_example/src/main.sw
test/src/e2e_vm_tests/test_programs/should_pass/language/mega_example/test.toml

ReplaceDecls for method application was calling replace_decls twice for FunctionDecl. This was visiting function declarations as a binary tree, doing replace decls twice per FunctionDecl.
With these changes, we merge both decl mappings before calling replace_decls once instead of twice.
The performance dropped from over 2min(did not wait for test to finish) to 7 seconds in the mega example. With --experimental-new-encoding and --release.

Fixes compiler performance in mega_example.

---

sway-core/src/semantic_analysis/ast_node/expression/typed_expression/method_application.rs
test/src/e2e_vm_tests/test_programs/should_pass/language/fqp_in_lib/Forc.lock
test/src/e2e_vm_tests/test_programs/should_pass/language/fqp_in_lib/Forc.toml
test/src/e2e_vm_tests/test_programs/should_pass/language/fqp_in_lib/src/lib.sw
test/src/e2e_vm_tests/test_programs/should_pass/language/fqp_in_lib/src/main.sw
test/src/e2e_vm_tests/test_programs/should_pass/language/fqp_in_lib/test.toml

When a fully qualified path was used inside a library using a type within the same file the symbol would not be found.
Fixes #5826

Fixes FQP root type not found when inside a library.

---

.github/workflows/ci.yml
Cargo.lock
Cargo.toml
forc-plugins/forc-client/src/op/deploy.rs
forc-plugins/forc-client/src/op/run/encode.rs
forc-plugins/forc-client/src/op/run/mod.rs
forc-plugins/forc-client/src/op/submit.rs
forc-plugins/forc-client/src/util/gas.rs
forc-plugins/forc-debug/docs/walkthrough.md
forc-plugins/forc-debug/examples/example_tx.json
forc-plugins/forc-debug/src/server/handlers/handle_launch.rs
forc-plugins/forc-tx/src/lib.rs
forc-test/src/execute.rs
forc-test/src/lib.rs
test/src/e2e_vm_tests/harness.rs
test/src/e2e_vm_tests/test_programs/should_pass/language/raw_ptr/raw_ptr_ret/test.toml

Update rust sdk to v0.56, fuel-core to v0.23.0 and fuel-vm to v0.47.1

chore:bump sdk to v0.56, fuel-core to 0.23.0, fuel-vm to 0.47.1

---

sway-lib-std/src/vec.sw

This PR uses the fact that we know the final length of the `Vec`, and creates it with the correct length, avoiding future allocations.

AbiDecode for  Vec using `with_capacity`

---

forc-pkg/src/manifest/mod.rs
sway-lsp/src/core/session.rs
sway-lsp/src/error.rs
sway-lsp/src/handlers/request.rs
sway-lsp/src/server_state.rs
sway-lsp/tests/lib.rs
sway-types/src/source_engine.rs

Fixes a critical bug where the server would crash if compilation was triggered from anything other than the root `main.sw` file. This was due to the metrics_map using the `SourceId` rather then the `ModuleId` as the key. 
This was introduced last week in #5813 as we now need to metrics to decide if the engines should be mem swapped or discarded. 
closes #5870

Use `ModuleId` instead of `SourceId` as the metrics map key

---

Cargo.lock
docs/reference/src/documentation/introduction/installation/cargo.md
docs/reference/src/documentation/introduction/installation/index.md
docs/reference/src/documentation/introduction/installation/source.md
docs/reference/src/index.md
forc-pkg/Cargo.toml
forc-plugins/forc-client/Cargo.toml
forc-plugins/forc-crypto/Cargo.toml
forc-plugins/forc-debug/Cargo.toml
forc-plugins/forc-doc/Cargo.toml
forc-plugins/forc-fmt/Cargo.toml
forc-plugins/forc-lsp/Cargo.toml
forc-plugins/forc-tx/Cargo.toml
forc-test/Cargo.toml
forc-tracing/Cargo.toml
forc-util/Cargo.toml
forc/Cargo.toml
sway-ast/Cargo.toml
sway-core/Cargo.toml
sway-error/Cargo.toml
sway-ir/Cargo.toml
sway-ir/sway-ir-macros/Cargo.toml
sway-lsp/Cargo.toml
sway-lsp/tests/fixtures/tokens/storage/Forc.toml
sway-parse/Cargo.toml
sway-types/Cargo.toml
sway-utils/Cargo.toml
swayfmt/Cargo.toml
templates/sway-test-rs/template/Cargo.toml

chore: bump to v0.55.0

---

examples/liquidity_pool/src/main.sw
sway-lib-std/src/asset.sw
sway-lib-std/src/call_frames.sw
sway-lib-std/src/context.sw
sway-lib-std/src/identity.sw
test/src/e2e_vm_tests/test_programs/should_pass/static_analysis/cei_pattern_violation_more_complex_logic/src/main.sw
test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/context_testing_contract/src/main.sw
test/src/sdk-harness/test_artifacts/call_frames_test_abi/src/main.sw
test/src/sdk-harness/test_artifacts/context_caller_contract/src/main.sw
test/src/sdk-harness/test_projects/call_frames/mod.rs
test/src/sdk-harness/test_projects/call_frames/src/main.sw

We currently support 2 methods of getting the contract id of a contract in an internal context:
- `contract_id()`
- `ContractId::this()`
The `this()` associated function is a constructor that returns `Self` and should be the primary method of getting the contract id. This idiomatically follows Rust's syntax and `contract_id()` has been removed.
The same syntax is followed with `AssetId::base()`.
Closes #5834

Remove `contract_id()` in favor of `ContractId::this()`

---

sway-core/src/semantic_analysis/ast_node/expression/typed_expression/method_application.rs
sway-core/src/semantic_analysis/namespace/trait_map.rs
sway-core/src/type_system/id.rs
sway-error/src/error.rs
sway-error/src/handler.rs
test/src/e2e_vm_tests/test_programs/should_fail/struct_field_privacy_storage/Forc.toml
test/src/e2e_vm_tests/test_programs/should_fail/trait_method_and_generic_trait_impl/src/main.sw
test/src/e2e_vm_tests/test_programs/should_fail/trait_method_and_generic_trait_impl/test.toml
test/src/e2e_vm_tests/test_programs/should_pass/language/method_indirect_inference/Forc.lock
test/src/e2e_vm_tests/test_programs/should_pass/language/method_indirect_inference/Forc.toml
test/src/e2e_vm_tests/test_programs/should_pass/language/method_indirect_inference/src/main.sw
test/src/e2e_vm_tests/test_programs/should_pass/language/method_indirect_inference/test.toml

We now do the return type unification before doing the second pass of arguments type checking in method application type checking.
Doing the unification sooner fixes the problem we were having while doing:
```
let mut bytes = Bytes::new();
bytes.push(1_u64.try_into().unwrap());
```
With the unification sooner we will unify the return of unwarp with the type annotation of the push argument before we do the type checking of `1_u64.try_into()`. By the time we do `1_u64.try_into()` we will already have the type parameter `U` unified with u8.
Fixes #5802.

Fixes type inference on inlined method applications.

---

sway-core/src/language/call_path.rs
sway-core/src/semantic_analysis/namespace/lexical_scope.rs
sway-core/src/semantic_analysis/namespace/module.rs
sway-core/src/semantic_analysis/namespace/root.rs

Fixes #5911 .
So far all imported items in a module have been collected in single map, with a flag in each value indicating whether it was the result of a glob/star import or an item import (this distinction matters because item imports shadow glob imports).
This PR splits the map in two: One for glob imports and one for item imports. This simplifies name resolution, and eliminates the `GlobImport` flag.
When another module imports all reexported items the logic is now slightly more complex, but this will be resolved once the excessive cloning of namespaces, modules and typed declarations are eliminated.

Refactor: Split use synonyms into separate maps for glob and item imports

---

sway-lib-std/src/lib.sw
test/src/sdk-harness/Forc.lock
test/src/sdk-harness/Forc.toml
test/src/sdk-harness/test_projects/run_external_proxy/mod.rs

This PR removes `run_external` temporarily until it is stabilized.

Disabling run_external

---

.github/workflows/ci.yml
.github/workflows/scripts/check-sdk-harness-version.sh
Cargo.toml

We are currently out of sync in between sdk-harness and test suite, this is not ideal due to couple of reasons:
1. It is not nice to have our two test suites, testing with different versions of fuel-core, which means we do not test one version completely in the sense of our e2e and sdk-harness tests.
2. It can create problems in CI if a contract id needs to be updated, when the out-of sync versions are incompatible. (for example: one is using version 0.1.0, one is using 0.2.0)
The added job will fail and inform the dev bumping fuel-core version, to also bump it in sdk-harness or in general make them in sync.
The reason we need this as a CI job is we cannot enforce it via cargo. Since adding sdk-harness to the sway repo workspace, it creates our well known cyclic dependency between sdk and …

ci: add a job for checking fuel-core versions between sdk-harness and test suite

---

Cargo.lock
Cargo.toml
forc-plugins/forc-client/src/op/run/encode.rs

closes #5932.
This PR bumps rust sdk used in sway repo to v0.58.0 which is the actual version that should be used with fuel-core v0.24.3

chore: use rust-sdk v0.58.0

---

ci_checks.sh

Updates `ci_checks.sh` file that aims to locally loosely "simulate" CI, to better represent the current state of the CI by:
1. Adds `sdk-harness` version check step to the script
2. Updates instructions on how to install & run fuel-core for test suite.

chore: update ci_checks script to represent current ci better

---

test/src/e2e_vm_tests/mod.rs

If the `test.toml` file in a test does not contain the entries `expected_result` and `expected_result_new_encoding`, the end-to-end tests fail with an unhelpful error message.
This PR improves the error message.

Fail nicer on missing expected_result in test.toml files

---

sway-core/src/lib.rs

The auditors were wondering why we had multiple code paths, and turns out its just dead code, so remove it.

Clean up dead code.

---

sway-lib-std/src/primitive_conversions/u16.sw
sway-lib-std/src/primitive_conversions/u32.sw
sway-lib-std/src/primitive_conversions/u64.sw
sway-lib-std/src/primitive_conversions/u8.sw

```
warning
--> sway-lib-std/src/primitive_conversions/u64.sw:189:4
|
187 |
188 | #[test]
189 | fn test_u64_try_from_U128() {
|    ---------------------- Function name "test_u64_try_from_U128"
is not idiomatic. Function names should be snake_case, like
"test_u64_try_from_u128".
190 |     use ::assert::assert;
|
```

Fix non idiomatic function names warnings in the std lib.

---

sway-core/src/semantic_analysis/namespace/trait_map.rs
sway-types/src/ident.rs

I generated a flame graph and saw that we are spending a ton of time cloning `BaseIdent` and `TraitName`. I've wrapped the `name_override_opt` in BaseIdent with an `Arc` and also changed TraitName to: 
```rust
type TraitName = Arc<CallPath<TraitSuffix>>;
``` 
Again running the same test being used in #5976 and also incorporating that PR's optimisations for the benchmark, we are getting a further 33.47% performance increase. 
Before: Elapsed time: `22.02603425s`
After: Elapsed time: `14.653166459s`
In discussions with Jibril today, we should probably look at implementing a String interning system but this can be addressed in a future PR.

Wrap `BaseIdent` `name_override_opt` & `TraitName` in an `Arc`

---

sway-core/src/semantic_analysis/namespace/module.rs

The [`im` docs](https://docs.rs/im/latest/im/) state that the performance of `HashMap` is similar to that found in `std` but the `ImOrd` is between 2-3x slower than `BTreeMap`. Changing submodules from using `im::OrdMap` to using `im::HashMap` is giving us a nice performance win. 
I tried compiling the libraries project from fluid protocol as a test, it has 19 seperate libraries. This change gives us a 21.25% speed increase. 
Before: Elapsed time: `27.968193458s`
After:  Elapsed time: `22.02603425s`
Running the compile benchmark in LSP is showing a 29% improvement. 
Before: Elapsed time: `3.8328s`
After: Elapsed time: `2.7086s`

change submodules to use `im::HashMap` instead of `im::OrdMap`

---

sway-core/src/control_flow_analysis/analyze_return_paths.rs
sway-core/src/control_flow_analysis/flow_graph/mod.rs
sway-core/src/lib.rs

Using the same performance test as in #5976 and #5978, this change gives a further 21.33% performance improvement. 
Before: Elapsed time: `14.653166459s`
After: Elapsed time: `11.527667375s`

Make ControlFlowGraph store a reference to Engines to remove clones

---

forc-plugins/forc-client/src/op/deploy.rs
forc-plugins/forc-client/src/util/tx.rs
forc-plugins/forc-tx/src/lib.rs

Base asset ids are dynamic for the newer fuel-core versions. This PR adds capability to query that and use it for forc-client transactions. Also adds a flag `max-fee` which is required to be set for newer versions of fuel-core.

feat: take dynamic asset id into account with `forc-client`

---

test/src/sdk-harness/Cargo.lock
test/src/sdk-harness/Cargo.toml
test/src/sdk-harness/test_projects/low_level_call/mod.rs
test/src/sdk-harness/test_projects/predicate_data_simple/mod.rs
test/src/sdk-harness/test_projects/predicate_data_struct/mod.rs
test/src/sdk-harness/test_projects/tx_fields/mod.rs

This PR is part of https://github.com/FuelLabs/sway/issues/5727 and it is just doing the minimal changes to update `fuels-rs` to version 0.61, given we don´t need to use `master` anymore.

upgrade sdk-harness test to use fuels-rs v0.61

---

forc-plugins/forc-client/src/constants.rs
forc-plugins/forc-client/src/util/node_url.rs
forc-plugins/forc-client/src/util/target.rs

Changes the target of `--testnet` flag to testnet instead of devnet. Also fixes some missing from end point url conversions for target resolving.

feat: point --testnet flag to latest testnet instead of `devnet`

---

Cargo.lock
Cargo.toml
forc-plugins/forc-client/src/op/run/encode.rs
forc-plugins/forc-client/src/op/run/mod.rs
forc-test/src/lib.rs
forc/src/cli/commands/test.rs
sway-core/src/abi_generation/fuel_abi.rs
test/src/e2e_vm_tests/mod.rs
test/src/e2e_vm_tests/test_programs/should_pass/language/configurable_consts/json_abi_oracle_new_encoding.json
test/src/e2e_vm_tests/test_programs/should_pass/language/logging/json_abi_oracle_new_encoding.json
test/src/e2e_vm_tests/test_programs/should_pass/language/main_args/main_args_various_types/json_abi_oracle.json
test/src/e2e_vm_tests/test_programs/should_pass/language/main_args/main_args_various_types/json_abi_oracle_new_encoding.json
test/src/e2e_vm_tests/test_programs/should_pass/language/smo/json_abi_oracle.json
test/src/e2e_vm_tests/test_programs/should_pass/language/smo/json_abi_oracle_new_encoding.json
test/src/e2e_vm_tests/test_programs/should_pass/language/u256/u256_abi/json_abi_oracle_new_encoding.json
test/src/e2e_vm_tests/test_programs/should_pass/stdlib/assert_eq/json_abi_oracle_new_encoding.json
test/src/e2e_vm_tests/test_programs/should_pass/stdlib/assert_eq_revert/json_abi_oracle_new_encoding.json
test/src/e2e_vm_tests/test_programs/should_pass/stdlib/assert_ne/json_abi_oracle_new_encoding.json
test/src/e2e_vm_tests/test_programs/should_pass/stdlib/assert_ne_revert/json_abi_oracle_new_encoding.json
test/src/e2e_vm_tests/test_programs/should_pass/stdlib/require/json_abi_oracle_new_encoding.json
test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/basic_storage/json_abi_oracle_new_encoding.json
test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/multiple_impl/json_abi_oracle_new_encoding.json
test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/storage_access_contract/json_abi_oracle_new_encoding.json
test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/storage_namespace/json_abi_oracle_new_encoding.json
test/src/sdk-harness/Cargo.lock
test/src/sdk-harness/Cargo.toml

Bumps:
1. fuels-rs v0.62.0
2. forc-wallet to v0.7.1
3. fuels-abi-types to v0.5.0
In the process I had to adjust forc-run to use new encoding api from the sdk as well.

chore: use fuels-rs v0.62.0, fuel-abi-types v0.5.0

---

sway-lib-std/src/string.sw

`AbiEncode` and `AbiDecode` are missing for the `String` type. This is required for inline tests being developed in [sway-standards](https://github.com/FuelLabs/sway-standards/issues/91).

Add `AbiEncode` and `AbiDecode` for `String`

---

test/bench.sh

This PR introduces a script that compiles a sway project across multiple commits, and generates an HTML report to help analysis of compilation time and binary size.
The report is 100% autonomous, only depending on CDN scripts, and can be served as it is by any HTTP server. There are two main features worthy of being noted: a pivot table, and the data table.
The pivot table is configured by default to show the average compilation time across multiple commits, like the example below.
Below it, one finds the data table used, with links to Github issues and commits.
The script help can be printed by invoking it without any arguments
```
> test/bench.sh
-n|--qty          how many commits will be used
-b|--branch       which branch will be used. Defaults to "master"
-p|--path         path to …
```

Bash script to help benchmark the compiler

---

.github/CODEOWNERS

Put catchall rule at the beginning rather than the end.
This also makes @FuelLabs/leads the code owners of the release infrastructure.

Fix code owner precedence

---

sway-core/src/semantic_analysis/ast_node/declaration/auto_impl.rs

This PR tries to fix https://github.com/FuelLabs/sway/issues/6093.
The cause seems to be a problem with our error reporting. What is happening is, the source code has other errors unrelated to auto impl of AbiEncode. For example, some private fields are being accessed from other modules.
This is currently panicking because when type-checking the auto impl, some of these errors "leak" into the auto impl `type_check` and make it fail completely; I was expecting the type check would always finish, even if with some errors. 
This was being used as a security guard against implementation bugs. But now that the auto impl is more stable we can remove it, and when a type check completely fails, we do not panic anymore, just failing that particular auto impl.

Do not panic when there is auto impl type check

---

Cargo.lock
Cargo.toml
forc-pkg/src/manifest/mod.rs
forc-pkg/src/pkg.rs
test/src/e2e_vm_tests/test_programs/should_fail/contract_dependencies_conflicting_salt/contract_a/Forc.toml
test/src/e2e_vm_tests/test_programs/should_fail/contract_dependencies_conflicting_salt/contract_b/Forc.toml
test/src/e2e_vm_tests/test_programs/should_pass/forc/contract_dependencies/contract_a/Forc.toml
test/src/sdk-harness/Cargo.lock
test/src/sdk-harness/Cargo.toml

Updates sdk used to v0.63.0 also updates fuel-core to v0.27.0 and forc-wallet to v0.8.0.

chore: bump fuel-core to v0.27.0

---

sway-ir/src/optimize/constants.rs
sway-types/src/u256.rs

This PR fixes a problem with constant folding optimization pass with the mod operator. Unfortunately, we were not checking that the RHS was not zero. So expressions like `mod 1 0` were packing the compiler.

Fix mod by zero constant folding

---

sway-core/src/ir_generation/compile.rs
sway-core/src/language/ty/declaration/function.rs
sway-core/src/query_engine/mod.rs
sway-core/src/semantic_analysis/ast_node/declaration/function.rs
sway-core/src/semantic_analysis/ast_node/declaration/trait_fn.rs
sway-core/src/semantic_analysis/ast_node/expression/typed_expression/function_application.rs
sway-core/src/semantic_analysis/ast_node/expression/typed_expression/method_application.rs
sway-core/src/type_system/id.rs
sway-core/src/type_system/info.rs
test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/asset_ops_test/src/main.sw
test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/call_basic_storage/src/main.sw
test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/call_increment_contract/src/main.sw
test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/call_storage_enum/src/main.sw
test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/storage_access_caller/src/main.sw
test/src/ir_generation/tests/fn_dedup.sw

Adds function cached to query engine, and reuses previously compiled methods and functions.
Closes #5904.

Adds method and function deduplication to frontend.

---

sway-lib-std/src/storage/storage_map.sw
test/src/sdk-harness/test_projects/storage_map_nested/src/main.sw

Currently, the `StorageMap` `remove()` function uses the `slot` to compute the key to remove. When inserting, `field_id` is used. This has been updated. Tests that remove from a nested `StorageMap` have also been added.
Closes #6128

Change `StorageMap`'s `remove()` to use `sha256(key, self.field_id())` instead of `sha256(key, self.slot())`

---

sway-lib-std/src/low_level_call.sw

The parameter does not exist for the functions

Fix doc comment

---

forc-plugins/forc-client/src/op/run/encode.rs
sway-ir/src/optimize/sroa.rs

chore: fix some comments

---

sway-core/src/semantic_analysis/cei_pattern_analysis.rs
test/src/e2e_vm_tests/test_programs/should_pass/static_analysis/cei_pattern_violation_in_asm_block_mint_burn/Forc.lock
test/src/e2e_vm_tests/test_programs/should_pass/static_analysis/cei_pattern_violation_in_asm_block_mint_burn/Forc.toml
test/src/e2e_vm_tests/test_programs/should_pass/static_analysis/cei_pattern_violation_in_asm_block_mint_burn/src/main.sw
test/src/e2e_vm_tests/test_programs/should_pass/static_analysis/cei_pattern_violation_in_asm_block_mint_burn/test.toml

Fixes #6153. 
The `burn` and `mint` instructions have so far not been taken into account in our CEI analysis, despite them having an effect on the contract state. This PR fixes that issue.

Make CEI analysis take `burn` and `mint` into account

---

sway-core/src/semantic_analysis/ast_node/declaration/auto_impl.rs
sway-ir/src/optimize.rs
sway-ir/src/optimize/constants.rs
sway-lib-core/src/codec.sw
test/bench.sh
test/src/e2e_vm_tests/test_programs/should_pass/language/configurable_consts/json_abi_oracle_new_encoding.json
test/src/e2e_vm_tests/test_programs/should_pass/language/slice/slice_contract/src/main.sw
test/src/e2e_vm_tests/test_programs/should_pass/language/string_slice/string_slice_contract/src/main.sw
test/src/e2e_vm_tests/test_programs/should_pass/language/u256/u256_abi/json_abi_oracle_new_encoding.json
test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/array_of_structs_caller/src/main.sw
test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/asset_ops_test/src/main.sw
test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/bal_opcode/src/main.sw
test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/call_abi_with_tuples/src/main.sw
test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/call_basic_storage/src/main.sw
test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/call_contract_with_type_aliases/src/main.sw
test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/call_increment_contract/src/main.sw
test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/call_storage_enum/src/main.sw
test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/caller_auth_test/src/main.sw
test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/caller_context_test/src/main.sw
test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/nested_struct_args_caller/src/main.sw
test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/storage_access_caller/src/main.sw
test/src/e2e_vm_tests/test_programs/should_pass/test_abis/test_fuel_coin_abi/Forc.lock
test/src/e2e_vm_tests/test_programs/should_pass/unit_tests/workspace_test/contract_multi_test/src/main.sw
test/src/sdk-harness/test_projects/auth/mod.rs

This PR implements five optimizations to decrease the binary size of contracts:
1 - create `BufferReader` only once;
2 - `BufferReader` using only one pointer to the current position;
3 - more specialized read fns for `BufferReader`;
4 - remove useless binary operations;
5 - do not encode the result of a contract method, if it is `()`.
Which brings the contract `test_fuel_coin_contract` from 3400 to 2560 bytes. Around 25% improvement. Results will be more timid for bigger contracts.

Improving binary size for encoding v1

---

Cargo.lock
forc-plugins/forc-debug/Cargo.toml
forc-plugins/forc-debug/src/main.rs

fix: fix panic and improve error output in forc-debug

---

examples/advanced_storage_variables/src/main.sw

https://vercel.com/fuel-labs/docs-hub/5r9LvMoawPA5PmVPTqX4p4FFcP8Q?filter=errors
This PR https://github.com/FuelLabs/sway/pull/6051/files broke a page in the docs because of a mislabeled anchor tag
`sway
{{#include ../../../../examples/advanced_storage_variables/src/main.sw:storage_string_import}}`

docs: Fix nightly storage docs

---

sway-ir/src/error.rs
sway-ir/src/verify.rs
sway-ir/tests/tests.rs
sway-ir/tests/verify/entry_block_dominance_frontier.ir
sway-ir/tests/verify/entry_block_mem2reg.ir
sway-ir/tests/verify/entry_block_simplify_cfg.ir

This PR fixes #6148 by verifying that a function entry block cannot have predecessors.
Additionally, the PR provides a simple testing infrastructure for testing IR verifications.
Closes #6148.

Verify that entry block does not have predecessors

---

sway-core/src/semantic_analysis/ast_node/mod.rs
sway-core/src/semantic_analysis/namespace/root.rs

This reverts PR #6080 due to a pretty severe performance regression.
The reason this was split to a separate step was because it needs a typed declaration due to the depedency on the type system and thus cannot be used during collection.
However, the type system will be changed to work with parsed declarations pretty soon, so revert this back to the old behavior and temporarily check for a typed declaration instead.
Fixes https://github.com/FuelLabs/sway/issues/6182.

Handle traits when doing namespace item imports.

---

sway-core/src/asm_generation/fuel/fuel_asm_builder.rs
test/src/e2e_vm_tests/test_programs/should_pass/language/configurable_consts/json_abi_oracle.json
test/src/e2e_vm_tests/test_programs/should_pass/language/configurable_consts/json_abi_oracle_new_encoding.json
test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/call_abi_with_tuples/src/main.sw
test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/call_basic_storage/src/main.sw
test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/call_storage_enum/src/main.sw

This PR generates `$one` register access for the boolean constant `true`, instead of placing `1` into the data section.
This removes loading from the data section when using the constant.
E.g., when calling `function(true)`, instead of:
```
.data:
data_0 .byte 1
```
```
load $r30 data_0                        ; literal instantiation
move $$arg0 $r30                        ; pass arg 0
mova $$reta .9                          ; set new return addr
fncall .4                               ; call function_1
```
we now have:
```
move $$arg0 $one                        ; pass arg 0
mova $$reta .9                          ; set new return addr
fncall .4                               ; call function_1
```
Out of 450 `should_pass` tests, 140 got decreased in the bytecode size.
<details> …

Use `$one` for `true` in ASM instead of using data section

---

sway-lsp/benches/lsp_benchmarks/requests.rs
sway-lsp/src/capabilities/hover/mod.rs
sway-lsp/src/config.rs
sway-lsp/src/handlers/request.rs
sway-lsp/src/utils/markup.rs
sway-lsp/tests/lib.rs

Closes https://github.com/FuelLabs/sway/issues/6091
Front end change: https://github.com/FuelLabs/sway-vscode-plugin/pull/187

fix: only support hover links for vscode

---

test/src/e2e_vm_tests/test_programs/should_fail/multiple_enums_with_the_same_name/test.toml
test/src/e2e_vm_tests/test_programs/should_fail/multiple_structs_with_the_same_name/test.toml

Two disabled tests preventing #418 from being closed, are now fixed.
Closes #418

Enables tests that prove #418 is solved.

---

.github/workflows/ci.yml
Cargo.lock
forc-plugins/forc-client/Cargo.toml
forc-plugins/forc-client/src/constants.rs
forc-plugins/forc-client/src/op/deploy.rs
forc-plugins/forc-client/src/op/mod.rs
forc-plugins/forc-client/src/op/run/mod.rs
forc-plugins/forc-client/src/util/gas.rs
forc-plugins/forc-client/src/util/tx.rs
forc-plugins/forc-client/tests/deploy.rs

closes #6211.
Defers the contract deployment estimation to sdk, and refactors signer selection for better testability. Also added an integration test to ensure we are always able to deploy to fuel-core to prevent this happening in the future. Basically some refactoring and a test addition. The diff is because I split finalize signed. I'll be adding unit tests to the split version in a follow up, probably alongside #6069

fix: deployment estimation deferred to sdk

---

Cargo.lock
forc-pkg/src/lock.rs
forc-pkg/src/pkg.rs
forc-pkg/src/source/git/mod.rs
forc-pkg/src/source/ipfs.rs
forc-plugins/forc-doc/Cargo.toml
forc-plugins/forc-doc/src/lib.rs
forc-tracing/Cargo.toml
forc-tracing/src/lib.rs
forc-util/src/lib.rs
forc/src/cli/commands/test.rs
forc/src/ops/forc_template.rs

Makes the indendation and formatting consistent for forc's action messages.
before
after
before
after

feat: Add helper function for consistent forc output

---

Cargo.lock
forc-pkg/Cargo.toml
forc-pkg/src/pkg.rs

Users can see the bytecode size for every compiled package using the `--verbose` flag with `forc build`. 
The PR makes it so they see the total bytecode size by default without verbose mode in the `Finished` status message.
For workspaces, the bytecode size is the sum of all of the built packages' bytecode.

feat: Print the formatted bytecode size on forc build

---

sway-ir/src/optimize/inline.rs
sway-ir/tests/inline/recursive-1.ir
sway-ir/tests/tests.rs

Also update the testsuite inliner predicate to respect inline annotations.
Closes #6149

Inliner shouldn't inline a function into itself

---

sway-core/src/type_system/info.rs

This PR adds `string slices` to `CURRENTLY_SUPPORTED_TYPES_MESSAGE` in `match` expressions. The support for string slices is added in #6202.

Add string slices to supported types message in match expressions

---

test/src/sdk-harness/test_projects/run_external_proxy/mod.rs

This test was disabled when we introduced encoding v1. But it has been fixed since and we can enable it again.

re-enable LDC test

---

sway-lsp/src/server_state.rs

This PR introduces an LRU (Least Recently Used) cache mechanism for managing sessions in large workspaces. This change aims to address the issue of high RAM usage reported in workspaces with multiple projects.
closes #6222

Add LRU Session Cache to Reduce RAM Usage

---

sway-lsp/tests/fixtures/tokens/abi/Forc.toml
sway-lsp/tests/fixtures/tokens/consts/Forc.toml
sway-lsp/tests/fixtures/tokens/fields/Forc.toml
sway-lsp/tests/fixtures/tokens/matches/Forc.toml
sway-lsp/tests/fixtures/tokens/paths/Forc.toml
sway-lsp/tests/fixtures/tokens/structs/Forc.toml
sway-lsp/tests/fixtures/tokens/turbofish/Forc.toml
sway-lsp/tests/fixtures/tokens/variables/Forc.toml
sway-lsp/tests/lib.rs

#6116 introduces changes to how the `std` and `core` preludes are imported. This change causes a number of `lsp` tests to fail, because the `lsp` tests rely on `v0.48.1` of the standard library, which is no longer consistent with the code in #6116.
This PR is an attempt to fix those failing tests. In some cases the tests have just been updated to use the most recent standard library, but in a few cases I couldn't figure out what needed to be done, so those tests have been commented out.

Fix lsp tests for changes related to reexports

---

sway-core/src/abi_generation/abi_str.rs

Small code refactor

---

sway-core/src/asm_lang/virtual_ops.rs
sway-error/src/handler.rs

Optimization Explanation
- Using HashSet to track seen elements simplifies the code logic.
- Using the retain method directly filters out duplicate elements in place, avoiding the complexity of manually managing indices and swapping elements.
- The code is more concise and readable while maintaining the original order.
- Time complexity comparison: Original code: Due to the need to manually manage indices and swap elements, the time -complexity is O(n^2) (in the worst case). Optimized code: Using HashSet and the retain method, the time complexity is O(n).
- Space complexity comparison: Original code: Requires additional HashMap and SmallVec to store hash values and indices. Optimized code: Only requires a HashSet to store seen elements.

Use HashSet for error deduplication

---

sway-lsp/benches/lsp_benchmarks/compile.rs
sway-lsp/src/core/session.rs
sway-lsp/src/core/sync.rs
sway-lsp/src/error.rs
sway-lsp/src/handlers/request.rs

closes #5462
related #5445
before we were recreating the build plan on every keystroke. We now cache the result and reuse on subsequent did change events. We invalidate the cache if there has been any modifications to the `Forc.toml` file since the cache was created.
Here are the timings when triggering this with a did_change event on the FUSD repo.
previous: `80.146ms`
with this change: `56µs`

Cache Build Plans in language server

---

sway-lsp/src/core/document.rs
sway-lsp/src/handlers/notification.rs
sway-lsp/src/server.rs
sway-lsp/src/server_state.rs

Implements a new `PidLockedFiles` type for efficient file locking. Before this we were doing file IO on every did change key press event. We now cache the results for efficiency.

cache pid lock files to reduce IO operations

---

docs/book/src/SUMMARY.md
docs/book/src/reference/undefined_behavior.md

Add a section in the docs to list known UB.

Add documentation about Undefined Behavior

---

docs/book/src/reference/known_issues_and_workarounds.md

related https://github.com/FuelLabs/sway/issues/6300

fix: update the document link for Manual Storage Management.

---

docs/book/src/index.md

correction grammar errors
_The standard library has **it's** own reference documentation that has detailed information about each module in std._ => _The standard library has **its** own reference documentation that has detailed information about each module in std._
"it's" should be corrected to "its". "It's" is a contraction for "it is", while "its" is the possessive form.
_Similar to ERC standards for Ethereum and Solidity, Sway has **it's** own SRC standards..._ => _Similar to ERC standards for Ethereum and Solidity, Sway has **its** own SRC standards..._
"it's" should be corrected to "its".

chore: correction typos index.md

---

sway-lsp/tests/fixtures/tokens/abi/Forc.toml
sway-lsp/tests/fixtures/tokens/consts/Forc.toml
sway-lsp/tests/fixtures/tokens/fields/Forc.toml
sway-lsp/tests/fixtures/tokens/matches/Forc.toml
sway-lsp/tests/fixtures/tokens/paths/Forc.toml
sway-lsp/tests/fixtures/tokens/paths/src/deep_mod.sw
sway-lsp/tests/fixtures/tokens/paths/src/deep_mod/deeper_mod.sw
sway-lsp/tests/fixtures/tokens/paths/src/main.sw
sway-lsp/tests/fixtures/tokens/storage/Forc.toml
sway-lsp/tests/fixtures/tokens/structs/Forc.toml
sway-lsp/tests/fixtures/tokens/turbofish/Forc.toml
sway-lsp/tests/fixtures/tokens/variables/Forc.toml
sway-lsp/tests/lib.rs

Re-pin LSP tests to published version of `std` and re-enable commented out tests

---

Cargo.lock
forc-pkg/Cargo.toml
forc-util/src/fs_locking.rs

chore: bump forc-pkg deps and fix clippy warnings

---

Cargo.lock
Cargo.toml
templates/sway-test-rs/template/Cargo.toml
test/src/sdk-harness/Cargo.lock
test/src/sdk-harness/Cargo.toml

Bump sdk and fuel-core versions

chore: bump sdk version

---

forc-plugins/forc-client/src/op/deploy.rs
forc-plugins/forc-client/src/util/tx.rs
forc-plugins/forc-client/tests/deploy.rs

Embeds proxy abi to code directly, without a path due to limitations around cargo publish and `abigen!` macro.

fix release workflow by embedding proxy abi to code in plain str

---

.github/workflows/ci.yml
templates/sway-predicate-test-rs/template/Cargo.toml
templates/sway-script-test-rs/template/Cargo.toml
templates/sway-test-rs/template/Cargo.toml

Fix sway templates

---

sway-lib-core/src/codec.sw
test/src/e2e_vm_tests/test_programs/should_pass/language/configurable_consts/json_abi_oracle_new_encoding.json
test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/storage_access_caller/src/main.sw

`AbiDecode` for `bool` was not checking for valid values allowing unsound bools that were not `true` nor `false`. Given that `3VL` is not within our scope here (:smile:), this PR will now `revert` in this case which is certainly a problem decoding values.
The same thing already happens for `enum` variant, which also `revert(0)` when the variant is unknown.
These two are the only cases where the "encoded bytes" can live outside of their respective valid set.

Guarantee only valid bools are being decoded

---

sway-lsp/src/server_state.rs

Implemented a caching mechanism for manifest directory lookups using a DashMap. This optimization reduces average lookup time from approximately 421µs to 0.47µs, resulting in an 895x speed improvement for subsequent calls.
part of #5445

Optimize manifest directory lookup with efficient caching

---

.vscode/settings.json
forc-pkg/src/pkg.rs

Closes #6209 
It looks like the compiler actually doesn't cache anything between builds, so this issue can be closed.

chore: remove comment

---

swayfmt/src/formatter/mod.rs
swayfmt/src/items/item_storage/mod.rs
swayfmt/src/utils/language/punctuated.rs
swayfmt/tests/mod.rs

Handle formatting new types in `StorageField`

---

sway-core/src/semantic_analysis/ast_node/code_block.rs
sway-core/src/semantic_analysis/ast_node/declaration/declaration.rs
sway-core/src/semantic_analysis/namespace/lexical_scope.rs
sway-core/src/semantic_analysis/namespace/module.rs

As shown in https://fuellabs.github.io/sway-performance-dashboard/ #6461 introduced a bigger memory footprint.
Lexical scope has a shared OrdMap called `symbols_unique_while_collecting_unifications` that was never cleared.
With this commit, it is cleared on each code block along with the clear of collected unifications.

Reduces memory footprint of collecting unifications.

---

test/src/in_language_tests/test_programs/math_inline_tests/Forc.toml
test/src/in_language_tests/test_programs/math_inline_tests/src/main.sw

Adds some in language tests for overflow and unsafe math operations. Ensuring the operations revert

add overflow and unsafe math tests

---

.github/workflows/bench-lsp.yml
.github/workflows/benchmark.yml
Cargo.lock
sway-lsp/Cargo.toml
sway-lsp/README.md
sway-lsp/benches/bench_main.rs
sway-lsp/benches/lsp_benchmarks/compile.rs
sway-lsp/benches/lsp_benchmarks/requests.rs
sway-lsp/benches/lsp_benchmarks/token_map.rs

Closes https://github.com/FuelLabs/sway/issues/6477

ci: Benchmark with codspeed

---

sway-core/src/semantic_analysis/ast_node/expression/typed_expression/function_application.rs
test/src/e2e_vm_tests/test_programs/should_fail/bad_generic_annotation/test.toml
test/src/e2e_vm_tests/test_programs/should_fail/language/reexport/shadowing_in_reexporting_module/test.toml
test/src/e2e_vm_tests/test_programs/should_fail/recursive_type_unification/test.toml
test/src/e2e_vm_tests/test_programs/should_pass/language/function_return_type_unification/.gitignore
test/src/e2e_vm_tests/test_programs/should_pass/language/function_return_type_unification/Forc.lock
test/src/e2e_vm_tests/test_programs/should_pass/language/function_return_type_unification/Forc.toml
test/src/e2e_vm_tests/test_programs/should_pass/language/function_return_type_unification/src/main.sw
test/src/e2e_vm_tests/test_programs/should_pass/language/function_return_type_unification/test.toml

The function return type unification was missing, leading to generic functions not being resolved based on the return type.

Adds function return type unification.

---

sway-core/src/abi_generation/abi_str.rs
test/src/e2e_vm_tests/test_programs/should_pass/language/main_args/main_args_generics/json_abi_oracle_new_encoding.json
test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/abi_with_alias/Forc.lock
test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/abi_with_alias/Forc.toml
test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/abi_with_alias/json_abi_oracle.json
test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/abi_with_alias/json_abi_oracle_new_encoding.json
test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/abi_with_alias/src/main.sw
test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/abi_with_alias/test.toml

Before this push, using an alias in a contract would produce an ABI with two distinct metadata types for tuples: one for `(_,_)` and another for `(u64,u64)`.
With this change, aliases are bypassed and we only produce metadata for the string type of the inner alias type. If alias is `(u64, u64)` we will produce a metadatatype for `(_,_)`.
Fixes #6488

Fixes ABI alias metadata types.

---

test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/array_of_structs_caller/src/main.sw

This PR improves tests for https://github.com/FuelLabs/sway/pull/6490. Now we have one contract test where the contract address comes from a complex expression.

Test for contract address being a complex expression

---

sway-lib-std/src/auth.sw
test/src/sdk-harness/test_projects/auth/mod.rs

The `msg_sender()` function used the `sender` of a `Input::Message` rather than the `recipient`.
Closes #6485

Change `msg_sender()`'s `Input::Message` from sender to recipient

---

test/src/e2e_vm_tests/test_programs/should_pass/language/function_return_type_unification/.gitignore
test/src/e2e_vm_tests/test_programs/should_pass/language/function_return_type_unification/Forc.lock
test/src/e2e_vm_tests/test_programs/should_pass/language/function_return_type_unification/src/main.sw
test/src/e2e_vm_tests/test_programs/should_pass/language/function_return_type_unification/test.toml
test/src/e2e_vm_tests/test_programs/should_pass/language/type_inference_propagation_of_type_constraints/Forc.lock
test/src/e2e_vm_tests/test_programs/should_pass/language/type_inference_propagation_of_type_constraints/Forc.toml
test/src/e2e_vm_tests/test_programs/should_pass/language/type_inference_propagation_of_type_constraints/src/main.sw
test/src/e2e_vm_tests/test_programs/should_pass/language/type_inference_propagation_of_type_constraints/test.toml

This PR adds tests that prove that #6379 is fixed. The actual fix happened in #6490.
Closes #6379.

Add tests for propagation of type constraints in type inference

---

sway-core/src/semantic_analysis/ast_node/expression/match_expression/analysis/usefulness.rs
test/src/e2e_vm_tests/test_programs/should_pass/language/match_expressions_unreachable_or/Forc.lock
test/src/e2e_vm_tests/test_programs/should_pass/language/match_expressions_unreachable_or/Forc.toml
test/src/e2e_vm_tests/test_programs/should_pass/language/match_expressions_unreachable_or/src/main.sw
test/src/e2e_vm_tests/test_programs/should_pass/language/match_expressions_unreachable_or/test.toml

This PR fixes #6388. If a whole OR match arm is unreachable a warning will be emitted like in this case:
```Sway
match v {
1 => (),
2 => (),
1 | 2 => (), <<<--- Warning emitted here.
_ => (),
};
```
The PR strictly fixes the issue reported in #6388. It does not fix a previously known, more general issue, described in #5097 where we expect warnings to be emitted also on individual elements of an OR arm, even if the whole arm is reachable. E.g.:
```Sway
match v {
1 => (),
2 => (),
1 | 3 => (), <<<--- Warning should be emitted here that `1` is not reachable.
2 | 4 => (), <<<--- Warning should be emitted here that `2` is not reachable.
_ => (),
};
```
Fixing this issue requires more invasive restructuring of the propagation of the collected witness information and will be done in a separate …

Emit unreachable arm warning for OR match arms

---

.github/workflows/ci.yml
Cargo.lock
Cargo.toml
test/src/sdk-harness/Cargo.lock
test/src/sdk-harness/Cargo.toml

Updates the sdk version to 0.66.4 mainly for getting the sdk [fix for blobed code behind proxy](https://github.com/FuelLabs/fuels-rs/commit/fc6eb566aeef2fdfa4b8f4134c05bfd44264b7ea). Also updates the fuel-core version used to 0.35.0 as this is the latest version testnet is using.

chore: use fuel-core 0.35.0 and sdk 0.66.4

---

.github/workflows/ci.yml

Separating this commit out from the main commit of #6179...
This PR comes in two commits:
1. The changes to CI - replace `cargo-deps` with `cargo tree`
2. A test commit that will create a cyclic dependency which will be reverted once it's tested to be working
The origin commit message:
- cargo-deps is no longer maintained
- cargo-deps doesn't understand workspaces

Replace cargo deps with built-in cargo tree (#6179)

---

sway-core/src/language/ty/expression/expression_variant.rs
sway-core/src/semantic_analysis/ast_node/expression/typed_expression/method_application.rs
sway-lsp/tests/integration/code_actions.rs
test/src/e2e_vm_tests/test_programs/should_pass/language/generic_impl_self/Forc.lock
test/src/e2e_vm_tests/test_programs/should_pass/language/generic_impl_self/Forc.toml
test/src/e2e_vm_tests/test_programs/should_pass/language/generic_impl_self/src/main.sw

This PR fixes https://github.com/FuelLabs/sway/issues/6487.

fix second pass of method application arguments

---

sway-core/src/transform/to_parsed_lang/convert_parse_tree.rs
sway-error/src/convert_parse_tree_error.rs
test/src/e2e_vm_tests/test_programs/should_fail/invalid_cfg_arg/Forc.lock
test/src/e2e_vm_tests/test_programs/should_fail/invalid_cfg_arg/Forc.toml
test/src/e2e_vm_tests/test_programs/should_fail/invalid_cfg_arg/src/main.sw
test/src/e2e_vm_tests/test_programs/should_fail/invalid_cfg_arg/test.toml

We now throw an error that enforces cfg arg to be a valid one.
Fixes #6326

Fixes unreachable on invalid cfg attribute arg.

---

sway-core/src/semantic_analysis/ast_node/declaration/impl_trait.rs
test/src/e2e_vm_tests/test_programs/should_fail/mismatch_closing_delimiters/Forc.lock
test/src/e2e_vm_tests/test_programs/should_fail/mismatch_closing_delimiters/Forc.toml
test/src/e2e_vm_tests/test_programs/should_fail/mismatch_closing_delimiters/src/main.sw
test/src/e2e_vm_tests/test_programs/should_fail/mismatch_closing_delimiters/test.toml

An unused line of code threw an OOB panic because of a parser error. Removing the unused line of code fixes the issue.
Fixes #6331

Fixes OOB in type_check_analyze of ImplTrait.

---

sway-core/src/semantic_analysis/namespace/root.rs
test/src/e2e_vm_tests/test_programs/should_fail/parser_associated_type_error/Forc.lock
test/src/e2e_vm_tests/test_programs/should_fail/parser_associated_type_error/Forc.toml
test/src/e2e_vm_tests/test_programs/should_fail/parser_associated_type_error/src/main.sw
test/src/e2e_vm_tests/test_programs/should_fail/parser_associated_type_error/test.toml

Doing an unwrap without checking if the value was none was causing a panic. Fixed by throwing an error so we can also see the previous errors.
Fixes #6330

Fixes panic error on decl_to_type_info.

---

.vscode/launch.json
sway-core/src/engine_threading.rs
sway-core/src/query_engine/mod.rs
sway-lsp/src/config.rs
sway-lsp/src/server_state.rs
sway-lsp/tests/fixtures/garbage_collection/minimal_script/.gitignore
sway-lsp/tests/fixtures/garbage_collection/minimal_script/Forc.toml
sway-lsp/tests/fixtures/garbage_collection/minimal_script/src/main.sw
sway-lsp/tests/lib.rs

Fixes a bug that would crash the language server when a function node was part of the AST.
#5967 added a function cache to the `QueryEngine`. Garbage collection needed to be called on this otherwise it returns references to types that have been cleared from the other engines during garbage collection. 
In the future, any other nodes that we decide to cache need to have GC applied to them or we will end up crashing the language server on the first key-pressed event. 
I've also removed the gc_frequency setting and now run GC on each keystroke. Without doing this, the spans stored in the TokenMap and what was returned from the compiler were falling out of sync. This ensures that everything is always up to date and the correct spans are used. closes #5260 
Finally, I've added a `launch.json` …

Fix `function_cache` garbage collection bug 

---

.github/workflows/ci.yml
sway-lib-std/src/bytes.sw
sway-lib-std/src/vec.sw

This typo was introduced here: https://github.com/FuelLabs/sway/commit/5e24673b827837690b41dfbffd2bf746d936b90d#diff-b803fcb7f17ed9235f1e5cb1fcd2f5d3b2838429d4368ae4c57ce4436577f03fR465
`&` should be `&&`
It caused the exit code to be 0 even though some of the tests fails to compile. Example: https://github.com/FuelLabs/sway/actions/runs/10865968373/job/30152989834#step:6:86
Thanks @alfiedotwtf for noticing these failing tests!

ci: Fix typo in forc-unit tests

---

forc-plugins/forc-client/src/op/deploy.rs

It looks like there was a change in how fuel core client returns the block height. It used to be a hex number and we had to convert it to decimal, but now it’s returning the number as a decimal so we don't need to convert it.

fix: forc-deploy block url

---

Cargo.lock
Cargo.toml
forc-pkg/Cargo.toml
forc-plugins/forc-client/Cargo.toml
forc-plugins/forc-crypto/Cargo.toml
forc-plugins/forc-debug/Cargo.toml
forc-plugins/forc-doc/Cargo.toml
forc-plugins/forc-fmt/Cargo.toml
forc-plugins/forc-lsp/Cargo.toml
forc-plugins/forc-tx/Cargo.toml
forc-test/Cargo.toml
forc-tracing/Cargo.toml
forc-util/Cargo.toml
forc/Cargo.toml
scripts/mdbook-forc-documenter/Cargo.toml
sway-ast/Cargo.toml
sway-core/Cargo.toml
sway-error/Cargo.toml
sway-ir/Cargo.toml
sway-ir/sway-ir-macros/Cargo.toml
sway-lsp/Cargo.toml
sway-lsp/tests/utils/Cargo.toml
sway-parse/Cargo.toml
sway-types/Cargo.toml
sway-utils/Cargo.toml
swayfmt/Cargo.toml
test/Cargo.toml
test/src/sdk-harness/Cargo.toml

For #6179, PR #6501 kept bumping into errors as it was doing too many things, so I've split that PR into multiple PRs. This is the first, and the only thing it does is move all of the various `Cargo.toml` dependencies into the single workspace `Cargo.toml`.
Future PRs will:
- Update dependency versions
- Update code that breaks from the version bumps

Move all crate dependencies to the workspace Cargo.toml (#6179)

---

sway-lsp/src/core/session.rs
sway-lsp/src/handlers/notification.rs

I noticed that the language server would crash when compilation was triggered from a did save event as we were trying to create runnables from the Engines that had GC applied to it. We now check to ensure that the correct Engines is accessed to avoid a panic when creating runnables. 
After fixing this bug, I noticed that optimised builds was not returning diagnostics. I've opened #6576 to work on this and have temporarily disabled the optimisation so diagnostics continue to work.

fix OOB slab panic when creating runnables on a did_save event

---

Cargo.toml

This should [unblock](https://github.com/FuelLabs/sway/actions/runs/11035362451/job/30652169645#step:4:22) releases. [Cargo doesn't use the workspace version for path dependencies](https://github.com/rust-lang/cargo/issues/11133), so we still have to specify the versions. This is also how it's done in [fuel-core](https://github.com/FuelLabs/fuel-core/blob/master/Cargo.toml).
This is actually nice because it means we could in the future bump the versions of the dependencies separately, all from within the one file.

ci: add versions to cargo workspace

---

sway-lsp/src/capabilities/code_actions/diagnostic/auto_import.rs

I noticed that autocomplete wasn't working for some function declarations. It was because sometimes function declarations in the token map are stored as `TyDecl::FunctionDecl(decl)` and sometimes as `TypedAstToken::TypedFunctionDeclaration(TyFunctionDecl {..})`
This PR expands the matching for declarations to make autocomplete work in more cases.

fix: Capture more declarations for sway autocomplete

---

Cargo.lock
Cargo.toml

Adds blob deployments for scripts and predicates. Supports fuels 0.66.6 and fuel-core 0.37.0.

chore: bump to 0.65.0

---

docs/book/src/forc/plugins/forc_client/index.md
forc-plugins/forc-client/src/op/deploy.rs

Pins forc-deploy chunk sizes to 100kb to fix errors while deploying chunked contracts. To unblock an ecosystem project, the PR is marked critical.

fix: pin forc-deploy to use 100kb blob size by default

---

.github/CODEOWNERS

This was added in #6600. Reverting this back to the original code owners now after having a chat with Mike.

revert to original code owners before the freeze

---

docs/book/src/forc/plugins/forc_client/index.md
forc-plugins/forc-client/src/cmd/deploy.rs
forc-plugins/forc-client/src/constants.rs
forc-plugins/forc-client/src/lib.rs
forc-plugins/forc-client/src/util/node_url.rs
forc-plugins/forc-client/src/util/target.rs

Removes any references to beta networks and unmaintained devnet channels.

remove beta and devnet refs

---

docs/book/src/forc/plugins/forc_client/index.md
forc-plugins/forc-client/src/cmd/deploy.rs
forc-plugins/forc-client/src/constants.rs
forc-plugins/forc-client/src/lib.rs
forc-plugins/forc-client/src/op/deploy.rs
forc-plugins/forc-client/src/util/node_url.rs
forc-plugins/forc-client/src/util/target.rs
forc-plugins/forc-client/src/util/tx.rs
forc-plugins/forc-client/tests/deploy.rs

add new target to forc

---

Cargo.lock
Cargo.toml
forc-plugins/forc-client/src/util/target.rs
forc-plugins/forc-client/src/util/tx.rs
test/src/sdk-harness/Cargo.lock
test/src/sdk-harness/Cargo.toml

Bumps fuel-core v0.40.0 and SDK to 0.66.9.
Also updates the account selection phase of forc-deploy to show check sum  encoded address.

feat: bump fuel-core to v0.40.0 and sdk to v0.66.9 + show checksum addresses in forc-deploy

---

Cargo.lock
Cargo.toml

supports `fuel-core 0.40.0` and `fuels-rs 0.66.9`
removes support for the beta channels from `forc` and adds mainnet target. #6621 
~~waiting on #6630~~

chore: bump to v0.66.0

---

sway-lib-std/src/math.sw
test/src/in_language_tests/test_programs/bytes_inline_tests/src/main.sw
test/src/in_language_tests/test_programs/math_inline_tests/src/main.sw

u256.log() now always recovers the flag register. Additionally the method now returns 0u256 with invalid args when unsafe math panic is disabled.
Closes #6644

fix: u256 log suggestions

---

sway-ir/src/optimize/memcpyopt.rs
sway-ir/tests/memcpyopt/no_memcpyopt_wide_binary_operator.ir
sway-ir/tests/memcpyopt/no_memcpyopt_wide_unary_operator.ir

This PR fixes the issue of  `FuelVMInstruction`s not being considered in the `memcpyopt` as storing into the destination. E.g., in this example:
```
script {
entry fn main() -> u256 {
local u256 x
local u256 y
local u256 z
entry():
v0 = get_local ptr u256, x
v1 = get_local ptr u256, y
v2 = get_local ptr u256, z
mem_copy_val v2, v0
wide add v0, v1 to v2
v3 = load v2
ret u256 v3
}
}
```
after the `memcpyopt` the `v3 = load v2` got turned into `v3 = load v0` because the `v2` is considered as not being written to.

Properly treat `FuelVMInstruction`s in the `memcpyopt`

---

sway-lib-std/src/auth.sw

caller_addresses: use input_message_recipient

---

.github/workflows/ci.yml

Moves CI runners to buildjet from github.
|         | before | after |
|---------|--------|-------|
| total   | 6823   | 4815  |
| slowest | 1004   | 717   |
Overall, %30 faster CI times, ~5 minutes removed for each PR in slowest run (e2e testing).

ci: move to buildjet

---

sway-core/src/semantic_analysis/ast_node/expression/typed_expression.rs
test/src/e2e_vm_tests/test_programs/should_fail/array_wrong_elements_types/src/main.sw
test/src/e2e_vm_tests/test_programs/should_fail/array_wrong_elements_types/stdout.snap
test/src/e2e_vm_tests/test_programs/should_fail/type_check_analyze_errors/stdout.snap

This PR fixes an issue with array items that are typed as `TypeInfo::Error`. These errors were being swallowed and the compiler was failing later with an ICE.
Now we correctly show the more user-friendly error.
```
--> test/src/e2e_vm_tests/test_programs/should_fail/array_wrong_elements_types/src/main.sw:51:26
|
49 | 
50 |     // Literal too big
51 |     let mut a = [8u8, 8, 18446744073709551615];
|                          ^^^^^^^^^^^^^^^^^^^^ Literal value is too large for type u8.
52 | }
```

improve error messages for array items

---

update_fuel_dependencies.sh

Adds a bash script which iterates over all fuel owned/maintained crates we depend on and only runs cargo update for them. 
This is especially useful for incorporating minor bumps which happens much more often.

chore: add a script to bump all fuel maintained dependencies

---

docs/book/src/reference/sway_libs.md
docs/book/src/sway-program-types/libraries.md

closes #6636.
closes #6631.
As of https://github.com/FuelLabs/sway-libs/pull/278 sway-libs/fixed-point library is deprecated and removed completely from sway-libs repo. We should not link it from our book as well.

docs: remove dead links to sway-libs/fixed-point

---

Cargo.lock
swayfmt/Cargo.toml
swayfmt/test_macros/src/lib.rs

closes #5421.
Removes unmaintained `difference` create used in swayfmt and uses `similar` instead. Security wise this is not an important problem as the dependency is only used as a dev-dependency. But the pr is a part of an effort cleaning `RUSTSEC` issues mainly for housekeeping reasons of our ever growing repo.

chore: remove unmaintained `difference` in favor of `similar`

---

Cargo.lock
Cargo.toml
forc-pkg/Cargo.toml
forc-pkg/src/lock.rs
forc-pkg/src/pkg.rs
forc-pkg/src/source/git/mod.rs
forc-pkg/src/source/ipfs.rs
forc-tracing/Cargo.toml
forc-tracing/src/lib.rs
forc-util/Cargo.toml
forc-util/src/cli.rs
forc-util/src/lib.rs
forc/Cargo.toml
forc/src/cli/commands/test.rs
swayfmt/Cargo.toml
swayfmt/test_macros/Cargo.toml

related to #2601.
Removes ansi_term dependency from sway crates. To remove the dependency completely from dep tree we need a release of sway repo to get a new version of forc_util and use it in forc_wallet as forc_wallet is depending on `forc-util v0.47.0` which uses `ansi_term`. Once that is done we can close #2601

chore: remove unmaintained `ansi_term` in favor of `ansiterm`

---

forc-plugins/forc-client/src/op/deploy.rs
forc-plugins/forc-client/src/util/tx.rs
forc-plugins/forc-client/tests/deploy.rs

closes #6703 and unblocks #6680.
Forc-deploy was asking for a password without checking if a wallet exists or not and the check for existence was happening after the password prompt. This meant we were asking for a password even when the wallet does not exists.
Below examples are taken in a system where the wallet does not exists at the default path (a fresh system):
```bash
...
Confirming transactions [deploy final-contract]
Network: https://testnet.fuel.network
Wallet: /Users/kayagokalp/.fuel/wallets/.wallet
✔ Wallet password · ****
? Could not find a wallet at "/Users/kayagokalp/.fuel/wallets/.wallet", would you like to create a new one? [y/N]:  (y/n) ›
```
```bash
...
Confirming transactions [deploy final-contract]
Network: https://testnet.fuel.network
? Could not find a wallet at …
```

fix: forc-deploy asks for password before checking if the wallet exists

---

Cargo.lock
Cargo.toml
forc-plugins/forc-client/src/util/tx.rs

- Adds support for importing a wallet on `forc-deploy`
- Resolves https://github.com/FuelLabs/forc-wallet/issues/139

Forc-deploy import wallet support if non-existent wallet

---

Cargo.lock
Cargo.toml
test/src/sdk-harness/Cargo.lock
test/src/sdk-harness/Cargo.toml

This latest version of the fuels sdk should unblock the CI pipeline.

chore: upgrade fuels sdk to 66.10

---

.github/workflows/ci.yml

Add a single job that depends on all the CI checks so we can make a single job required.

Add verifications-complete job

---

docs/book/src/forc/manifest_reference.md
forc-pkg/src/manifest/mod.rs

Adds support for `metadata` as `[project.metadata]` or `[workspace.metadata]` in `Forc.toml` of value `toml::Value`
- Addresses: https://github.com/FuelLabs/rfcs/blob/22bf3936a37b60bb496232c1b52bf59e204a0697/text/rfcs/0006-metadata-in-forc-manifest.md#reference-level-explanation
- Resolves: https://github.com/FuelLabs/sway/issues/2180
- https://github.com/FuelLabs/example-forc-plugins/pull/1

`Forc.toml` metadata support

---

sway-core/src/semantic_analysis/ast_node/declaration/auto_impl.rs
test/src/e2e_vm_tests/test_programs/should_pass/language/main_args/main_args_various_types/Forc.toml
test/src/e2e_vm_tests/test_programs/should_pass/language/main_args/main_args_various_types/json_abi_oracle_new_encoding.json
test/src/e2e_vm_tests/test_programs/should_pass/language/main_args/main_args_various_types/src/main.sw
test/src/e2e_vm_tests/test_programs/should_pass/language/main_args/main_args_various_types/src/types.sw

Fixes https://github.com/FuelLabs/sway/issues/6569

Support for aliased import for encoding v1

---

forc-plugins/forc-client/tests/deploy.rs
sway-core/src/asm_generation/fuel/optimizations.rs
test/src/e2e_vm_tests/test_programs/should_pass/language/configurable_consts/json_abi_oracle_new_encoding.json
test/src/e2e_vm_tests/test_programs/should_pass/language/configurable_dedup_decode/snapshot.toml
test/src/e2e_vm_tests/test_programs/should_pass/language/configurable_dedup_decode/stdout.snap
test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/array_of_structs_caller/src/main.sw
test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/asset_ops_test/src/main.sw
test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/asset_ops_test/test.toml
test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/call_basic_storage/src/main.sw
test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/call_contract_with_type_aliases/src/main.sw
test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/storage_access_caller/src/main.sw

This PR improve value propagation optimization in two ways:
1 - First, when the optimizer knows that both source and destination registers of the `MOVE`  instruct have the same value and version; it will remove the instruction as it is useless;
2 - Otherwise, we propagate the value saying that destination now have the same value and version of the source register for other optimizations.

improve asm copy propagation for MOVE instruction

---

sway-core/src/decl_engine/ref.rs
sway-core/src/type_system/id.rs
sway-core/src/type_system/substitute/subst_types.rs

Changes `SubstTypesContext` to contain an optional `TypeSubstMap`.
This is to make this usable from collection context where no type substitution needs to be done.

Change `SubstTypesContext` to contain an optional `TypeSubstMap`.

---

sway-core/src/semantic_analysis/ast_node/code_block.rs
sway-core/src/semantic_analysis/ast_node/declaration/abi.rs
sway-core/src/semantic_analysis/ast_node/declaration/enum.rs
sway-core/src/semantic_analysis/ast_node/declaration/function.rs
sway-core/src/semantic_analysis/ast_node/declaration/impl_trait.rs
sway-core/src/semantic_analysis/ast_node/declaration/struct.rs
sway-core/src/semantic_analysis/ast_node/declaration/trait.rs
sway-core/src/semantic_analysis/ast_node/declaration/trait_fn.rs
sway-core/src/semantic_analysis/ast_node/expression/typed_expression.rs
sway-core/src/semantic_analysis/namespace/lexical_scope.rs
sway-core/src/semantic_analysis/namespace/module.rs
sway-core/src/semantic_analysis/symbol_collection_context.rs

This adds a mapping from a lexical scope to the declaration that lexically corresponds to it.
This is necessary for some upcoming collection context PR.

Associate lexical scopes with their respective declarations.

---

docs/reference/src/documentation/language/control-flow/match/single-line.md
docs/reference/src/documentation/operations/namespace/index.md
docs/reference/src/documentation/operations/reentrancy.md

fix: typos cleanup

---

.github/workflows/ci.yml

This PR extends the language and SDK tests on CI to also run with the `storage_domains` experimental feature turned on.
This is a part of our general testing strategy for experimental features. For E2E tests, we test only a handful of selected tests with the target experimental feature turned on. For language and SDK tests, we want to run all of the tests for every experimental feature.

Add testing of `storage_domains` to language and SDK tests

---

test/src/in_language_tests/test_programs/math_inline_tests/src/main.sw
test/src/in_language_tests/test_programs/math_inline_tests/src/modulo.sw

Add inline test for modulo operator for primitive types u8 u16 u32 u64 and u256
Closes #6776

Add modulo inline tests

---

swayfmt/src/utils/language/expr/mod.rs
swayfmt/src/utils/language/expr/tests.rs
swayfmt/tests/mod.rs

fix: formatting for loop

---

.github/workflows/ci.yml
.github/workflows/gh-pages.yml
forc-plugins/forc-doc/README.md
forc-plugins/forc-doc/src/cli.rs
forc-plugins/forc-doc/src/lib.rs
forc-plugins/forc-doc/src/tests/expects/impl_trait/mod.rs
forc-plugins/forc-doc/tests/lib.rs
forc-plugins/forc-fmt/src/main.rs

Closes https://github.com/FuelLabs/sway/issues/5789

Rename forc doc `--manifest-path` to `--path`

---

sway-lib-core/src/primitive_conversions.sw
sway-lib-std/src/bytes.sw

Previously due to issue #1548 it was not possible to use a method defined in an impl block in another method defined in the same impl block, that issue is now fixed.

Remove instances of multiple impl blocks

---

test/src/in_language_tests/test_programs/bytes_inline_tests/src/main.sw

A few bytes tests are erroneously missing the test attribute, meaning they are not actually run.

add erroneously missing #[test()] attribute

---

sway-core/src/asm_generation/finalized_asm.rs
sway-core/src/asm_generation/fuel/allocated_abstract_instruction_set.rs
sway-core/src/asm_generation/fuel/checks.rs
sway-core/src/asm_generation/fuel/fuel_asm_builder.rs
sway-core/src/asm_generation/fuel/functions.rs
sway-core/src/asm_generation/fuel/optimizations.rs
sway-core/src/asm_generation/fuel/programs/abstract.rs
sway-core/src/asm_generation/fuel/register_allocator.rs
sway-core/src/asm_lang/allocated_ops.rs
sway-core/src/asm_lang/virtual_immediate.rs
sway-core/src/asm_lang/virtual_ops.rs

Do not allow inline `VirtualImmediate`* instantiations

---

.github/workflows/ci.yml
.github/workflows/gh-pages.yml
.github/workflows/scripts/verify_tag.sh
Cargo.toml

The github-pages CI action has been [failing](https://github.com/FuelLabs/sway/actions/runs/12867769693/job/35873104739) since the forc-migrate PR was merged, because the plugin needs to be installed in that workflow.
It was also missing from forc-binaries which is needed for us to be able to distribute the binary.

fix: gh-pages CI failing due to forc-migrate

---

Cargo.toml

The `publish` job [failed](https://github.com/FuelLabs/sway/actions/runs/12918145032/job/3) as the serde feature for the `num_bigint` crate needed to be enabled.

chore: enable serde feature for num_bigint

---

forc-pkg/src/pkg.rs
sway-core/src/debug_generation/dwarf.rs

DWARF debug symbols are now automatically generated and saved as `debug_symbols.obj` in the output directory when using debug builds. This enables better debugging support out of the box in development without requiring the `-g` flag. The `-g` flag is still supported for specifying custom debug symbol output paths or generating debug symbols in other build profiles.

Auto-generate DWARF debug symbols in debug builds

---

sway-lib-std/src/vec.sw
test/src/in_language_tests/test_programs/vec_inline_tests/src/main.sw

`last()` is not implemented for `Vec`.

Add `last()` to `Vec`

---

forc-plugins/forc-debug/src/server/handlers/handle_set_breakpoints.rs
forc-plugins/forc-debug/src/server/handlers/handle_stack_trace.rs
forc-plugins/forc-debug/src/server/mod.rs
forc-plugins/forc-debug/src/server/state.rs
forc-plugins/forc-debug/src/types.rs
forc-plugins/forc-debug/tests/server_integration.rs

Replace the custom HashMap-based source map implementation in `forc-debug` with the compiler's source map format directly. This simplifies our source mapping logic and maintains better consistency with the compiler's source location tracking, while preserving all existing functionality.
Key changes:
- Remove custom source map types and use compiler's SourceMap
- Simplify breakpoint verification using compiler spans
- Add test to verify source map instruction-to-line mappings
closes #6733

Use compiler source map directly in forc-debug

---

forc-pkg/src/manifest/mod.rs

closes #6861 
`forc` was allowing dependency name being the same (through the use of `package` alias and the declaration itself) as the project name.
The following two cases are now invalid and produces an error on the forc-pkg side before going to the compiler.
```TOML
[project]
authors = ["Fuel Labs <contact@fuel.sh>"]
entry = "main.sw"
license = "Apache-2.0"
name = "lib_contract"
[dependencies]
lib_contract = { path = "../lib_contract_abi/", package = "lib_contract_abi" }
```
and
```TOML
[project]
authors = ["Fuel Labs <contact@fuel.sh>"]
entry = "main.sw"
license = "Apache-2.0"
name = "lib_contract_abi"
[dependencies]
lib_contract = { path = "../lib_contract_abi/", package = "lib_contract_abi" }
```

feat: disallow dependency package name collision in forc-pkg

---

README.md

docs: added a twitter shield

---

sway-core/src/ir_generation/const_eval.rs
sway-core/src/semantic_analysis/ast_node/expression/intrinsic_function.rs
test/src/e2e_vm_tests/test_programs/should_pass/language/const_inits/src/main.sw

This PR solves an issue with `__transmute` in "const contexts". In these cases, the "source" and "return" types were not being correctly solved.

Fix issue with `__transmute` type checking

---

sway-ast/src/expr/op_code.rs
sway-core/src/asm_lang/allocated_ops.rs
sway-core/src/asm_lang/mod.rs
sway-core/src/asm_lang/virtual_ops.rs
sway-parse/src/expr/op_code.rs
test/src/e2e_vm_tests/test_programs/should_pass/ecall/ecall_basic/Forc.lock
test/src/e2e_vm_tests/test_programs/should_pass/ecall/ecall_basic/Forc.toml
test/src/e2e_vm_tests/test_programs/should_pass/ecall/ecall_basic/src/main.sw
test/src/e2e_vm_tests/test_programs/should_pass/ecall/ecall_basic/test.toml

The ECAL opcode is supported in `fuel-vm` to extend the capabilities of the VM.
Users can implement rust code to interop with the VM using the ECAL opcode.
This PR introduces support for the opcode in the sway repo - such that sway assembly can be successfully compiled with the ECAL opcode.
Examples of how to utilize the `ECAL` opcode can be seen here: https://github.com/FuelLabs/fuel-vm/blob/9478991db1ea8799fab47ebe1c195946a2698a7f/fuel-vm/examples/external.rs#L51
- Closes https://github.com/FuelLabs/sway/issues/5239
- Added an e2e test to validate compilation of ecall opcode in sway assembly.

ECAL opcode support

---

sway-core/src/language/ty/code_block.rs
sway-core/src/language/ty/expression/expression.rs
sway-lib-std/src/ecr.sw
sway-lib-std/src/vm/evm/ecr.sw
test/src/e2e_vm_tests/test_programs/should_pass/language/deprecated/src/main.sw
test/src/e2e_vm_tests/test_programs/should_pass/language/deprecated/test.toml

Add support for the `#[deprecated]` attribute to functions, enums, struct items, enum variants and propagate deprecation check exhaustively throughout expressions variants.
Partially addresses #6942.
Support for deprecating traits, abis and the methods thereof in their definitions is still missing, as well as scrutinees and storage fields.

Extend `#[deprecated]` support

---

sway-core/src/asm_generation/fuel/checks.rs
test/src/e2e_vm_tests/test_programs/should_fail/predicate_invalid_opcodes/src/main.sw
test/src/e2e_vm_tests/test_programs/should_fail/predicate_invalid_opcodes/test.toml
test/src/e2e_vm_tests/test_programs/should_pass/language/asm/instructions/ldc/Forc.lock
test/src/e2e_vm_tests/test_programs/should_pass/language/asm/instructions/ldc/Forc.toml
test/src/e2e_vm_tests/test_programs/should_pass/language/asm/instructions/ldc/src/main.sw
test/src/e2e_vm_tests/test_programs/should_pass/language/asm/instructions/ldc/test.toml

This PR allows `LDC` opcode in predicates. Historically, it was not allowed in the FuelVM, but this restriction is removed and we are removing it now from Sway as well.

Allow `ldc` opcode in predicates

---

docs/book/src/forc/manifest_reference.md
forc-pkg/src/manifest/mod.rs

Related https://github.com/FuelLabs/forc.pub/issues/30

feat: Support categories and keywords in forc manifest

---

forc-plugins/forc-migrate/src/migrations/mod.rs
forc-plugins/forc-migrate/src/migrations/try_from_bytes_for_b256.rs

This PR adds migration step for migrating `<bytes>.into()` calls to `<bytes>.try_into().unwrap`, as explained in the Breaking Changes chapter of #6994.

Add migration for `Bytes::into(self) -> b256` to `Bytes::try_into`

---

sway-features/Cargo.toml

The sway-features Cargo.toml had dependencies not aligned with the
workspace which prevented the publish action to run properly.

Fix source dependencies preventing release

---

test/Cargo.toml
test/src/e2e_vm_tests/mod.rs
test/src/main.rs
test/src/snapshot/mod.rs

This PR improves snapshot testing by moving the snapshot testing infrastructure from the separate `tests` project inside of the `e2e_vm_tests`.
This solves the following issues:
- double test execution on CI. Snapshot tests were executed twice on the CI, once as as part of `cargo_run_e2e_tests` and once as a part of `cargo_test_workspace`.
- double compilation. When running `e2e_vm_tests`, snapshot tests were executed as a separate process. In the recent issue with recompiling crates, this has caused the crates to be recompiled twice, starting from the `ring` crate.
- access to `reduced_std_libs`. Snapshot tests also need access to `reduced_std_libs`. Until now, they dependent only on `core` and full-blown `std`, but now they also depend on `sway-lib-std-core` which is generated when …

Improve snapshot testing

---

docs/book/src/forc/plugins/forc_client/forc_call.md
forc-plugins/forc-client/src/cmd/call.rs
forc-plugins/forc-client/src/op/call/list_functions.rs
forc-plugins/forc-client/src/op/call/mod.rs
forc-plugins/forc-client/src/op/call/parser.rs

Adds optional `--list-functions` CLI arg to `forc call`.
With provided ABI and a contract address; calling `forc-call` with `--list-functions` will list all available functions in the contract and additionally display example CLI usage to call the respective functions with default/basic parameters.
```sh
> forc call -- \               
--abi ./forc-plugins/forc-client/test/data/contract_with_types/contract_with_types-abi.json \
23190a0648a92ac42f58dc2f4159ee28cdd1448bbcaabd272ec42a00e8e4aed4 --list-functions
Available functions in contract: 23190a0648a92ac42f58dc2f4159ee28cdd1448bbcaabd272ec42a00e8e4aed4
test_array(a: [u64; 10]) -> [u64; 10]
forc call \
--abi ./forc-plugins/forc-client/test/data/contract_with_types/contract_with_types-abi.json \ …
```

forc-call list functions support with example call usage

---

sway-error/src/lex_error.rs
sway-parse/src/token.rs
test/src/e2e_vm_tests/test_programs/should_fail/u256/u256_only_hex_literal/Forc.lock
test/src/e2e_vm_tests/test_programs/should_fail/u256/u256_only_hex_literal/Forc.toml
test/src/e2e_vm_tests/test_programs/should_fail/u256/u256_only_hex_literal/src/main.sw
test/src/e2e_vm_tests/test_programs/should_fail/u256/u256_only_hex_literal/test.toml
test/src/e2e_vm_tests/test_programs/should_pass/language/u256/u256_operators/src/main.sw

This PR removes the constraint on `u256` literals being only expressed in hexadecimal.
The constraint has been removed and the code slightly refactored to remove the unnecessary `radix` variable in the `lex_int_lit` function in `token.rs`.
The corresponding error `LexErrorKind::U256NotInHex` has been removed from the codebasen as well as the `should_fail` test looking to raise this error.
The u256 testing suite has been augmented with additional tests to make sure we can express u256 literals in decimal, binary and octal.
Closes #5456

Allow decimal/binary/octal u256 literals

---

Cargo.lock
Cargo.toml
forc-util/Cargo.toml
forc-util/src/fs_locking.rs

adds the mark-flaky-tests crate so we can use `#[flaky]` above tests that might fail. Also improves the `test_cleanup_stale_files` test which was added in #6816

chore: improve `test_cleanup_stale_files` test & add `mark-flaky-tests` crate

---

.github/workflows/benchmark.yml

The default ubuntu runners are too limited to run the codspeed benchmarks, this PR moves the benchmarks over to buildjet

move codspeed benchmarks to buildjet

---

Cargo.lock
forc-plugins/forc-publish/Cargo.toml
forc-plugins/forc-publish/src/tarball.rs

close #7063.
`forc-publish` tarball tests are setting the current working director with `env::set_current_dir`. One thing to note here is `env` module is changing things for the whole process. Here is the [docs](https://doc.rust-lang.org/std/env/index.html):
> Inspection and manipulation of the process’s environment.
So setting `env::set_current_dir` changes the current dir on all threads. By default cargo runs tests in parallel using multiple threads in a single process. This means, tarball tests are racing with each other and changing each other's working directory making the tests flaky.

fix: run forc-publish tarball tests sequentially to remove flakiness

---

.github/workflows/ci.yml

Adds forc-node binary (introduced in #6473 ) to the sway repo releases.

ci: include forc-node binaries in releases

---

forc-plugins/forc-client/src/cmd/call.rs
forc-plugins/forc-client/src/op/call/call_function.rs
forc-plugins/forc-client/src/op/call/mod.rs
forc-plugins/forc-client/src/op/call/transfer.rs

- Introduces verbosity levels for the `forc-call` command, replacing the `show-receipts` flag
- Inspired by [`forge test` verbosity levels](https://book.getfoundry.sh/reference/forge/forge-test#evm-options); i.e. can specify `-v=1` or `-vv`, etc.
- Verbosity `v1` prints the following additional info:
- logs
- Verbosity `v2` prints the following additional info:
- receipts
- script json (`tx.json`)
Note: The `tx.json` printed in the response can be used by `forc-debug` to debug the transaction
^ Addresses: https://github.com/FuelLabs/sway/issues/7019

forc call verbosity levels

---

forc-pkg/src/source/reg/file_location.rs
forc-pkg/src/source/reg/index_file.rs
forc-pkg/src/source/reg/mod.rs

closes #7077.
Adds support for yanked packages. Forc will handle yanked packages by not accepting the version, and listing other possible versions.
Also adds other possible versions in the error message if the version requested is something that does not exists.

feat: yanking support for registry packages

---

sway-lib-std/src/crypto/signature.sw
test/src/in_language_tests/test_programs/crypto_ed25519_inline_tests/src/main.sw
test/src/in_language_tests/test_programs/crypto_message_inline_tests/src/main.sw
test/src/in_language_tests/test_programs/crypto_point2d_inline_tests/src/main.sw
test/src/in_language_tests/test_programs/crypto_public_key_inline_tests/src/main.sw
test/src/in_language_tests/test_programs/crypto_scalar_inline_tests/src/main.sw
test/src/in_language_tests/test_programs/crypto_secp256k1_inline_tests/src/main.sw
test/src/in_language_tests/test_programs/crypto_secp256r1_inline_tests/src/main.sw
test/src/in_language_tests/test_programs/crypto_signature_inline_tests/src/main.sw

This PR implement `Eq` and `PartialEq` for `Signature` and adds missing `AbiEncode` and `AbiDecode` tests for the crypto module.

Implement `Eq` for `Signature` and add missing `codec` tests

---

sway-lib-std/src/tx.sw

This PR optimizes functions in the `tx` module for bytecode size and gas usage. E.g., the bytecode size of the following script that calls all of the optimized functions got **reduced from 1792 bytes to 648 bytes**:
```sway
fn main() {
let _ = std::tx::tx_script_length();
let _ = std::tx::tx_script_data_length();
let _ = std::tx::tx_script_data::<u64>();
let _ = std::tx::tx_script_bytecode::<u64>();
let _ = std::tx::tx_script_bytecode_hash();
let _ = std::tx::tx_witnesses_count();
let _ = std::tx::tx_witness_data::<u64>(0);
}
```
The optimization:
- mostly removes the duplicated checks for `tx_type()` and where necessary, replaces calls to `tx_type()` to a single `if`.
- removes the private helper function `tx_script_start_pointer`. The function was re-checking the `tx_type()` to be a …

Optimize `tx` module for bytecode size and gas usage

---

sway-lib-std/src/inputs.sw
sway-lib-std/src/outputs.sw
sway-lib-std/src/tx.sw
test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/asset_ops_test/src/main.sw
test/src/sdk-harness/test_artifacts/tx_output_contract/src/main.sw
test/src/sdk-harness/test_artifacts/tx_output_predicate/src/main.sw
test/src/sdk-harness/test_projects/auth/mod.rs

This PR optimizes the `std::inputs` and `std::outputs` modules for bytcode size and gas cost using the same optimization techinques like in #7087.
The optimized public functions are listed in the below code snippet. **The bytcode size of that code got reduced from 5688 bytes to 2544 bytes.**
```sway
fn main() {
let _ = std::tx::tx_witnesses_count();
let _ = std::inputs::input_count();
let _ = std::inputs::input_amount(0);
let _ = std::inputs::input_coin_owner(0);
let _ = std::inputs::input_predicate_data::<u64>(0);
let _ = std::inputs::input_asset_id(0);
let _ = std::inputs::input_witness_index(0);
let _ = std::inputs::input_predicate_length(0);
let _ = std::inputs::input_predicate(0);
let _ = std::inputs::input_predicate_data_length(0);
let _ = std::inputs::input_message_sender(0);
let _ …
```

Optimize `inputs` and `outputs` modules for bytecode size and gas usage

---

forc-pkg/src/source/reg/file_location.rs

Limits the levels of nesting to 2 for registry sources. Changes the naming convention for the index files from unlimited amount of nesting by `chunk_size` to only 2 levels of nesting with `chunk_size`.
So `foobar` was split as `fo/ob/ar/foobar` with `chunk_size` 2 but with this PR it is split as `fo/ob/foobar`.

feat: limit registry nesting to 2 levels for registry sources

---

.github/workflows/ci.yml

`build-and-release-forc-binaries` step failed in the last release because it was using an old OS version (20.04). The details can be seen [here](https://github.com/FuelLabs/sway/actions/runs/14605196507/job/40975381937) and [here](https://github.com/actions/runner-images/issues/11101).

ci: move build binaries step to ubuntu-22.04

---

Cargo.lock
Cargo.toml

Release of 0.67.2 failed due to a CI issue fixed in #7099. This release of 0.67.2 is to replace invalid release of 0.67.1

chore: bump to 0.67.2

---

.github/workflows/ci.yml

This PR fixes the CI pipeline failures caused by GitHub's deprecation of their legacy caching service.
Our CI was failing with the error:
```
ERROR: This legacy service is shutting down, effective April 15, 2025. Migrate to the new service ASAP. For more information: https://gh.io/gha-cache-sunset
```
This was caused by our use of `docker/build-push-action@v2` which relies on the legacy GitHub Actions caching service that's being deprecated.
* Updated docker/build-push-action from v2 to v6 to use the new caching service
* Updated related Docker actions for compatibility
* docker/metadata-action from v3 to v5
* docker/setup-buildx-action from v1 to v3
* docker/login-action from v1 to v3
* Merged changes from external contributor to update actions/checkout from v3 to v4 for Node 20 …

fix(ci): update Docker actions to fix GitHub cache deprecation error

---

sway-lib-std/src/assert.sw

This PR changes the trait constraints on `assert_eq` and `assert_ne` from `Eq` to `PartialEq`. The `Eq` requirement was unnecessary strong, and is actually a "leftover" from the original implementation, before we introduced `PartialEq`.

`assert_eq` requires `PartialEq` instead of `Eq`

---

sway-lib-std/src/vec.sw

Fixes a mistake where an `Eq` constraint was used where a `PartialEq` suffixes.

Fix `Eq` constraint in vec.sw `impl<T> PartialEq for Vec<T>`.

---

Cargo.lock
Cargo.toml

Bumps the version to 0.68.1 to get a release with fuel-core v0.43.1 support.
Waiting on:

chore: bump version to 0.68.1

---

sway-lsp/tests/fixtures/workspace/test-contract/Forc.toml
sway-lsp/tests/fixtures/workspace/test-library/Forc.toml

The `sync_with_updates_to_manifest_in_workspace` test [was failing](https://github.com/FuelLabs/sway/actions/runs/14633300994/job/41059472756?pr=7112) because I forgot to specify `implicit-std = false` in the `Forc.toml` which meant it was trying to fetch when it shouldn't have.

fix: add `implicit-std = false` to fix failing LSP test

---

forc-plugins/forc-client/src/op/call/call_function.rs
forc-plugins/forc-client/src/op/call/missing_contracts.rs

Using `fuels-rs` SDK to retrieve missing contracts for a forc-call query.
This function/improvement was introduced in the `fuels-rs` sdk here: https://github.com/FuelLabs/fuels-rs/pull/1628
Addresses: https://github.com/FuelLabs/sway/issues/7113

forc-call: missing contract retrieval refactor

---

test/update-contract-ids.sh

Currently update-contract-ids.sh cannot be run on any recent macOS installation, as the system-provided grep and sed are incompatible with the linux-specific options used. The GNU versions of these are available through homebrew, so it would be nice to use those. Unfortunately, those are installed with `g` prefix, so the binaries are named `gsed` and `ggrep`. This PR changes the script to prefer these `g`-prefixed commands, making the script work on macOS as well.
I tested this on a recent clean Ubuntu install, as well as latest macOS, and it works on both.

Make update-contract-ids.sh macOS-compatible

---

sway-lsp/src/core/session.rs

Fix #7144
way-lsp contains a possible double read-lock bug.
The lock is a parking_lot::RwLock:
The first read lock is on L227 in completion_items
The second read lock is on L235 in completion_items
https://github.com/FuelLabs/sway/blob/324f04fbab358a8e7eb729d03e0293605755ba5a/sway-lsp/src/core/session.rs#L227-L235
The solution is to remove the redundant second read lock
After the fix, the possible double read-lock will be eliminated, and the performance may be better.

sway-lsp: Fix the double read-lock bug in session

---

sway-lsp/src/utils/keyword_docs.rs

As the title says.
There's a corresponding PR in the vscode plugin for correct syntax highlighting when hovering over the `abi` keyword here https://github.com/FuelLabs/sway-vscode-plugin/pull/193

Add documentation for the `abi` keyword for LSP

---

Cargo.lock
Cargo.toml
sway-lsp/Cargo.toml
sway-lsp/src/core/session.rs
sway-lsp/src/core/sync.rs
sway-lsp/src/error.rs
sway-lsp/src/handlers/notification.rs
sway-lsp/src/handlers/request.rs
sway-lsp/src/server.rs
sway-lsp/src/server_state.rs
sway-lsp/tests/integration/lsp.rs
sway-lsp/tests/lib.rs

This PR replaces our custom Tokio-based thread watcher for `Forc.toml` files with the built-in LSP `didChangeWatchedFiles` notification system. The changes:
* Remove the Tokio thread-based file watching system and associated cleanup code
* Implement client-side file watching registration during initialization
* Handle `Forc.toml` file changes through the LSP notification protocol
* Update tests to use the new notification system
* Simplify manifest syncing with a direct approach
This approach is more efficient as it leverages the client's native file watching capabilities rather than spawning a separate thread. The PR maintains the same functionality while reducing resource usage and complexity.
Note: This doesn't yet implement the recompilation on `Forc.toml` changes as mentioned in …

Replace Tokio Thread File Watcher with LSP Client File Watcher

---

.github/workflows/ci.yml
forc-plugins/forc-publish/README.md
forc-plugins/forc-publish/src/credentials.rs

Related https://github.com/FuelLabs/sway/issues/7040
Publish sway `std` library to https://forc.pub/ when a release is created.

ci: publish lib-std on release

---

forc-plugins/forc-client/tests/deploy.rs
forc/tests/cli_integration.rs
sway-core/src/ir_generation/compile.rs
sway-ir/src/printer.rs
test/src/e2e_vm_tests/test_programs/should_pass/language/attributes_deprecated/stdout.snap
test/src/e2e_vm_tests/test_programs/should_pass/language/panic_expression/panicking_contract/stdout.snap
test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/array_of_structs_caller/src/main.sw
test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/asset_ops_test/src/main.sw
test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/bal_opcode/src/main.sw
test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/call_basic_storage/src/main.sw
test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/call_contract_with_type_aliases/src/main.sw
test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/call_increment_contract/src/main.sw
test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/caller_context_test/src/main.sw
test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/storage_access_caller/src/main.sw

This PR removes the double compilation of contract methods in the IR, in the case of new encoding.
The contract methods were first compiled as a part of the compilation of the `__entry` function, and afterwards, again separately. The contract methods compiled in the second compilation pass were later on removed as not reachable.
The issue was brought to the surface in a test written by @hal3e in [fuel-rs PR that integrates ABI errors](https://github.com/FuelLabs/fuels-rs/pull/1651). In that particular test, because of the double compilation, a `panic` expression in a contract method got compiled twice and produced two same entries in the ABI JSON.
Removing the double compilation resulted in a small reduction of bytecode size and gas usage. In some tests bytecode size got reduced for ~50 …

Remove double IR-compilation of contract methods

---

examples/arrays/Forc.toml
examples/arrays/src/main.sw
sway-core/src/semantic_analysis/namespace/package.rs
sway-lsp/benches/lsp_benchmarks/compile.rs
sway-lsp/benches/lsp_benchmarks/mod.rs
sway-lsp/benches/lsp_benchmarks/requests.rs
sway-lsp/benches/lsp_benchmarks/token_map.rs
sway-lsp/src/capabilities/hover/hover_link_contents.rs
sway-lsp/src/capabilities/hover/mod.rs
sway-lsp/src/capabilities/rename.rs
sway-lsp/src/core/document.rs
sway-lsp/src/core/mod.rs
sway-lsp/src/core/session.rs
sway-lsp/src/core/sync.rs
sway-lsp/src/error.rs
sway-lsp/src/handlers/notification.rs
sway-lsp/src/handlers/request.rs
sway-lsp/src/lib.rs
sway-lsp/src/server.rs
sway-lsp/src/server_state.rs
sway-lsp/tests/fixtures/diagnostics/dead_code/Forc.toml
sway-lsp/tests/fixtures/diagnostics/multi_file/Forc.toml
sway-lsp/tests/integration/lsp.rs
sway-lsp/tests/lib.rs
sway-lsp/tests/utils/src/lib.rs

* Moves `SyncWorkspace` ownership from individual `Session` instances to a single, global instance within `ServerState`.
* `SyncWorkspace` is now initialized once when the LSP server starts, creating a single temporary workspace clone.
Also removes the `resync` function. This was causing the server and the IDE to fall out of sync with each other. For example, if you have 2 panels open and then save a file in one of the tabs but have unsaved changes in the other tab then those changes would not be reflected in the temp memory folder. This meant everything would be out of sync. We already are syncing everything on each keystroke per file so this fn was not necessary in the first place.
This PR is a precursor to https://github.com/FuelLabs/sway/pull/7139
part of …

Refactor: Move `SyncWorkspace` from `Session` into `ServerState`

---

sway-lsp/src/capabilities/semantic_tokens.rs
sway-lsp/tests/lib.rs
sway-lsp/tests/utils/src/lib.rs

Previously, the language server would panic if it encountered a `SymbolKind` that mapped to a `SemanticTokenType` not present in the `SUPPORTED_TYPES` array. This was due to an `unwrap()` call in the `type_index` function.
This PR addresses the issue by:
Adding `SemanticTokenType::new("traitType")` to the `SUPPORTED_TYPES` array, which was the specific missing type causing a crash when opening `sway-lib-std/src/iterator.sw`.
Modifying `type_index` to return `Option<u32>` instead of `u32`, removing the `unwrap()`.
closes #7188

fix: Prevent panic in semantic highlighting for unknown token types

---

sway-lsp/src/core/session.rs

Check for typed program errors before unwrapping to prevent panics.

---

sway-core/src/ir_generation.rs
sway-core/src/ir_generation/function.rs
sway-core/src/language/ty/declaration/function.rs
sway-core/src/semantic_analysis/ast_node/declaration/function.rs
sway-core/src/semantic_analysis/ast_node/expression/typed_expression/function_application.rs
sway-core/src/semantic_analysis/ast_node/expression/typed_expression/struct_instantiation.rs
sway-core/src/transform/to_parsed_lang/convert_parse_tree.rs
sway-core/src/type_system/ast_elements/binding.rs
sway-core/src/type_system/ast_elements/type_parameter.rs
sway-lsp/tests/lib.rs
test/src/e2e_vm_tests/test_programs/should_pass/language/const_generics/json_abi_oracle.json
test/src/e2e_vm_tests/test_programs/should_pass/language/const_generics/snapshot.toml
test/src/e2e_vm_tests/test_programs/should_pass/language/const_generics/src/main.sw
test/src/e2e_vm_tests/test_programs/should_pass/language/const_generics/stdout.snap

This PR is part of https://github.com/FuelLabs/sway/issues/6860 and allows standalone functions to have "const generics" like the code below:
```sway
fn return_n<const NNN: u64>() -> u64 {
NNN
}
```

const generics for standalone fns

---

forc-plugins/forc-node/src/consts.rs
forc-plugins/forc-node/src/ignition/op.rs

closes #7193.
There was a simple bug in the mainnet setup we were still fetching testnet configuration. Which caused some syncing issues.

fix: ensure forc-node ignition fetches ignition chain config

---

forc-plugins/forc-publish/src/error.rs

closes #7207.
Adding the underlying error message to `thiserror` impls in forc-publish so that we can debug things easier.

feat: more descriptive publish error message for forc-publish

---

sway-core/src/language/ty/expression/expression_variant.rs
sway-core/src/query_engine/mod.rs
sway-core/src/semantic_analysis/ast_node/declaration/abi.rs
sway-core/src/semantic_analysis/ast_node/declaration/impl_trait.rs
sway-core/src/semantic_analysis/ast_node/declaration/variable.rs
sway-core/src/semantic_analysis/ast_node/expression/intrinsic_function.rs
sway-core/src/semantic_analysis/ast_node/expression/match_expression/typed/matcher.rs
sway-core/src/semantic_analysis/ast_node/expression/typed_expression.rs
sway-core/src/semantic_analysis/ast_node/expression/typed_expression/enum_instantiation.rs
sway-core/src/semantic_analysis/ast_node/expression/typed_expression/function_application.rs
sway-core/src/semantic_analysis/ast_node/expression/typed_expression/if_expression.rs
sway-core/src/semantic_analysis/ast_node/expression/typed_expression/method_application.rs
sway-core/src/semantic_analysis/ast_node/expression/typed_expression/struct_instantiation.rs
sway-core/src/semantic_analysis/namespace/module.rs
sway-core/src/semantic_analysis/namespace/namespace.rs
sway-core/src/semantic_analysis/namespace/package.rs
sway-core/src/semantic_analysis/namespace/trait_coherence.rs
sway-core/src/semantic_analysis/namespace/trait_map.rs
sway-core/src/semantic_analysis/type_check_context.rs
sway-core/src/semantic_analysis/type_resolve.rs
sway-core/src/type_system/ast_elements/type_parameter.rs
sway-core/src/type_system/engine.rs
sway-core/src/type_system/mod.rs
sway-lsp/src/traverse/typed_tree.rs

This PR remove needless memory allocation:
1 - it removes needless `.clone()`, `.to_vec()` and some `.collect()`;
2 - it wraps `TraitEntry` into a `SharedTraitEntry`. In a lot of cases, `TraitEntry` was being completely cloned, and only occasionally being mutated. Now its `clone()` is cheap, and the occasional needed complete `clone` has the inconvenience of requiring `fork_if_non_unique` to be called before mutation;
3 - `err_override` was cloning a lot of stuff and only used on errors. Now they are behind a closure that is normally not called;
4 - There were a lof of needless `Vec` when dealing with modules;
5 - `find_method_for_type` and others were generating a lot of temporary `Vec`.

Removing needless allocations (clone, to_vec, collect etc...)

---

forc-plugins/forc-doc/src/render/item/type_anchor.rs
sway-core/src/abi_generation/abi_str.rs
sway-core/src/abi_generation/evm_abi.rs
sway-core/src/ir_generation/convert.rs
sway-core/src/ir_generation/function.rs
sway-core/src/language/ty/declaration/function.rs
sway-core/src/semantic_analysis/ast_node/expression/intrinsic_function.rs
sway-core/src/semantic_analysis/ast_node/expression/typed_expression/method_application.rs
sway-core/src/semantic_analysis/namespace/trait_map.rs
sway-core/src/semantic_analysis/type_check_context.rs
sway-core/src/transform/to_parsed_lang/convert_parse_tree.rs
sway-core/src/type_system/ast_elements/length.rs
sway-core/src/type_system/ast_elements/type_parameter.rs
sway-core/src/type_system/engine.rs
sway-core/src/type_system/info.rs
sway-core/src/type_system/unify/unifier.rs
sway-core/src/type_system/unify/unify_check.rs
sway-lib-std/generate.sh
sway-lib-std/src/debug.sw
sway-lib-std/src/primitives.sw
sway-lsp/src/traverse/parsed_tree.rs
sway-parse/src/item/item_impl.rs
sway-parse/src/ty/mod.rs
test/src/e2e_vm_tests/test_programs/should_pass/language/const_generics/src/main.sw
test/src/e2e_vm_tests/test_programs/should_pass/language/const_generics/stdout.snap

This PR is part of https://github.com/FuelLabs/sway/issues/6860. It implements "const generics" for "string arrays" and `len` methods for arrays and string arrays.
```sway
#[cfg(experimental_const_generics = true)]
impl<const N: u64> str[N] {
pub fn len(self) -> u64 {
N
}
}
````

Const generics for "string array" and `len` methods

---

sway-lsp/benches/lsp_benchmarks/compile.rs
sway-lsp/benches/lsp_benchmarks/mod.rs
sway-lsp/src/core/session.rs
sway-lsp/src/server_state.rs
sway-lsp/tests/lib.rs

This PR introduces selective processing to dramatically improve LSP performance when opening multiple files.
* **Conditional reprocessing**: Only perform expensive traversal operations when tokens don't exist or files have been modified
* **Selective garbage collection**: GC now only runs when files are actually modified, not on every compilation
* **Targeted token map updates**: Remove tokens only for modified files instead of clearing the entire map
* **Improved modified file tracking**: Extract modified file detection into reusable utility functions
| Test | Before | After | Improvement |
|------|--------|-------|-------------|
| did_open_all_std_lib_files | 54.96s | 3.76s | 14.6x faster |
| Time reduction | - | - | 93% decrease |
The `did_open_all_std_lib_files` test opens every file …

Optimisation: only traverse AST's if the cache is stale. 

---

docs/book/src/sway-program-types/libraries.md

Replaced the outdated GitHub link to the Binary Merkle Proof library with the up-to-date documentation link at https://docs.fuel.network/docs/sway-libs/merkle/. This ensures users have access to the latest usage instructions and examples.

Update Merkle library link to current documentation

---

forc-plugins/forc-client/src/cmd/call.rs
forc-plugins/forc-client/src/op/call/call_function.rs
forc-plugins/forc-client/src/op/call/list_functions.rs
forc-plugins/forc-client/src/op/call/mod.rs

This pull request introduces a enhancement to the ABI handling in the `forc-client` plugin by replacing the `Either<PathBuf, Url>` type with a new `AbiSource` enum.
This improves flexibility and usability by supporting ABI sources as file paths, URLs, or raw JSON strings.
Additionally, it simplifies related code and updates documentation and tests accordingly.
This represents an additional optional for callers to use forc-call with an ABI available at-hand without needing to write to a file first.

feat: forc-call inline abi support

---

forc-pkg/src/source/reg/mod.rs

---
**Description:**  
This pull request corrects a typo in the error message and related tests, changing "avaiable" to "available" for improved clarity and professionalism.

Fix Typo in Yanked Version Message

---

forc-pkg/src/manifest/build_profile.rs
forc-pkg/src/pkg.rs
forc-pkg/tests/sections/Forc.toml
sway-core/src/build_config.rs
sway-core/src/lib.rs
sway-core/src/metadata.rs

This PR adds the `backtrace` build option as described in the [ABI Backtracing RFC](https://github.com/FuelLabs/sway-rfcs/blob/ironcev/abi-backtracing/rfcs/0016-abi-backtracing.md).
This is the second step in implementing #7276.
Docs for `backtrace` build option will be added in a separate PR that will document the whole backtracking feature.

Add `backtrace` build option

---

docs/book/src/sway-program-types/libraries.md

- Replace https://github.com/FuelLabs/sway-libs/tree/master/libs/src/ownership 
with https://fuellabs.github.io/sway-libs/book/ownership/index.html

docs: fix broken sway-libs GitHub link to use official documentation URL

---

Cargo.lock
forc-plugins/forc-doc/Cargo.toml
forc-plugins/forc-doc/src/doc/descriptor.rs
forc-plugins/forc-doc/src/doc/mod.rs
forc-plugins/forc-doc/src/render/item/components.rs
forc-plugins/forc-doc/src/render/item/type_anchor.rs
forc-plugins/forc-doc/src/render/mod.rs

Key changes:
- Parallelize document rendering and link generation
- Add type aliases for complex nested types (`DocLinkMap`, `ModuleMap`, `RenderResult`)
- Remove unnecessary wrapper functions and clones
The parallel processing maintains insertion order through sequential merging, ensuring identical documentation output.
Not sure why the codspeed report isn't showing this below but when I run `cargo bench` locally i'm seeing these results.
| Metric | Before | After | Improvement |
|--------|--------|-------|-------------|
| build_std_lib_docs | 70.069 ms | 43.227 ms | **43.2% faster** |

Add parallel processing to `forc-doc` using rayon to improve performance

---

docs/book/src/sway-program-types/libraries.md

Replaced broken link https://github.com/FuelLabs/sway-libs/tree/master/libs/src/signed_integers
with the correct one https://docs.fuel.network/docs/sway-libs/signed_integers/

chore: fix broken link in libraries.md

---

Cargo.lock
docs/book/src/SUMMARY.md
docs/book/src/debugging/debugging_with_forc_call.md
forc-plugins/forc-client/Cargo.toml
forc-plugins/forc-client/src/cmd/call.rs
forc-plugins/forc-client/src/op/call/call_function.rs
forc-plugins/forc-mcp/src/forc_call/mod.rs

This PR adds interactive debugging capabilities to the `forc call` command, enabling developers to debug contract function calls step-by-step after transaction execution.
The `--debug` flag is added to the `forc call` command that launches an interactive debugging session after transaction execution.
The integration automatically handles transaction/ABI data and launches `forc-debug` for step-by-step debugging.
- New `--debug` flag in `forc call` command
- `start_debug_session()` function that creates temporary transaction/ABI files and launches the debugger
- Integration with existing `forc-debug` functionality via the `start_tx` command
```bash
forc call 0x0dcba78d7b09a1f77353f51367afd8b8ab94b5b2bb6c9437d9ba9eea47dede97 \
--abi ./contract-abi.json \
get_balance …
```

feat: forc-call debugger integration

---

sway-lib-std/src/ops.sw
test/src/in_language_tests/test_programs/ops_inline_tests/src/main.sw

Add implementation for `wrapping_add()`, `wrapping_sub()` and `wrapping_mul()` to standard operations.

Add wrapping operations to standard library

---

sway-ir/src/analysis/memory_utils.rs
test/src/e2e_vm_tests/test_programs/should_pass/language/array/array_repeat/stdout.snap
test/src/e2e_vm_tests/test_programs/should_pass/language/const_generics/stdout.snap
test/src/e2e_vm_tests/test_programs/should_pass/language/intrinsics/dbg/stdout.snap
test/src/e2e_vm_tests/test_programs/should_pass/language/panic_expression/panic_handling_in_unit_tests/stdout.snap
test/src/e2e_vm_tests/test_programs/should_pass/language/panic_expression/panicking_contract/stdout.snap
test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/call_basic_storage/src/main.sw
test/src/ir_generation/tests/global_constants_usage.sw

This PR properly treats `InstOp::GetGlobal` in the `memory_utils::get_symbols`. Before, when analysis hit `GetGlobal` as a pointer source, it didn't know that there cannot be a symbol behind that pointer. That's why it was treated the resulting `ReferredSymbols` as incomplete. This harmed `memcpyopt` optimizations.
E.g., in this example:
```sway
script;
const ADDRESS: b256 = 0x9999999999999999999999999999999999999999999999999999999999999999;
fn main() {
poke(ADDRESS);
}
#[inline(never)]
fn poke<T>(_t: T) { }
```
the resulting final IR in `release` build was:
```
entry_orig fn main_0() -> (), !13 {
local mut b256 __aggr_memcpy_0            <<<--- Additional local.
local b256 __tmp_arg
entry():
v0 = get_global __ptr b256, storage_all_layouts::ADDRESS, !14
v1 = get_local __ptr b256, …
```

Eliminate `mem_copy_val`s when accessing global constants

---

sway-core/src/lib.rs
sway-core/src/metadata.rs
sway-core/src/semantic_analysis/ast_node/expression/match_expression/typed/matcher.rs
sway-core/src/semantic_analysis/ast_node/expression/match_expression/typed/typed_match_branch.rs
sway-core/src/semantic_analysis/ast_node/expression/typed_expression.rs
sway-core/src/semantic_analysis/module.rs
sway-ir/src/analysis/memory_utils.rs

Corrected misspellings:
- `more then` → `more than`

chore: fix typos

---

forc-plugins/forc-client/src/cmd/call.rs
forc-plugins/forc-client/src/op/call/call_function.rs

Addresses https://github.com/FuelLabs/sway/issues/7366
This pull request updates how external contract addresses are handled in the call command, improving user experience and error handling.
The main changes allow:
- explicitly indicate when no external contracts should be used
- can now explicitly provide no external contracts (which prevents redundant RPC request(s)) using `--external-contracts ''`
- users to specify multiple contract IDs in a more flexible format (comma separated string)

bugfix: forc call explicit support for no external contracts

---

.github/workflows/gh-pages.yml

PR #7362 attempted to fix the std library documentation deployment but broke it completely - the site now shows a 404 error at https://fuellabs.github.io/sway/master/std/.
The issue was that CSS and JavaScript assets (`static.files/`, `search.js`) were not being deployed, causing the documentation to be unusable even when HTML pages loaded.
This fix:
1. Builds docs with `forc doc`
2. Moves `static.files/` and `search.js` into the `std/` directory
3. Updates HTML relative paths (removes `../` references)
4. Deploys the complete package to `master/std`

fix: move std library assets into docs directory to fix GitHub Pages deployment

---

README.md
justfile
scripts/bisect-forc/README.md
scripts/bisect-forc/bisect-forc.sh
scripts/compare-gas-usage/extract-gas-usage.sh
scripts/compare-gas-usage/generate-diff.sh
test/src/e2e_vm_tests/mod.rs
test/src/main.rs

This PR brings all the scripts that we have, and push a couple more into one `just` file (https://github.com/casey/just).
Initially we are just calling the script directly, but we can improve it later.

One `justfile` to run them all

---

forc-plugins/forc-debug/src/error.rs
forc-plugins/forc-doc/src/doc/descriptor.rs
sway-ast/src/expr/mod.rs
sway-ast/src/item/item_impl.rs
sway-ast/src/item/item_trait.rs
sway-ast/src/path.rs
sway-core/src/asm_generation/abi.rs
sway-core/src/asm_generation/fuel/optimizations/constant_propagate.rs
sway-core/src/language/parsed/declaration/storage.rs
sway-core/src/language/ty/ast_node.rs
sway-core/src/language/ty/expression/scrutinee.rs
sway-core/src/lib.rs
sway-core/src/semantic_analysis/ast_node/expression/match_expression/typed/matcher.rs
sway-core/src/semantic_analysis/program.rs
sway-core/src/type_system/id.rs
sway-lib-std/src/iterator.sw
sway-lsp/src/core/token.rs

Continuation of https://github.com/FuelLabs/sway/issues/6860.
This PR implements `Iterator` trait for arrays, which allows codes like below:
```sway
let array: [u64; 3] = [1u64, 2u64, 3u64];
let mut value = 0;
for v in array.iter() {
value += v;
}
assert(value == 6);
```
PS: `#allow` and some unrelated changes demanded by `clippy`.

Iterator trait for arrays

---

sway-core/src/transform/to_parsed_lang/convert_parse_tree.rs
sway-error/src/convert_parse_tree_error.rs

This PR removes the `ConvertParseThreeError::SelfImplForContract` and the unreachable code branch that was emiting it.
#7275 introduces self impls for contracts and transforms every `impl Contract` into `impl <GeneratedAbiName> for Contract` which makes the `SelfImplForContract` error obsolete and the `match` arm that was emitting it unreachable.

Remove emitting of `ConvertParseThreeError::SelfImplForContract`

---

Cargo.lock
forc-pkg/Cargo.toml
forc-pkg/src/source/reg/mod.rs

closes #7376 and TOOL-681
**Problem**: When registry package fetching fails, the created directory remains in ~/.forc/registry/, causing subsequent builds to fail because forc assumes the directory contains a valid package.
To mitigate this:
- *Moved directory creation:* Directory creation now happens after validating the package exists in the registry index.
- *Added cleanup guard*: Used scopeguard::guard to ensure automatic cleanup if fetch fails.
- *Implemented proper error handling*: On successful fetch, the guard is defused; on failure, the directory is automatically removed.
-  `test_fetch_directory_cleanup_on_failure` validates that failed fetches properly clean up directories

feat: improved reliability for failing fetches through forc-pkg

---

.github/workflows/ci.yml

Point `cargo-unused-deps-check` at `nightly-2025-08-15`, which ships rustc 1.88 so `cargo-udeps` and its cargo dependencies install cleanly. This should fix the currently [failing](https://github.com/FuelLabs/sway/actions/runs/17906778883/job/50909289626?pr=7399) job.

Update nightly toolchain for cargo-udeps CI job

---

docs/book/spell-check-custom-words.txt
docs/book/src/SUMMARY.md
docs/book/src/forc/manifest_reference.md
docs/book/src/reference/attributes.md
docs/book/src/reference/experimental_features.md
docs/book/src/reference/index.md

This PR adds "Experimental Features" chapter to The Sway Book.
#7256 will likely create need for some developers to actively use experimental features as a part of their project configurations, or CI. It was already reported that it's unclear how to add experimental features in the `Forc.toml`, and the [RFC chapter on enabling features in Sway](https://github.com/FuelLabs/sway-rfcs/blob/master/rfcs/0013-changes-lifecycle.md#enabling-features-on-sway) is unfortunately outdated. Also, some of the possibilities listed in the RFC are currently not implemented, like, e.g., the meta token for enabling and disabling all experimental features.
This PR documents the actually implemented way of using experimental features.
Additionally, it fixes the index page of the "Sway Reference" chapter, by …

Add "Experimental Features" chapter to The Sway Book

---

.github/workflows/ci.yml
.github/workflows/gh-pages.yml

Using larger Actions runners for the GitHub pages and Sway publish steps due to disk size limitations on the standard runners.

fix: change runners for publish workflows

---

Cargo.lock
Cargo.toml
forc-plugins/forc-publish/src/main.rs
forc-tracing/Cargo.toml
forc-tracing/src/lib.rs
forc-tracing/src/telemetry.rs
forc/Cargo.toml
forc/src/cli/mod.rs
test/src/e2e_vm_tests/test_programs/should_pass/language/array/array_repeat/stdout.snap

This adds `fuel-telemetry` to `forc-tracing` with **opt-out functionality** for upstream tools like fuelup.
First, add it to the `forc-tracing` dependency:
```toml
[dependencies]
forc-tracing = { version = "0.47", features = ["telemetry"] }
```
Then use the `telemetry::*` glob, followed by the usual `tracing` macros, but with a `_telemetry` postfix:
```rust
use forc_tracing::{
init_tracing_subscriber, println_green, println_red, println_yellow, telemetry::*,
};
fn main() {
init_tracing_subscriber(Default::default());
println_red("Stop");
println_yellow("Slow down");
println_green("Go");
error_telemetry!("Error message for InfluxDB");
warn_telemetry!("Warn message for InfluxDB");
info_telemetry!("Info message for InfluxDB");
debug_telemetry!("Debug message for InfluxDB"); …
```

feat: introduce fuel-telemetry macros

---

sway-lib-std/src/hash.sw
test/src/e2e_vm_tests/test_programs/should_pass/language/configurable_consts/json_abi_oracle_new_encoding.json
test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/call_basic_storage/src/main.sw
test/src/in_language_tests/test_programs/hash_inline_tests/src/main.sw

This PR removes workarounds based on `asm` blocks used in the `std::hash` module to obtain an address of a copy-type. Those workarounds are replaced with `__addr_of` which since #7255 supports taking addresses of copy-types.

Remove workarounds based on `asm` blocks from `std::hash`
