sway-server/src/utils/common.rs
Fixes a display bug identified over slack.
=> Fix display bug.

Cargo.lock, test/src/e2e_vm_tests/mod.rs
=> print out filtered tests; warn if no tests run

.github/workflows/ci.yml
=> Add publish delay to CI

.github/workflows/ci.yml
Tag release images with proper version tags
=> Add semver tagging for release image

sway-server/src/capabilities/file_sync.rs, sway-server/src/core/session.rs
=> lsp: handle file deletion

test/src/e2e_vm_tests/mod.rs
=> Fix bug with reporting number of tests run.

forc/README.md
Remove unmaintained usage documentation, and clean up remaining.
=> Clean up Forc readme.

Cargo.lock, forc/Cargo.toml, parser/Cargo.toml, sway-core/Cargo.toml, sway-fmt/Cargo.toml, sway-ir/Cargo.toml, sway-server/Cargo.toml, sway-types/Cargo.toml, sway-utils/Cargo.toml, test/Cargo.toml
Skipping v0.3.2 since I erroneously published that without bumping.
=> bump to v0.3.3

.github/workflows/ci.yml
=> ci: build with all features

test/src/e2e_vm_tests/test_programs/address_test/Forc.toml, test/src/e2e_vm_tests/test_programs/test_fuel_coin_abi/Forc.toml, test/src/e2e_vm_tests/test_programs/test_fuel_coin_abi/src/main.sw, test/src/e2e_vm_tests/test_programs/test_fuel_coin_contract/Forc.toml, test/src/e2e_vm_tests/test_programs/test_fuel_coin_contract/src/main.sw, test/src/e2e_vm_tests/test_programs/token_ops_test/Forc.toml, test/src/e2e_vm_tests/test_programs/token_ops_test/src/main.sw
The tests for this PR: https://github.com/FuelLabs/sway-lib-std/pull/27
=> Adding tests for force_transfer function.

docs/src/getting-started/forc_project.md
quite possibly the smallest PR i've ever done :)
=> fix misspelled cargo in docs

deployment/Dockerfile
Fix failing master branch by using latest version of rust.
=> update to latest rust docker image

Cargo.lock
#760 missed bumping the lockfile.
=> Bump lockfile internal deps to v0.4.0.

forc/src/ops/forc_explorer.rs
=> Make forc explorer print out a valid URL.

sway-core/src/error.rs, sway-core/src/lib.rs
=> fix: prevent panic when parsing empty string

sway-core/src/parse_tree/declaration/impl_trait.rs
Tiny fix. Closes https://github.com/FuelLabs/sway/issues/833
=> Fix panic on empty trait impl

.gitignore, .vscode/settings.json
User-specific ignores should be put in `.git/info/exclude`.
=> Remove `.vscode`

.github/workflows/ci.yml, sway-core/src/asm_generation/from_ir.rs, sway-core/src/optimize.rs, sway-ir/tests/tests.rs
Let's see if this will appease clippy
=> Address seemingly new clippy nits that block unrelated PRs

forc/src/cli/mod.rs
=> Add --version to Forc

examples/hello_world/src/main.sw, examples/subcurrency/src/main.sw, examples/wallet_smart_contract/src/main.sw
Update for new syntax introduced in #859
=> Remove forced args for example contracts.

forc-pkg/src/pkg.rs
This closes #915 by implementing the solution mentioned there.
=> Fix concurrent `forc` updates/builds with a unique `fetch_id`

Cargo.lock, forc-pkg/Cargo.toml, forc-util/Cargo.toml, forc/Cargo.toml, parser/Cargo.toml, sway-core/Cargo.toml, sway-fmt/Cargo.toml, sway-ir/Cargo.toml, sway-lsp/Cargo.toml, sway-types/Cargo.toml, sway-utils/Cargo.toml, test/Cargo.toml
=> Bump to v0.6.1

docs/src/reference/temporary_workarounds.md, docs/src/sway-on-chain/smart_contracts.md
closes: https://github.com/FuelLabs/sway/issues/898
=> Additional updates to the Sway book regarding the new contract call syntax

docs/src/SUMMARY.md, docs/src/basics/index.md
Commenting out the reference type guide until we have more clarity on whether reference types will be supported
=> Comment out reference type section for now

examples/counter/src/main.sw, test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/call_increment_contract/Forc.lock, test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/call_increment_contract/Forc.toml, test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/call_increment_contract/src/main.sw, test/src/e2e_vm_tests/test_programs/should_pass/test_abis/increment_abi/src/main.sw, test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/basic_storage/src/main.sw, test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/increment_contract/Forc.lock, test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/increment_contract/Forc.toml, test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/increment_contract/src/main.sw
Fixing the contract that we include in the Sway book as well as the E2E test.
=> Fix incrementor test

forc-pkg/Cargo.toml, forc-pkg/src/manifest.rs, forc/src/ops/forc_init.rs
=> Remove author manifest field.

forc/src/cli/commands/run.rs, forc/src/ops/forc_run.rs, forc/src/utils/mod.rs, forc/src/utils/parameters.rs
=> Add forc run tx parameters.

sway-core/src/parse_tree/declaration/trait.rs, sway-lsp/src/core/token.rs
Addressing 2 TODOs left by Elvis, @leviathanbeak was there a reason why you posed these TODOs as questions?
=> Handle parsing tokens within FunctionApplication and TraitDeclaration

forc/src/utils/defaults.rs
=> Change default stdlib to point to this repo.

docs/src/examples/subcurrency.md
Added a small explanation for subcurrency.
=> Subcurrency Explanation

forc/src/cli/commands/test.rs
This allows for forwarding both custom options and custom arguments
through to `forc test`'s underlying `cargo test` invocation.
See the documentation for the new `test::Command` fields for
information on how to forward options and arguments.
This also removes the permanent "--nocapture" arg that we previously
passed through to `cargo test` in favour of allowing the user to
optionally specify it if they wish.
To achieve the original behaviour, you can invoke `forc test` with the
following:
```
forc test -- --nocapture
```
Note that this PR *does* keep the original behaviour of permanently
setting `--color always` in order to provide nice colorful output by
default. This is useful as cargo appears to disable colored output by
default when run as a child process.
In the case that the user …
=> Allow forwarding options and arguments from `forc test` to `cargo test`

sway-core/src/sway.pest
=> Added optional trailing `,` to `use` statements in `sway-pest`

docs/src/introduction/installation.md
- 1.58 version specified
- And update instructions
Related: https://github.com/FuelLabs/sway/issues/1240
=> Specify Rust version in install docs

forc-pkg/src/pkg.rs
This fixes a bug where removing a path dependency (e.g. core) from the
manifest where that dependency is shared by another dependency (e.g.
std) could cause path map reconstruction to fail.
Previously, we assumed that the dependency would be present within the
manifest in order to retrieve the source path. This PR removes this
assumption and will instead reconstruct the dependency graph (and in
turn the lock file) when a dependency is discovered to be missing during
path reconstruction.
First spotted by @nfurfaro [here][1].
[1]: https://github.com/FuelLabs/sway/pull/1276/files#r853131667
=> Handle removed dep in manifest during path reconstruction from graph

docs/src/introduction/installation.md
- Added some details around installing available forc plugins and how it works.
=> forc plugins

docs/src/forc/index.md
- Make forc docs more welcoming for those coming from crates.io
- Format the commands link with some context
=> Make Forc docs nicer

test/src/sdk-harness/README.md
Updated the location of the build script and linked to the docs for `forc test`
=> Update readme for stdlib tests

forc-fmt/src/main.rs
=> Add --path to forc fmt.

sway-core/src/constants.rs, sway-core/src/error.rs, sway-core/src/lib.rs, sway-core/src/semantic_analysis/ast_node/declaration/function.rs, sway-core/src/semantic_analysis/ast_node/expression/typed_expression.rs, sway-core/src/semantic_analysis/ast_node/mod.rs, sway-core/src/semantic_analysis/syntax_tree.rs, sway-core/src/type_engine.rs, sway-core/src/type_engine/unresolved_type_check.rs, test/src/e2e_vm_tests/mod.rs, test/src/e2e_vm_tests/test_programs/should_fail/contract_pure_calls_impure/Forc.lock, test/src/e2e_vm_tests/test_programs/should_fail/different_contract_caller_types/Forc.lock, test/src/e2e_vm_tests/test_programs/should_fail/insufficient_type_info/.gitignore, test/src/e2e_vm_tests/test_programs/should_fail/insufficient_type_info/Forc.lock, test/src/e2e_vm_tests/test_programs/should_fail/insufficient_type_info/Forc.toml, test/src/e2e_vm_tests/test_programs/should_fail/insufficient_type_info/src/main.sw
The IR stage is written such that any unresolved types are an internal compiler error. This is an invariant of the IR according to @otrho and therefore should be upheld as an ICE.
This PR adds a pass before the IR stage that ensures all types are well-formed and not insufficiently specified before IR gen. Eventually we could make a _new_ tree type that uses a specified `Type` enum without any unspecified variants. That would get us compile-time proofs of correctness and allow us to drop the type engine after type checking. However, it would be a _ton_ of copy/paste as we would have to recreate our AST type, so I'm deeming it out of scope for now.
before:
after:
=> Ensure well-formed and concrete types before IR gen

docs/src/introduction/overview.md
Close https://github.com/FuelLabs/sway/issues/1405
=> Add contract type and use wallet_lib::Wallet in wallet_contract example

Cargo.lock
Change probably missed from an earlier PR.
=> Updating Cargo.lock

sway-core/src/asm_generation/register_allocator.rs
=> Some code cleanup in `register_allocator.rs`

.github/workflows/ci.yml
- This PR updates the `build-forc-test-project` CI job to use a local `sway-lib-std` dependency
=> Update manifest for build-forc-test-project

docs/README.md
=> Revert 1477 braqzen #1476 and update formatting

forc/src/utils/defaults.rs
=> Changed default manifest dependency ordering

docs/src/blockchain-development/calling_contracts.md
=> Updated example to show how to call a private function

.github/workflows/ci.yml, test/src/sdk-harness/build.sh
This PR adds `--locked` to CI `cargo` commands
=> Add --locked to cargo CI

sway-core/src/control_flow_analysis/dead_code_analysis.rs
`ConstantDeclaration`s aren't actually a thing as they're now all just `VariableDeclaration`s with 'pub const' mutability.  This needed to be accounted for in the dead code analysis.
Closes #1529.
=> Make sure global const delcarations are not misreported as unused.

docs/src/basics/comments_and_logging.md
=> Added block comment example

docs/src/blockchain-development/calling_contracts.md
=> Fixed Typo in book advanced Calls. #1561 

examples/hashing/src/main.sw, sway-lib-std/src/hash.sw, test/src/sdk-harness/Cargo.toml, test/src/sdk-harness/test_projects/hashing/mod.rs, test/src/sdk-harness/test_projects/hashing/src/main.sw
=> Added generic keccak256 function

forc-util/src/lib.rs, forc/src/ops/forc_init.rs
=> Updated welcome message colors

sway-lsp/src/core/token.rs
See @canndrew's explanation [here](https://github.com/FuelLabs/sway/issues/1395#issuecomment-1125943930) for more context on why this was originally causing our bug. 
closes #1385
closes #1395
=> Fix incorrect collection of tokens from tuples in the language server

docs/theme/highlight.js, scripts/highlightjs/build.sh
=> Add more highlighted languages

forc/src/utils/defaults.rs
Bump fuels-rs forc init to 0.14
=> Bump fuels-rs init version to 0.14

docs/src/blockchain-development/purity.md
Just until https://github.com/FuelLabs/sway/pull/1716 is complete and released.
=> Add a note saying that the storage attributes are still WIP

docs/src/testing/testing-with-rust.md
Closes https://github.com/FuelLabs/sway/issues/1723
The current test is outdated.
=> Update the Rust SDK test

docs/src/basics/comments_and_logging.md
Closes https://github.com/FuelLabs/sway/issues/1635
=> Update the logging section in the Sway Book

docs/src/sway-program-types/libraries.md
Also closes https://github.com/FuelLabs/sway/issues/1605
=> Improve the libraries section

docs/src/basics/comments_and_logging.md, docs/src/introduction/overview.md
This should get merged after `v0.14.3` is published.
=> Update how receipts look like in the Sway Book after #1717

docs/src/basics/control_flow.md, examples/match_statements/src/main.sw
Closes https://github.com/FuelLabs/sway/issues/1757
=> Add an `enum` matching example

sway-core/src/control_flow_analysis/dead_code_analysis.rs, sway-lib-std/src/u128.sw
Now I am going to be perfectly honest here and admit I don't actually know why this works.  @sezna Does this make any sense?
Closes #1682.
=> Change the dead code analysis for `if` expressions.

forc-util/src/lib.rs, forc/src/ops/forc_init.rs
closes #1698.
Reverts the colors back to old settings (before #1662).
=> Change color of forc init output

sway-lib-std/src/token.sw
This reverts commit cee607dfedfa633f00daa9c1ef20fc2f0217f095.
=> Revert "Made transfer_to a little more generic (#1853)"

sway-core/src/parse_tree/expression/mod.rs
=> Remove dead code

forc-pkg/src/pkg.rs
This is WIP opening up for visibility. 
This is one of the proposed solutions for #1869
=> remove_deps cannot handle removed dependencies correctly when there are multiple roots after edge removal

forc-pkg/src/pkg.rs
closes #1908.
Dependency cycles were detected but not explicitly printed. 
With this PR, we are computing strongly connected components using [Kosaraju's algorithm](https://en.wikipedia.org/wiki/Kosaraju%27s_algorithm). If the resulting list of nodes has more than 1 element, they are members of a cycle in the graph.  
1. `forc init --library dependency_a`
2. `forc init --library dependency_b`
3. add `dependency_b` as a dependency for `dependency_a`
4. add`dependency_a` as a dependency for `dependency_b`
5. `forc init --library dependency_c`
6. `forc init --library dependency_d`
7. add `dependency_c` as a dependency for `dependency_d`
8. add `dependency_d` as a dependency for `dependency_c`
10. add `dependency_c` as a dependency for `dependency_a` 
11. `forc build` in dependency_a
The …
=> Dependency cycles are explicitly printed

docs/src/basics/built_in_types.md, docs/src/reference/known_issues_and_workarounds.md, examples/arrays/Forc.lock, examples/arrays/Forc.toml, examples/arrays/src/main.sw
And some small other things.
I expect the section on "Missing Features" to slowly expand (and then hopefully shrink after that 😄)
=> General enhancements to arrays in the Sway Book

Cargo.lock, forc-gm/Cargo.toml, forc-pkg/Cargo.toml, forc-plugins/forc-explore/Cargo.toml, forc-plugins/forc-fmt-v2/Cargo.toml, forc-plugins/forc-fmt/Cargo.toml, forc-plugins/forc-lsp/Cargo.toml, forc-util/Cargo.toml, forc/Cargo.toml, sway-core/Cargo.toml, sway-fmt-v2/Cargo.toml, sway-fmt/Cargo.toml, sway-ir/Cargo.toml, sway-lsp/Cargo.toml, sway-parse/Cargo.toml, sway-types/Cargo.toml, sway-utils/Cargo.toml
~~Waiting on https://github.com/FuelLabs/sway/pull/1921~~ No longer waiting on #1921. Something needs to be investigated on the SDK side first.
=> Bump to v0.15.2

forc/src/utils/defaults.rs, test/src/sdk-harness/Cargo.toml
Closes https://github.com/FuelLabs/sway/issues/1907
~~Currently blocked by an issue on the SDK side.~~
=> Bump to fuels 0.15

sway-fmt-v2/src/utils/bracket.rs
=> Adds `AngleBracket` to `utils::bracket`

.github/workflows/gh-pages.yml
Fixes #1577
See successful run here: https://github.com/adlerjohn/mdbook-ci-test/actions/runs/2512943740
=> Split book into latest and master.

sway-lib-std/src/storage.sw
looks like an extra "the" got into this comment
=> Remove extra "the"

sway-fmt-v2/src/config/user_def.rs, sway-fmt-v2/src/config/user_opts.rs, sway-fmt-v2/src/constants.rs
=> Added storage field alignment threshold to formatter config

sway-core/src/control_flow_analysis/dead_code_analysis.rs
While waiting for the tests to pass on a PR I thought I'd have a quick
look to see if I could find any quick wins for dead code analysis #1952.
I noticed that we're using `has_path_connecting` for every
combination of node and entry point. This means we were re-checking the
same nodes many, many times, searching from scratch each time and not
re-using any of the knowledge of already visited nodes in each
consecutive traversal.
This commit refactors the approach to first collect all known live nodes
into a set by traversing from the entry points. We re-use the same `Dfs`
when searching from each entry in order to re-use its inner set of
visited nodes and avoid re-searching sections of the graph that we've
already visited.
The dead nodes are those not contained in the live set after …
=> Speedup `find_dead_code` pass in control flow analysis

README.md
Closes https://github.com/FuelLabs/sway/issues/2171
=> Update broken link for contributing to Sway in README.md

forc-pkg/src/lock.rs, forc-plugins/forc-explore/src/main.rs, forc-util/src/lib.rs, forc-util/src/restricted.rs, forc/src/ops/forc_abi_json.rs, forc/src/ops/forc_clean.rs, sway-core/src/semantic_analysis/ast_node/expression/match_expression/analysis/pattern.rs, sway-core/src/semantic_analysis/ast_node/expression/typed_expression.rs, sway-core/src/semantic_analysis/ast_node/mod.rs, sway-fmt/src/traversal_helper.rs, test/src/e2e_vm_tests/harness.rs
The new version of clippy added some lints. This should get our CI back in good shape.
=> Fix new clippy lints.

test/src/e2e_vm_tests/test_programs/should_pass/language/modulo_uint_test/Forc.toml
Changes:
- Changed author entry to `Fuel Labs <contact@fuel.sh>`
Closes #2199
=> Update author entry in manifest test for `e2e/.../language/modulo_uint_test`

sway-fmt-v2/src/fmt.rs, sway-fmt-v2/src/items/item_abi.rs, sway-fmt-v2/src/items/item_const.rs, sway-fmt-v2/src/items/item_enum.rs, sway-fmt-v2/src/items/item_storage.rs, sway-fmt-v2/src/items/item_struct.rs, sway-fmt-v2/src/utils/attribute.rs, sway-fmt-v2/src/utils/generics.rs, sway-fmt-v2/src/utils/newline_style.rs, sway-fmt-v2/src/utils/path.rs, sway-fmt-v2/src/utils/program_type.rs, sway-fmt-v2/src/utils/punctuated.rs, sway-fmt-v2/src/utils/ty.rs
Just a quickie to fix some small stuff
Closes #2249 
Closes #2254
=> Update `sway-fmt-v2` with new `Ty` formatting and replace `push_str` with `write!`

forc-pkg/src/pkg.rs
Previously, if a path dependency's directory was removed from its
expected `path` location, the produced error would refer to a "patch"
even if there was no patch being applied:
```
Error: Cant apply patch from ../child, cause: No such file or directory (os error 2)
```
This improves the error message for this case:
```
Error: Failed to source dependency: Failed to canonicalize dependency path "parent/../child": No such file or directory (os error 2)
```
Also improves the error handling around patches more generally. In
particular, this fixes a case where an error could be produced in the
case that a dependency's URL was patched, but its name wasn't found
within the patch table. Instead, we assume no patch is desired. This is
necessary to allow users to source multiple packages from a …
=> forc-pkg: Improve error handling around removed path deps and patches

Cargo.lock, forc-gm/Cargo.toml, forc-pkg/Cargo.toml, forc-plugins/forc-explore/Cargo.toml, forc-plugins/forc-fmt-v2/Cargo.toml, forc-plugins/forc-fmt/Cargo.toml, forc-plugins/forc-lsp/Cargo.toml, forc-util/Cargo.toml, forc/Cargo.toml, sway-core/Cargo.toml, sway-fmt-v2/Cargo.toml, sway-fmt/Cargo.toml, sway-ir/Cargo.toml, sway-lsp/Cargo.toml, sway-parse/Cargo.toml, sway-types/Cargo.toml, sway-utils/Cargo.toml
=> Bump to v0.18.1

sway-core/src/ir_generation/function.rs, test/src/e2e_vm_tests/test_programs/should_pass/language/redundant_return/Forc.lock, test/src/e2e_vm_tests/test_programs/should_pass/language/redundant_return/Forc.toml, test/src/e2e_vm_tests/test_programs/should_pass/language/redundant_return/json_abi_oracle.json, test/src/e2e_vm_tests/test_programs/should_pass/language/redundant_return/src/main.sw, test/src/e2e_vm_tests/test_programs/should_pass/language/redundant_return/test.toml, test/src/ir_generation/tests/redundant_return.sw
Closes https://github.com/FuelLabs/sway/issues/2309
=> Add `is_terminated` check before compiling return statements to IR

forc-util/src/lib.rs, test/src/e2e_vm_tests/test_programs/should_fail/utf_chars/Forc.lock, test/src/e2e_vm_tests/test_programs/should_fail/utf_chars/Forc.toml, test/src/e2e_vm_tests/test_programs/should_fail/utf_chars/src/main.sw, test/src/e2e_vm_tests/test_programs/should_fail/utf_chars/test.toml
=> Fix utf8 related bug in computing window for errors and warnings.

sway-lib-std/src/assert.sw, sway-lib-std/src/chain/auth.sw, sway-lib-std/src/context.sw, sway-lib-std/src/context/call_frames.sw, sway-lib-std/src/ecr.sw, sway-lib-std/src/flags.sw, sway-lib-std/src/mem.sw, sway-lib-std/src/option.sw, sway-lib-std/src/reentrancy.sw, sway-lib-std/src/revert.sw, sway-lib-std/src/storage.sw, sway-lib-std/src/token.sw, sway-lib-std/src/tx.sw, sway-lib-std/src/u128.sw, sway-lib-std/src/u256.sw, sway-lib-std/src/vec.sw, sway-lib-std/src/vm/evm/ecr.sw
* Some formatting issues
* Some TODOs
* Some general code refactoring
* Removal of some `*` imports
etc.
Also closes https://github.com/FuelLabs/sway/issues/2119
=> General code quality enhancements to the standard library

Cargo.lock, forc-pkg/Cargo.toml, forc-plugins/forc-explore/Cargo.toml, forc-plugins/forc-fmt-v2/Cargo.toml, forc-plugins/forc-fmt/Cargo.toml, forc-plugins/forc-lsp/Cargo.toml, forc-util/Cargo.toml, forc/Cargo.toml, sway-core/Cargo.toml, sway-fmt-v2/Cargo.toml, sway-fmt/Cargo.toml, sway-ir/Cargo.toml, sway-lsp/Cargo.toml, sway-parse/Cargo.toml, sway-types/Cargo.toml, sway-utils/Cargo.toml
=> Bump to `v0.19.1`

sway-ir/src/optimize/simplify_cfg.rs
Addressing nits in #2436 from Alex.
=> Add an overall description to the `simplify-cfg` IR pass.

forc/README.md
=> Fix link to Forc reference in the repo

docs/src/reference/known_issues_and_workarounds.md
`ref mut` args are now available.
=> Remove known issue and fix issue number for another

docs/src/basics/methods_and_associated_functions.md
=> Fixed typo

sway-parse/src/token.rs
=> fix: ForwardSlash span collection

sway-core/src/asm_generation/from_ir.rs, sway-core/tests/ir_to_asm/gtf.asm, sway-core/tests/ir_to_asm/gtf.ir
Fixes one problem in https://github.com/FuelLabs/sway/pull/2642
=> Fix in how the `__gtf` intrinsic is lowered to asm

sway-fmt-v2/src/formatter/mod.rs, sway-fmt-v2/src/utils/language/attribute.rs
=> feat: doc comment formatting

sway-fmt-v2/src/formatter/mod.rs, sway-fmt-v2/src/items/item_trait.rs, sway-fmt-v2/src/utils/map/newline.rs
=> fix: Unformatted comment spans add extra newline

examples/subcurrency/src/main.sw, examples/wallet_abi/src/main.sw, examples/wallet_smart_contract/src/main.sw, swayfmt/src/formatter/mod.rs, swayfmt/src/module/mod.rs, swayfmt/src/utils/map/byte_span.rs, swayfmt/src/utils/map/comments.rs
=> fix: Formatter removes comments at the beginning of the file

.github/workflows/ci.yml
Fix for the publishing failure here: https://github.com/FuelLabs/sway/actions/runs/2982158010
=> fix tag verification for swayfmt

docs/src/forc_client.md
=> doc: added a section about interaction with the testnet

Cargo.lock, forc-pkg/Cargo.toml, forc-plugins/forc-client/Cargo.toml, forc-plugins/forc-explore/Cargo.toml, forc-plugins/forc-fmt/Cargo.toml, forc-plugins/forc-lsp/Cargo.toml, forc-util/Cargo.toml, forc/Cargo.toml, sway-ast/Cargo.toml, sway-core/Cargo.toml, sway-ir/Cargo.toml, sway-lsp/Cargo.toml, sway-parse/Cargo.toml, sway-types/Cargo.toml, sway-utils/Cargo.toml, swayfmt/Cargo.toml
Also ran `cargo update`
Pending:
=> Bump to `v0.24.0`

sway-core/src/type_system/type_info.rs, test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/abi_with_generic_types/json_abi_oracle.json, test/src/e2e_vm_tests/test_programs/should_pass/test_contracts/abi_with_generic_types/src/main.sw
Closes https://github.com/FuelLabs/sway/issues/2759
Simple change that was missed from the original change that introduced then new JSON ABI format.
=> Fix JSON ABI for generic tuples in structs

swayfmt/src/formatter/mod.rs, swayfmt/src/utils/map/comments.rs
Closes #2739
also ref #2649 though I don't believe this PR will close it, they are similar issues
=> Fix comments preceding `module_kind`

forc-plugins/forc-client/src/ops/deploy/op.rs, forc-plugins/forc-client/src/ops/run/op.rs
Related https://github.com/FuelLabs/sway/issues/1661
=> Replace println with tracing [ops]

sway-lib-std/src/address.sw, sway-lib-std/src/b512.sw, sway-lib-std/src/block.sw, sway-lib-std/src/chain/auth.sw, sway-lib-std/src/context.sw, sway-lib-std/src/context/call_frames.sw, sway-lib-std/src/context/registers.sw, sway-lib-std/src/contract_id.sw, sway-lib-std/src/ecr.sw, sway-lib-std/src/identity.sw, sway-lib-std/src/inputs.sw, sway-lib-std/src/logging.sw, sway-lib-std/src/mem.sw, sway-lib-std/src/option.sw, sway-lib-std/src/outputs.sw, sway-lib-std/src/prelude.sw, sway-lib-std/src/reentrancy.sw, sway-lib-std/src/result.sw, sway-lib-std/src/storage.sw, sway-lib-std/src/token.sw, sway-lib-std/src/tx.sw, sway-lib-std/src/u128.sw, sway-lib-std/src/u256.sw, sway-lib-std/src/vec.sw, sway-lib-std/src/vm/evm/ecr.sw, sway-lib-std/src/vm/evm/evm_address.sw
I had to revert some formatter changes related to comments.
=> Minor nits in the standard library + fmt

docs/src/introduction/standard_library.md, docs/src/sway-program-types/libraries.md, examples/identity/src/main.sw, examples/msg_sender/src/main.sw, examples/ownership/src/main.sw, examples/signatures/src/main.sw, examples/storage_map/src/main.sw, examples/storage_vec/src/main.sw, examples/subcurrency/src/main.sw, examples/vec/src/main.sw, examples/wallet_smart_contract/src/main.sw, sway-lib-std/src/prelude.sw, test/src/e2e_vm_tests/test_programs/should_fail/better_type_error_message/Forc.toml, test/src/e2e_vm_tests/test_programs/should_fail/better_type_error_message/src/main.sw, test/src/e2e_vm_tests/test_programs/should_fail/better_type_error_message/test.toml
=> Add `Option` and `Result` to the standard library prelude

sway-core/src/type_system/type_engine.rs
Simple PR to add some documentation to the type engine.
=> Add some documentation to the type engine.

swayfmt/src/utils/language/expr/mod.rs
=> Rename `visit_expr` to `expr_leaf_spans`

sway-lib-std/src/option.sw, sway-lib-std/src/reentrancy.sw, sway-lib-std/src/result.sw, sway-lib-std/src/storage.sw, sway-lib-std/src/token.sw, sway-lib-std/src/vec.sw
=> Fix `doc` comments and apply to `lib std`

docs/src/basics/built_in_types.md, sway-core/src/convert_parse_tree.rs, sway-core/src/error.rs, sway-core/src/ir_generation/convert.rs, sway-core/src/language/literal.rs, sway-core/src/semantic_analysis/ast_node/expression/match_expression/analysis/constructor_factory.rs, sway-core/src/semantic_analysis/ast_node/expression/match_expression/analysis/pattern.rs, sway-core/src/semantic_analysis/ast_node/expression/typed_expression.rs, sway-core/src/semantic_analysis/node_dependencies.rs, sway-core/src/type_system/resolved_type.rs, sway-core/src/type_system/type_engine.rs, sway-core/src/type_system/type_id.rs, sway-core/src/type_system/type_info.rs, sway-core/src/type_system/type_mapping.rs, sway-lsp/src/core/traverse_parse_tree.rs, sway-lsp/src/utils/debug.rs, sway-lsp/src/utils/token.rs, test/src/e2e_vm_tests/test_programs/should_pass/language/is_reference_type/src/main.sw
=> Remove `byte` type and associated literal

sway-core/src/language/ty/declaration/constant.rs, sway-core/src/semantic_analysis/ast_node/mod.rs
=> Add `const` attributes to `TyProgram`

sway-core/src/language/ty/declaration/trait.rs, sway-core/src/semantic_analysis/ast_node/declaration/trait.rs
=> Add `trait` attributes to `TyProgram`

sway-core/src/convert_parse_tree.rs, sway-core/src/language/parsed/declaration/abi.rs, sway-core/src/language/ty/declaration/abi.rs, sway-core/src/semantic_analysis/ast_node/declaration/abi.rs
=> Add `abi` attributes to `TyProgram`

examples/asm_return_tuple_pointer/src/main.sw, swayfmt/src/utils/language/expr/asm_block.rs
=> fix: add missing leaf span collection for final_expr_opt of asm blocks

docs/src/forc/manifest_reference.md
=> Simplify doc example for `contract-dependencies`

sway-lsp/src/capabilities/completion.rs, sway-lsp/src/capabilities/diagnostic.rs, sway-lsp/src/capabilities/document_symbol.rs, sway-lsp/src/capabilities/hover.rs, sway-lsp/src/capabilities/inlay_hints.rs, sway-lsp/src/capabilities/rename.rs, sway-lsp/src/capabilities/semantic_tokens.rs, sway-lsp/src/core/session.rs, sway-lsp/src/server.rs, sway-lsp/src/utils/common.rs, sway-lsp/src/utils/debug.rs, sway-lsp/src/utils/function.rs, sway-lsp/src/utils/mod.rs, sway-lsp/src/utils/sync.rs, sway-lsp/src/utils/token.rs
Just did some house cleaning 
- remove unused code
- documented some functions
- remove unnecessary `if let` in favor of using `?`
- moved some functions around
- instead of returning and passing around `TokenMap`, return and pass in an Iterator of tokens `where I: Iterator<Item = (Ident, Token)>,`
=> LSP: Code clean up, remove unused code, add missing docs

sway-core/src/language/ty/module.rs
This fixes the submodule iterator added in #3152.
Previously this wasn't actually returning any submodules, only traversing them! This resulted in `test_fns` method not working. This commit fixes the behaviour, tested locally as a part of #2985.
=> Fix `TyModule::submodules_recursive` iterator

swayfmt/src/formatter/mod.rs, swayfmt/src/items/item_trait.rs, swayfmt/src/utils/language/where_clause.rs
=> fix: Sway formatter removing generic traits type parameters

test/src/e2e_vm_tests/test_programs/should_pass/stdlib/if_type_revert/Forc.lock, test/src/e2e_vm_tests/test_programs/should_pass/stdlib/if_type_revert/Forc.toml, test/src/e2e_vm_tests/test_programs/should_pass/stdlib/if_type_revert/src/main.sw, test/src/e2e_vm_tests/test_programs/should_pass/stdlib/if_type_revert/test.toml
This is a test that was posted in #2876
This test case now runs without causing the internal error mentioned in the issue.
Pushing this test case which appears not to be covered in the existing ones.
Closes #2876
=> Tests revert in an if branch

examples/arrays/Forc.lock, examples/asm_return_tuple_pointer/Forc.lock, examples/break_and_continue/Forc.lock, examples/config_time_constants/Forc.lock, examples/counter/Forc.lock, examples/enums/Forc.lock, examples/fizzbuzz/Forc.lock, examples/hashing/Forc.lock, examples/identity/Forc.lock, examples/liquidity_pool/Forc.lock, examples/match_statements/Forc.lock, examples/msg_sender/Forc.lock, examples/native_token/Forc.lock, examples/ownership/Forc.lock, examples/ref_mut_params/Forc.lock, examples/signatures/Forc.lock, examples/storage_example/Forc.lock, examples/storage_map/Forc.lock, examples/storage_variables/Forc.lock, examples/storage_vec/Forc.lock, examples/structs/Forc.lock, examples/subcurrency/Forc.lock, examples/subcurrency/src/main.sw, examples/tuples/Forc.lock, examples/vec/Forc.lock, examples/wallet_abi/Forc.lock, examples/wallet_contract_caller_script/Forc.lock, examples/wallet_smart_contract/Forc.lock
And adding a missing semicolon in `subcurrency`.
=> Update lock files for all examples

.github/workflows/ci.yml, Cargo.lock, docs/src/sway-program-types/predicates.md, forc-pkg/Cargo.toml, forc-plugins/forc-client/Cargo.toml, forc-plugins/forc-doc/Cargo.toml, forc-plugins/forc-fmt/Cargo.toml, forc-plugins/forc-lsp/Cargo.toml, forc-test/Cargo.toml, forc-tracing/Cargo.toml, forc-util/Cargo.toml, forc/Cargo.toml, sway-ast/Cargo.toml, sway-core/Cargo.toml, sway-error/Cargo.toml, sway-ir/Cargo.toml, sway-ir/sway-ir-macros/Cargo.toml, sway-lsp/Cargo.toml, sway-parse/Cargo.toml, sway-types/Cargo.toml, sway-utils/Cargo.toml, swayfmt/Cargo.toml, test/src/sdk-harness/test_projects/evm_ec_recover/Forc.lock, test/src/sdk-harness/test_projects/evm_ec_recover/Forc.toml
=> Bump to`v0.31.0`

sway-lib-std/src/u256.sw
=> `U256` multiplication optimisation

swayfmt/src/formatter/mod.rs, swayfmt/src/items/item_trait.rs
=> Fix formatter failure on traits with definition block

sway-core/src/type_system/type_binding.rs, test/src/e2e_vm_tests/test_programs/should_fail/insufficient_type_info_fnret/Forc.lock, test/src/e2e_vm_tests/test_programs/should_fail/insufficient_type_info_fnret/Forc.toml, test/src/e2e_vm_tests/test_programs/should_fail/insufficient_type_info_fnret/src/main.sw, test/src/e2e_vm_tests/test_programs/should_fail/insufficient_type_info_fnret/test.toml
=> Check for errors after type checking type arguments.

forc/src/cli/commands/new.rs
=> fix: reserved keywords are checked before creating dir with forc new

sway-lib-std/src/u256.sw, test/src/e2e_vm_tests/test_programs/should_pass/stdlib/u256_div_test/src/main.sw
Closes https://github.com/FuelLabs/sway/issues/3567
=> typo in `U256` multiplication 

test/src/e2e_vm_tests/test_programs/should_pass/language/where_clause_functions/src/main.sw
I wasn't able to reproduce the error shown in #3325---I believe it to be resolved in the form shown in #3325. This PR adds the code from that issue to the test suite.
Closes #3325
=> Demonstrating bugfix to trait constraints

sway-core/src/semantic_analysis/ast_node/declaration/declaration.rs, sway-core/src/semantic_analysis/namespace/items.rs, test/src/e2e_vm_tests/test_programs/should_fail/repeated_abi_declaration/Forc.lock, test/src/e2e_vm_tests/test_programs/should_fail/repeated_abi_declaration/Forc.toml, test/src/e2e_vm_tests/test_programs/should_fail/repeated_abi_declaration/src/main.sw, test/src/e2e_vm_tests/test_programs/should_fail/repeated_abi_declaration/test.toml, test/src/e2e_vm_tests/test_programs/should_fail/repeated_trait_declaration/Forc.lock, test/src/e2e_vm_tests/test_programs/should_fail/repeated_trait_declaration/Forc.toml, test/src/e2e_vm_tests/test_programs/should_fail/repeated_trait_declaration/src/main.sw, test/src/e2e_vm_tests/test_programs/should_fail/repeated_trait_declaration/test.toml, test/src/e2e_vm_tests/test_programs/should_pass/language/where_clause_functions/src/main.sw
=> Block repeated ABI/trait declarations

Cargo.lock, forc-pkg/Cargo.toml, forc-plugins/forc-client/Cargo.toml, forc-plugins/forc-doc/Cargo.toml, forc-plugins/forc-fmt/Cargo.toml, forc-plugins/forc-lsp/Cargo.toml, forc-test/Cargo.toml, forc-tracing/Cargo.toml, forc-util/Cargo.toml, forc/Cargo.toml, sway-ast/Cargo.toml, sway-core/Cargo.toml, sway-error/Cargo.toml, sway-ir/Cargo.toml, sway-ir/sway-ir-macros/Cargo.toml, sway-lsp/Cargo.toml, sway-parse/Cargo.toml, sway-types/Cargo.toml, sway-utils/Cargo.toml, swayfmt/Cargo.toml
=> Bump to `v0.33.0`

.github/ISSUE_TEMPLATE/lsp-missing-token.md
Creating this issue template temporarily to make it faster to create a bunch of these issues.
https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/manually-creating-a-single-issue-template-for-your-repository
=> Update issue templates

test/src/e2e_vm_tests/test_programs/should_pass/language/import_method_from_other_file/Forc.lock, test/src/e2e_vm_tests/test_programs/should_pass/language/import_method_from_other_file/Forc.toml, test/src/e2e_vm_tests/test_programs/should_pass/language/import_method_from_other_file/src/asset.sw, test/src/e2e_vm_tests/test_programs/should_pass/language/import_method_from_other_file/src/main.sw, test/src/e2e_vm_tests/test_programs/should_pass/language/import_method_from_other_file/src/utils.sw
I believe this bug is resolved, and I wasn't able to reproduce it. I'm adding this test case to document this.
Closes #2277
=> Demonstrate that the bug for re-importing in order to access functionality is resolved

sway-lsp/src/traverse/parsed_tree.rs, sway-lsp/src/traverse/typed_tree.rs
No changes to the compiler were needed for this one. Nice and straightforward.
closes #3724
=> LSP: Collect tuple index Span

examples/fizzbuzz/src/main.sw, sway-lsp/src/capabilities/diagnostic.rs, sway-lsp/src/config.rs, sway-lsp/src/core/session.rs, sway-lsp/src/error.rs, sway-lsp/src/server.rs
Closes https://github.com/FuelLabs/sway/issues/3745
=> Add LSP option to hide compiler warnings and errors

sway-lsp/src/capabilities/completion.rs, sway-lsp/src/capabilities/document_symbol.rs, sway-lsp/src/capabilities/semantic_tokens.rs, sway-lsp/src/core/token.rs, sway-lsp/src/traverse/lexed_tree.rs, sway-lsp/src/traverse/mod.rs, sway-lsp/src/traverse/parsed_tree.rs
=> LSP: Collect attribute name tokens

sway-core/src/language/parsed/expression/mod.rs, sway-core/src/semantic_analysis/ast_node/expression/typed_expression.rs, sway-core/src/transform/to_parsed_lang/convert_parse_tree.rs, sway-lsp/src/core/token.rs, sway-lsp/src/traverse/parsed_tree.rs
=> LSP: Collect `IntrinsicFunctionExpression` tokens

sway-core/src/semantic_analysis/storage_only_types.rs, test/src/e2e_vm_tests/test_programs/should_fail/storage_types/src/main.sw, test/src/e2e_vm_tests/test_programs/should_fail/storage_types/test.toml
=> Disallow returning `StorageMap` and `StorageVec` from contract methods and standalone functions

Cargo.lock, forc-plugins/forc-fmt/Cargo.toml, forc-plugins/forc-fmt/src/main.rs
=> feat: forc-fmt workspace support

forc-plugins/forc-doc/src/descriptor.rs, forc-plugins/forc-doc/src/doc.rs, forc-plugins/forc-doc/src/render.rs
Closes #3820 
I've added a limit of 200 characters so that anything longer would be 75 characters with an ellipsis (not pictured):
=> Add docstring previews to index files

forc-pkg/src/manifest.rs, test/src/e2e_vm_tests/test_programs/should_fail/duplicate_pkg_names_in_workspace/Forc.lock, test/src/e2e_vm_tests/test_programs/should_fail/duplicate_pkg_names_in_workspace/Forc.toml, test/src/e2e_vm_tests/test_programs/should_fail/duplicate_pkg_names_in_workspace/contract/Forc.toml, test/src/e2e_vm_tests/test_programs/should_fail/duplicate_pkg_names_in_workspace/contract/src/main.sw, test/src/e2e_vm_tests/test_programs/should_fail/duplicate_pkg_names_in_workspace/contract2/Forc.toml, test/src/e2e_vm_tests/test_programs/should_fail/duplicate_pkg_names_in_workspace/contract2/src/main.sw, test/src/e2e_vm_tests/test_programs/should_fail/duplicate_pkg_names_in_workspace/script/Forc.toml, test/src/e2e_vm_tests/test_programs/should_fail/duplicate_pkg_names_in_workspace/script/src/main.sw, test/src/e2e_vm_tests/test_programs/should_fail/duplicate_pkg_names_in_workspace/script2/Forc.toml, test/src/e2e_vm_tests/test_programs/should_fail/duplicate_pkg_names_in_workspace/script2/src/main.sw, test/src/e2e_vm_tests/test_programs/should_fail/duplicate_pkg_names_in_workspace/test.toml
=> feat: error out if more than one package declares the same package name in a workspace

sway-core/src/semantic_analysis/ast_node/declaration/function.rs, sway-core/src/semantic_analysis/ast_node/declaration/impl_trait.rs, sway-core/src/type_system/id.rs, test/src/e2e_vm_tests/test_programs/should_fail/unknown_types_in_contract/src/main.sw, test/src/e2e_vm_tests/test_programs/should_pass/language/generic_type_inference/src/main.sw, test/src/e2e_vm_tests/test_programs/should_pass/language/generic_type_inference/src/utils.sw
This PR fixes a bug with the self type bug updating the `replace_self_type` method on `TypeId` to properly handle nested types.
Closes #3863
=> Fix bug with replacing the self type.

sway-lib-std/src/bytes.sw
=> Impl From<b256> for Bytes

swayfmt/src/formatter/mod.rs, swayfmt/src/utils/language/expr/conditional.rs, swayfmt/src/utils/language/expr/mod.rs
=> Fix handling of empty code blocks

.github/workflows/ci.yml, .github/workflows/gh-pages.yml
=> Updated `mdbook` verson in CI

forc-test/src/lib.rs
This PR adds a step to execution of unit tests so that duplicate unit tests are omitted. Duplicate tests are generated from dependencies declared with `dep` keyword in a duplicate manner (see #3947). Until that is fixed this PR de-duplicates sway unit tests based on their `span`. Once the fix for #3947 is ready we can remove the changes from this PR. This is also commented in the code.
closes #3813.
=> fix: prevent duplicate sway unit test execution

forc-pkg/src/pkg.rs, forc-test/src/lib.rs
This PR addresses couple of left over comments from previous PRs and introduces a general clean-up to the `forc-test`. Since lots of new stuff added rapidly to the codebase some of the comments were left over. Especially from https://github.com/FuelLabs/sway/pull/3672#pullrequestreview-1239935588
=> refactor: general clean-up for `forc-test`

docs/book/README.md, scripts/mdbook-forc-documenter/README.md
=> Update sway book `README`

docs/book/src/introduction/sway_quickstart.md
Ongoing PR for beta-3 changes in the Sway repo:
1. Made minor changes in the Sway quickstart for beta-3
=> beta-3 updates

sway-core/src/semantic_analysis/ast_node/declaration/enum.rs, sway-core/src/semantic_analysis/ast_node/declaration/function.rs, sway-core/src/semantic_analysis/ast_node/declaration/impl_trait.rs, sway-core/src/semantic_analysis/ast_node/declaration/struct.rs, sway-core/src/semantic_analysis/ast_node/declaration/trait.rs, sway-core/src/type_system/type_parameter.rs
This PR is a small refactor to the method call to type check a list of `TypeParameter`. This is to reduce the diff on #3744. This PR should have no practical or logical effect on `master`.
=> Small refactor to the method call to type check a list of `TypeParameter`

sway-core/src/decl_engine/ref.rs
Just a small PR with additional documentation.
=> Additional rustdoc documentation for `DeclRef`

docs/book/src/forc/plugins/forc_client/index.md
See the detailed release notes for `forc-wallet` v0.2.0 here:
https://github.com/FuelLabs/forc-wallet/releases/tag/v0.2.0
Related: https://github.com/FuelLabs/forc-wallet/issues/87.
=> Update Sway book section on `forc-wallet` for changes in v0.2.0

sway-lsp/src/traverse/typed_tree.rs
=> Fix: add type_def for `GenericTypeForFunctionScope` and fix storage field type_def

sway-core/src/semantic_analysis/ast_node/declaration/impl_trait.rs
Small PR to add an optimization and reduce load in the `TraitMap`. This prevents unnecessary entries being created for supertraits when a trait has no supertraits.
=> Small refactor to only create a `TraitMap` entry for the supertraits if there are supertraits.

sway-core/src/semantic_analysis/module.rs, sway-core/src/semantic_analysis/node_dependencies.rs
Small refactor to use `Engines` where possible, to promote code unity across the codebase and reduce possibilities for code refactors in the future.
~~- [ ] I have linked to any relevant issues.~~
~~- [ ] I have commented my code, particularly in hard-to-understand areas.~~
~~- [ ] I have updated the documentation where relevant (API docs, the reference, and the Sway book).~~
~~- [ ] I have added tests that prove my fix is effective or that my feature works.~~
=> Refactor to use `Engines` where possible

docs/book/src/basics/methods_and_associated_functions.md, examples/Forc.lock, examples/Forc.toml, examples/methods_and_associated_functions/Forc.toml, examples/methods_and_associated_functions/src/main.sw
Closes #4223
Basically just showing that associated methods do actually work.
=> New example for methods and associated functions

forc-plugins/forc-doc/src/descriptor.rs, sway-core/src/control_flow_analysis/analyze_return_paths.rs, sway-core/src/control_flow_analysis/dead_code_analysis.rs, sway-core/src/ir_generation/compile.rs, sway-core/src/ir_generation/const_eval.rs, sway-core/src/ir_generation/function.rs, sway-core/src/language/ty/ast_node.rs, sway-core/src/language/ty/declaration/declaration.rs, sway-core/src/language/ty/module.rs, sway-core/src/language/ty/program.rs, sway-core/src/semantic_analysis/ast_node/declaration/declaration.rs, sway-core/src/semantic_analysis/ast_node/declaration/impl_trait.rs, sway-core/src/semantic_analysis/ast_node/declaration/supertrait.rs, sway-core/src/semantic_analysis/ast_node/expression/match_expression/typed/typed_scrutinee.rs, sway-core/src/semantic_analysis/ast_node/expression/typed_expression.rs, sway-core/src/semantic_analysis/cei_pattern_analysis.rs, sway-core/src/semantic_analysis/coins_analysis.rs, sway-core/src/semantic_analysis/storage_only_types.rs, sway-core/src/type_system/binding.rs, sway-core/src/type_system/trait_constraint.rs, sway-core/src/type_system/type_parameter.rs, sway-lsp/src/capabilities/code_actions/abi_decl/mod.rs, sway-lsp/src/capabilities/code_actions/mod.rs, sway-lsp/src/capabilities/code_actions/struct_decl/struct_new.rs, sway-lsp/src/capabilities/hover.rs, sway-lsp/src/traverse/dependency.rs, sway-lsp/src/traverse/typed_tree.rs, sway-lsp/src/utils/debug.rs
=> Revert "Change some `TyDeclaration` variants to hold decl refs"

forc-test/src/lib.rs, sway-core/src/ir_generation/storage.rs, sway-core/src/language/purity.rs, sway-core/src/language/ty/program.rs, sway-core/src/language/ty/variable_mutability.rs, sway-core/src/semantic_analysis/ast_node/declaration/impl_trait.rs, sway-core/src/semantic_analysis/ast_node/expression/match_expression/analysis/constructor_factory.rs, sway-core/src/semantic_analysis/ast_node/mode.rs, sway-core/src/semantic_analysis/namespace/trait_map.rs, sway-core/src/type_system/info.rs
This PR applies new clippy suggestions from a new clippy update.
=> Apply new clippy suggestions from new clippy update

forc-test/src/lib.rs
closes #3988.
We added these span based filters as it was possible to declare duplicate dependencies in a transitive manner and this was causing tests to be duplicated. After the recent re-work of our module structure, it is not possible to declare such packages anymore, so we do not need these filters in-place.
=> refactor: remove span based test filters

docs/book/src/reference/known_issues_and_workarounds.md
https://github.com/FuelLabs/sway/issues/2647 has been resolved.
=> docs: remove missing feature regarding configurables

swayfmt/CONTRIBUTING.md, swayfmt/README.md
The CONTRIBUTING.md instructions were a bit outdated. For example, there is no need at all to uninstall/reinstall components just to test the formatter. Since I was working on the formatter recently and found what I thought is a more efficient way to build/test things, I updated it with what I personally used when handling the formatter.
Also updated the README.md with quickstart links.
=> docs(fmt): update swayfmt docs

swayfmt/src/items/item_configurable/tests.rs
Just a small cleanup - Code deletion is delicious
=> refactor: item_configurable test to use test_macros

sway-core/src/engine_threading.rs, sway-lsp/src/capabilities/code_actions/struct_decl/struct_new.rs, sway-lsp/src/capabilities/hover.rs, sway-lsp/src/capabilities/rename.rs, sway-lsp/src/core/session.rs, sway-lsp/src/core/token.rs, sway-lsp/src/core/token_map.rs
Inspired by @emilyaherbert work in #4225. This PR does the same but for the LSP code base.
=> LSP: Refactor to use `Engines` where possible

forc/src/ops/forc_contract_id.rs
=> feat: `forc contract-id` print contract name before printing id for workspaces

sway-lib-std/src/vec.sw
=>  Failure to delete the only element of `Vec` of length 1 

sway-ir/src/function.rs, sway-ir/src/optimize/dce.rs, sway-ir/tests/dce/dce2.ir, test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/array_of_structs_caller/src/main.sw, test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/call_basic_storage/src/main.sw, test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/call_contract_with_type_aliases/src/main.sw, test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/call_increment_contract/src/main.sw, test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/caller_context_test/src/main.sw, test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/get_storage_key_caller/src/main.sw, test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/nested_struct_args_caller/src/main.sw, test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/storage_access_caller/src/main.sw, test/src/ir_generation/tests/simple_contract_call.sw
=> Remove unused locals

Cargo.lock, forc-pkg/Cargo.toml, forc-plugins/forc-client/Cargo.toml, forc-plugins/forc-doc/Cargo.toml, forc-plugins/forc-fmt/Cargo.toml, forc-plugins/forc-lsp/Cargo.toml, forc-plugins/forc-tx/Cargo.toml, forc-test/Cargo.toml, forc-tracing/Cargo.toml, forc-util/Cargo.toml, forc/Cargo.toml, sway-ast/Cargo.toml, sway-core/Cargo.toml, sway-error/Cargo.toml, sway-ir/Cargo.toml, sway-ir/sway-ir-macros/Cargo.toml, sway-lsp/Cargo.toml, sway-parse/Cargo.toml, sway-types/Cargo.toml, sway-utils/Cargo.toml, swayfmt/Cargo.toml
Waiting for:
1. ~https://github.com/FuelLabs/sway/pull/4488~ we can get this later on it is not urgent.
=> Bump to v0.37.2

docs/book/src/introduction/installation.md
=> fix broken installation url, typo

sway-core/src/transform/to_parsed_lang/convert_parse_tree.rs
Removed some leftovers from a previous PR.
=> Remove leftover dbg!s

Cargo.lock, forc-pkg/Cargo.toml, forc-plugins/forc-client/Cargo.toml, forc-plugins/forc-doc/Cargo.toml, forc-plugins/forc-fmt/Cargo.toml, forc-plugins/forc-lsp/Cargo.toml, forc-plugins/forc-tx/Cargo.toml, forc-test/Cargo.toml, forc-tracing/Cargo.toml, forc-util/Cargo.toml, forc/Cargo.toml, sway-ast/Cargo.toml, sway-core/Cargo.toml, sway-error/Cargo.toml, sway-ir/Cargo.toml, sway-ir/sway-ir-macros/Cargo.toml, sway-lsp/Cargo.toml, sway-parse/Cargo.toml, sway-types/Cargo.toml, sway-utils/Cargo.toml, swayfmt/Cargo.toml
Waiting for:
- #4525.
@Dhaiwat10 was waiting for a release with the linked PR merged.
@IGI-111 I had the PR ready, leaving it up to you when to merge & cut the release. Made this a major bump as we had a breaking change merged (#4574).
=> release: bump to v0.40.0

docs/reference/src/SUMMARY.md, docs/reference/src/code/language/annotations/src/main.sw, docs/reference/src/documentation/language/annotations/attributes/payable.md
=> Sway Reference: Section 9 Annotations. Document the payable annotation 

docs/reference/src/code/language/annotations/src/main.sw, docs/reference/src/documentation/language/annotations/attributes/test.md
=> Sway Reference: Section 9 Annotations: Testing 

docs/reference/src/SUMMARY.md, docs/reference/src/code/language/annotations/src/main.sw, docs/reference/src/documentation/language/annotations/attributes/inline.md
=> Sway Reference: Section 9 Annotations inline

docs/reference/src/SUMMARY.md, docs/reference/src/code/language/annotations/src/main.sw, docs/reference/src/documentation/language/annotations/attributes/allow.md
=> Sway Reference: Section 9 annotations: allow dead code

docs/reference/src/SUMMARY.md, docs/reference/src/documentation/language/style-guide/name-convention.md
=> Sway Reference: Style Guide name convention

sway-lib-std/src/alloc.sw, test/src/e2e_vm_tests/test_programs/should_pass/language/raw_ptr/raw_ptr_ret/test.toml, test/src/e2e_vm_tests/test_programs/should_pass/language/raw_ptr/vec_ret/test.toml, test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/call_basic_storage/src/main.sw, test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/call_increment_contract/src/main.sw, test/src/e2e_vm_tests/test_programs/should_pass/require_contract_deployment/storage_access_caller/src/main.sw, test/src/e2e_vm_tests/test_programs/should_pass/stdlib/alloc/src/main.sw, test/src/e2e_vm_tests/test_programs/should_pass/stdlib/alloc/test.toml
Fixes https://github.com/FuelLabs/sway/issues/4246
=> Remove workaround with the HP pointer

docs/reference/src/code/language/style-guide/enum_style/src/lib.sw, docs/reference/src/documentation/language/style-guide/enums.md
=> Sway Ref: Style guide enum intro

.gitignore, docs/book/src/advanced/traits.md
fixes a couple broken links in the docs and adds .DS_Store to .gitignore.
=> fix: broken links, ignore DS_Store

sway-lib-std/src/contract_id.sw, sway-lsp/tests/lib.rs
=> Remove unused import from contract_id.sw

docs/reference/src/SUMMARY.md, docs/reference/src/code/operations/assertions/src/lib.sw, docs/reference/src/documentation/operations/assertions/assert-eq.md, docs/reference/src/documentation/operations/assertions/index.md
Closes #4676 
Added `dead_code` annotation to functions in library
=> Sway Ref: Assertions assert_eq

sway-lsp/src/core/session.rs
closes https://github.com/FuelLabs/sway-vscode-plugin/issues/141
=> return diagnostics from parser errors

Cargo.lock, forc-pkg/Cargo.toml, forc-plugins/forc-client/Cargo.toml, forc-plugins/forc-doc/Cargo.toml, forc-plugins/forc-fmt/Cargo.toml, forc-plugins/forc-lsp/Cargo.toml, forc-plugins/forc-tx/Cargo.toml, forc-test/Cargo.toml, forc-tracing/Cargo.toml, forc-util/Cargo.toml, forc/Cargo.toml, sway-ast/Cargo.toml, sway-core/Cargo.toml, sway-error/Cargo.toml, sway-ir/Cargo.toml, sway-ir/sway-ir-macros/Cargo.toml, sway-lsp/Cargo.toml, sway-parse/Cargo.toml, sway-types/Cargo.toml, sway-utils/Cargo.toml, swayfmt/Cargo.toml
Also runs `cargo update` in order to update deps to their latest patch release as this is a breaking release.
=> chore: bump to v0.42.0

forc-plugins/forc-client/src/op/deploy.rs
closes #4765.
This PR improves the deployed message for the successfull deployments done with `forc-deploy`. Before this PR succesfull deployment message was looking like the following:
```console
contract id: 0xa8f18533afc18453323bdf17c83750c556916ab183daacf46d7a8d3c633a40ee
Please provide the password of your encrypted wallet vault at "/Users/kayagokalp/.fuel/wallets/.wallet":
Do you accept to sign this transaction with fuel1egx2nvm4395gukm8uyh4zzxdlx3hht9ulu6n67nhwq57zs74camskx7klp [y/N]:y
contract a8f18533afc18453323bdf17c83750c556916ab183daacf46d7a8d3c633a40ee deployed in block 0x3ade9199ae88b6accbbbc5cb8f30aad8c034385f1f88214f894ae059284595da
```
After this PR
```console
Please provide the password of your encrypted wallet vault at "/Users/kayagokalp/.fuel/wallets/.wallet":
Do you …
```
=> feat: improve deployed message for forc-deploy

sway-ir/src/bin/opt.rs
=> Fix typo in opt.rs

Cargo.lock, forc-pkg/Cargo.toml, forc-plugins/forc-client/Cargo.toml, forc-plugins/forc-doc/Cargo.toml, forc-plugins/forc-fmt/Cargo.toml, forc-plugins/forc-lsp/Cargo.toml, forc-plugins/forc-tx/Cargo.toml, forc-test/Cargo.toml, forc-tracing/Cargo.toml, forc-util/Cargo.toml, forc/Cargo.toml, sway-ast/Cargo.toml, sway-core/Cargo.toml, sway-error/Cargo.toml, sway-ir/Cargo.toml, sway-ir/sway-ir-macros/Cargo.toml, sway-lsp/Cargo.toml, sway-parse/Cargo.toml, sway-types/Cargo.toml, sway-utils/Cargo.toml, swayfmt/Cargo.toml, test/src/sdk-harness/Cargo.lock
Waiting for:
1. #4766
2. #4764
3. #4762 
4. #4760
=> chore: bump to v0.42.1

sway-lib-core/src/ops.sw
Looked for the le function for a while being realizing the weird formatting was hiding it. The newline for the impls are also unnecessary
=> Fix weird formatting

sway-lib-std/src/vec.sw
Standardized documentation for vec.sw in std lib
=> Vec.sw documentation

sway-lib-std/src/u256.sw
=> U256 documentation

sway-lib-std/src/token.sw
=> Token library documentation

test/src/e2e_vm_tests/mod.rs
=> Show compiler error messages for unit tests that do not compile

sway-lib-core/src/raw_ptr.sw, sway-lib-core/src/raw_slice.sw, sway-lib-std/src/alloc.sw
Updated raw_ptr.sw, alloc.sw and raw_slice.sw closing out those tasks for https://github.com/FuelLabs/sway/issues/4812
=> Update memory manipulation libs to meet SRC-2 inline docs standard

sway-lib-std/src/assert.sw, sway-lib-std/src/logging.sw, sway-lib-std/src/option.sw, sway-lib-std/src/result.sw, sway-lib-std/src/revert.sw
This PR completes the option.sw, result.sw, assert.sw, revert.sw, and logging.sw tasks of https://github.com/FuelLabs/sway/issues/4812
=> Update assertion and results to meet SRC-2 inline docs standard

sway-lib-std/src/string.sw
=> string documentation

sway-lib-std/src/auth.sw, sway-lib-std/src/b512.sw, sway-lib-std/src/block.sw, sway-lib-std/src/bytes.sw
Documentation for library auth, b256, b512, block and bytes
=> A-B library documentation

sway-lsp/src/traverse/parsed_tree.rs
=> assign correct semantics to struct expression name accounting for `Self`

sway-lsp/src/traverse/typed_tree.rs
=> Assign correct type_defs to struct field and function param names

sway-lib-std/src/call_frames.sw, sway-lib-std/src/context.sw, sway-lib-std/src/external.sw
This PR completes the external.sw, call_frames.sw, and context.sw tasks of https://github.com/FuelLabs/sway/issues/4812
=> Std-lib external, call_frames, and context inline docs updates to meet SRC-2 standard

sway-lib-std/src/convert.sw
=> copied rust docs to sway

sway-lib-std/src/constants.sw, sway-lib-std/src/flags.sw, sway-lsp/tests/lib.rs
=> Update flags and constants docs

sway-lib-std/src/error_signals.sw, sway-lib-std/src/low_level_call.sw, sway-lib-std/src/outputs.sw
=> Llc outputs error_signals

forc/src/ops/forc_init.rs
Updates `forc new` and `forc init` welcome message to point to our new documentation hub.
=> feat: update `forc init/new` message to point users to new docs hub

Cargo.lock, docs/reference/src/documentation/introduction/installation/cargo.md, docs/reference/src/documentation/introduction/installation/index.md, docs/reference/src/documentation/introduction/installation/source.md, docs/reference/src/index.md, forc-pkg/Cargo.toml, forc-plugins/forc-client/Cargo.toml, forc-plugins/forc-doc/Cargo.toml, forc-plugins/forc-fmt/Cargo.toml, forc-plugins/forc-lsp/Cargo.toml, forc-plugins/forc-tx/Cargo.toml, forc-test/Cargo.toml, forc-tracing/Cargo.toml, forc-util/Cargo.toml, forc/Cargo.toml, sway-ast/Cargo.toml, sway-core/Cargo.toml, sway-error/Cargo.toml, sway-ir/Cargo.toml, sway-ir/sway-ir-macros/Cargo.toml, sway-lsp/Cargo.toml, sway-parse/Cargo.toml, sway-types/Cargo.toml, sway-utils/Cargo.toml, swayfmt/Cargo.toml
Bumps version to v0.44.1, to get some of tooling hot-fixes released.
=> Bump to v0.44.1

sway-lsp/tests/integration/lsp.rs
Migrates this test to use the new approach that was recently introduced. Should fix CI errors.
=> Fix test is sophie/4983code lens

test/src/e2e_vm_tests/harness.rs
Right now unit tests in the testsuite output something like this when a compiler panic happesn:
```
❯ cargo run --release --bin test unit_test_panic
Compiling test v0.0.0 (/Users/anton/fuel/sway/test)
Finished release [optimized] target(s) in 15.30s
Running `target/release/test unit_test_panic`
Testing should_pass/unit_test_panic ...%
```
After this change the output will look something like
```
❯ cargo run --release --bin test unit_test_panic
Finished release [optimized] target(s) in 0.54s
Running `target/release/test unit_test_panic`
Testing should_pass/unit_test_panic ... failed
Compiler panic
Compiling should_pass/unit_test_panic ...
Compiling script unit_test_panic (/Users/anton/fuel/sway/test/src/e2e_vm_tests/test_programs/should_pass/unit_test_panic)
thread 'main' panicked at …
```
=> Catch compiler panics in Sway unit tests

Cargo.lock, docs/reference/src/documentation/introduction/installation/cargo.md, docs/reference/src/documentation/introduction/installation/index.md, docs/reference/src/documentation/introduction/installation/source.md, docs/reference/src/index.md, forc-pkg/Cargo.toml, forc-plugins/forc-client/Cargo.toml, forc-plugins/forc-doc/Cargo.toml, forc-plugins/forc-fmt/Cargo.toml, forc-plugins/forc-lsp/Cargo.toml, forc-plugins/forc-tx/Cargo.toml, forc-test/Cargo.toml, forc-tracing/Cargo.toml, forc-util/Cargo.toml, forc/Cargo.toml, sway-ast/Cargo.toml, sway-core/Cargo.toml, sway-error/Cargo.toml, sway-ir/Cargo.toml, sway-ir/sway-ir-macros/Cargo.toml, sway-lsp/Cargo.toml, sway-parse/Cargo.toml, sway-types/Cargo.toml, sway-utils/Cargo.toml, swayfmt/Cargo.toml
=> Bump to v0.46.1

docs/book/src/blockchain-development/access_control.md
=> Fix broken link in access_control.md

sway-core/src/semantic_analysis/ast_node/expression/typed_expression.rs
=> chore: replaced `filter().map()` with `filter_map()` in `sway-core`.

Cargo.lock, docs/reference/src/documentation/introduction/installation/cargo.md, docs/reference/src/documentation/introduction/installation/index.md, docs/reference/src/documentation/introduction/installation/source.md, docs/reference/src/index.md, forc-pkg/Cargo.toml, forc-plugins/forc-client/Cargo.toml, forc-plugins/forc-crypto/Cargo.toml, forc-plugins/forc-debug/Cargo.toml, forc-plugins/forc-doc/Cargo.toml, forc-plugins/forc-fmt/Cargo.toml, forc-plugins/forc-lsp/Cargo.toml, forc-plugins/forc-tx/Cargo.toml, forc-test/Cargo.toml, forc-tracing/Cargo.toml, forc-util/Cargo.toml, forc/Cargo.toml, sway-ast/Cargo.toml, sway-core/Cargo.toml, sway-error/Cargo.toml, sway-ir/Cargo.toml, sway-ir/sway-ir-macros/Cargo.toml, sway-lsp/Cargo.toml, sway-parse/Cargo.toml, sway-types/Cargo.toml, sway-utils/Cargo.toml, swayfmt/Cargo.toml
=> chore: bump version to 0.49.1

sway-core/src/transform/to_parsed_lang/convert_parse_tree.rs
An issue was reported by @sdankel on #5477 caused by #5557.
A segmentation fault would occur when the for loop handling was performed inside the match. This would occur even when that part of the code was not called. Looks like a weird rust issue.
=> Moves for loop handling to a function.

sway-core/src/ir_generation/compile.rs, sway-core/src/ir_generation/const_eval.rs, sway-core/src/language/call_path.rs, sway-core/src/semantic_analysis/ast_node/declaration/abi.rs, sway-core/src/semantic_analysis/ast_node/declaration/auto_impl.rs, sway-core/src/semantic_analysis/ast_node/declaration/declaration.rs, sway-core/src/semantic_analysis/ast_node/declaration/function/function_parameter.rs, sway-core/src/semantic_analysis/ast_node/declaration/impl_trait.rs, sway-core/src/semantic_analysis/ast_node/declaration/trait.rs, sway-core/src/semantic_analysis/ast_node/expression/typed_expression.rs, sway-core/src/semantic_analysis/ast_node/expression/typed_expression/struct_instantiation.rs, sway-core/src/semantic_analysis/namespace/lexical_scope.rs, sway-core/src/semantic_analysis/namespace/mod.rs, sway-core/src/semantic_analysis/namespace/module.rs, sway-core/src/semantic_analysis/namespace/namespace.rs, sway-core/src/semantic_analysis/type_check_context.rs, sway-core/src/type_system/ast_elements/type_parameter.rs, sway-core/src/type_system/id.rs, sway-lsp/src/capabilities/hover/hover_link_contents.rs, sway-lsp/src/core/session.rs, sway-lsp/src/traverse/typed_tree.rs
This PR introduces a hierarchy of lexical scopes to namespace modules.
This might still have some bugs to work out, but I don't expect the API to need to change, so am offloading this right now to be able to unblock further work we have pending on namespaces/modules.
=> Introduce lexical scopes to namespace modules

docs/book/spell-check-custom-words.txt, docs/book/src/lsp/installation.md
=> Add instructions for LSP on Code OSS

forc-plugins/forc-debug/tests/fixtures/simple/Forc.toml, forc-plugins/forc-debug/tests/server_integration.rs
Closes https://github.com/FuelLabs/sway/issues/5637
=> Re-enable test_server_launch_mode

Cargo.lock, docs/reference/src/documentation/introduction/installation/cargo.md, docs/reference/src/documentation/introduction/installation/index.md, docs/reference/src/documentation/introduction/installation/source.md, docs/reference/src/index.md, forc-pkg/Cargo.toml, forc-plugins/forc-client/Cargo.toml, forc-plugins/forc-crypto/Cargo.toml, forc-plugins/forc-debug/Cargo.toml, forc-plugins/forc-doc/Cargo.toml, forc-plugins/forc-fmt/Cargo.toml, forc-plugins/forc-lsp/Cargo.toml, forc-plugins/forc-tx/Cargo.toml, forc-test/Cargo.toml, forc-tracing/Cargo.toml, forc-util/Cargo.toml, forc/Cargo.toml, sway-ast/Cargo.toml, sway-core/Cargo.toml, sway-error/Cargo.toml, sway-ir/Cargo.toml, sway-ir/sway-ir-macros/Cargo.toml, sway-lsp/Cargo.toml, sway-lsp/tests/fixtures/tokens/storage/Forc.toml, sway-parse/Cargo.toml, sway-types/Cargo.toml, sway-utils/Cargo.toml, swayfmt/Cargo.toml
cc version 1.0.86 has a bug that blocks our cross compilation pipeline https://github.com/rust-lang/cc-rs/issues/964
=> Revert to cc 1.0.83 and bump to 0.51.1

sway-lib-std/src/primitive_conversions/u16.sw
Adds From<u8> for u16
Partially addresses #5797
=> From<u8> for u16 implementation

Cargo.lock, docs/reference/src/documentation/introduction/installation/cargo.md, docs/reference/src/documentation/introduction/installation/index.md, docs/reference/src/documentation/introduction/installation/source.md, docs/reference/src/index.md, forc-pkg/Cargo.toml, forc-plugins/forc-client/Cargo.toml, forc-plugins/forc-crypto/Cargo.toml, forc-plugins/forc-debug/Cargo.toml, forc-plugins/forc-doc/Cargo.toml, forc-plugins/forc-fmt/Cargo.toml, forc-plugins/forc-lsp/Cargo.toml, forc-plugins/forc-tx/Cargo.toml, forc-test/Cargo.toml, forc-tracing/Cargo.toml, forc-util/Cargo.toml, forc/Cargo.toml, sway-ast/Cargo.toml, sway-core/Cargo.toml, sway-error/Cargo.toml, sway-ir/Cargo.toml, sway-ir/sway-ir-macros/Cargo.toml, sway-lsp/Cargo.toml, sway-lsp/tests/fixtures/tokens/storage/Forc.toml, sway-parse/Cargo.toml, sway-types/Cargo.toml, sway-utils/Cargo.toml, swayfmt/Cargo.toml
=> chore: bump to v0.52.1

Cargo.lock, docs/reference/src/documentation/introduction/installation/cargo.md, docs/reference/src/documentation/introduction/installation/index.md, docs/reference/src/documentation/introduction/installation/source.md, docs/reference/src/index.md, forc-pkg/Cargo.toml, forc-plugins/forc-client/Cargo.toml, forc-plugins/forc-crypto/Cargo.toml, forc-plugins/forc-debug/Cargo.toml, forc-plugins/forc-doc/Cargo.toml, forc-plugins/forc-fmt/Cargo.toml, forc-plugins/forc-lsp/Cargo.toml, forc-plugins/forc-tx/Cargo.toml, forc-test/Cargo.toml, forc-tracing/Cargo.toml, forc-util/Cargo.toml, forc/Cargo.toml, sway-ast/Cargo.toml, sway-core/Cargo.toml, sway-error/Cargo.toml, sway-ir/Cargo.toml, sway-ir/sway-ir-macros/Cargo.toml, sway-lsp/Cargo.toml, sway-lsp/tests/fixtures/tokens/storage/Forc.toml, sway-parse/Cargo.toml, sway-types/Cargo.toml, sway-utils/Cargo.toml, swayfmt/Cargo.toml
Bump repo to 0.53.0
waiting on #5813
=> chore: bump to v0.53.0

docs/book/src/lsp/troubleshooting.md
To be merged after https://github.com/FuelLabs/sway-vscode-plugin/pull/180
=> Update docs on how to disable LSP

test/src/e2e_vm_tests/test_programs/should_pass/language/generic_struct_instantiation/Forc.lock, test/src/e2e_vm_tests/test_programs/should_pass/language/generic_struct_instantiation/Forc.toml, test/src/e2e_vm_tests/test_programs/should_pass/language/generic_struct_instantiation/src/main.sw, test/src/e2e_vm_tests/test_programs/should_pass/language/generic_struct_instantiation/test.toml
The issue reported in #4689 is already fixed.
This PR only adds a test to prove it works as expected.
Closes #4689.
=> Adds test that proves unexpected error no longer occcurs.

Cargo.lock, docs/reference/src/documentation/introduction/installation/cargo.md, docs/reference/src/documentation/introduction/installation/index.md, docs/reference/src/documentation/introduction/installation/source.md, docs/reference/src/index.md, forc-pkg/Cargo.toml, forc-plugins/forc-client/Cargo.toml, forc-plugins/forc-crypto/Cargo.toml, forc-plugins/forc-debug/Cargo.toml, forc-plugins/forc-doc/Cargo.toml, forc-plugins/forc-fmt/Cargo.toml, forc-plugins/forc-lsp/Cargo.toml, forc-plugins/forc-tx/Cargo.toml, forc-test/Cargo.toml, forc-tracing/Cargo.toml, forc-util/Cargo.toml, forc/Cargo.toml, sway-ast/Cargo.toml, sway-core/Cargo.toml, sway-error/Cargo.toml, sway-ir/Cargo.toml, sway-ir/README.md, sway-ir/sway-ir-macros/Cargo.toml, sway-lsp/Cargo.toml, sway-parse/Cargo.toml, sway-types/Cargo.toml, sway-utils/Cargo.toml, swayfmt/Cargo.toml
=> chore: bump to v0.58.0

sway-core/src/language/ty/declaration/storage.rs, sway-error/src/error.rs, test/src/e2e_vm_tests/test_programs/should_fail/storage_field_access_on_non_struct/test.toml
Improve listing of available storage fields in case of missing field error.
=> Improve error messages for namespaced storage fields

Cargo.lock, forc-pkg/Cargo.toml, forc-plugins/forc-client/Cargo.toml, forc-plugins/forc-crypto/Cargo.toml, forc-plugins/forc-debug/Cargo.toml, forc-plugins/forc-doc/Cargo.toml, forc-plugins/forc-fmt/Cargo.toml, forc-plugins/forc-lsp/Cargo.toml, forc-plugins/forc-tx/Cargo.toml, forc-test/Cargo.toml, forc-tracing/Cargo.toml, forc-util/Cargo.toml, forc/Cargo.toml, sway-ast/Cargo.toml, sway-core/Cargo.toml, sway-error/Cargo.toml, sway-ir/Cargo.toml, sway-ir/sway-ir-macros/Cargo.toml, sway-lsp/Cargo.toml, sway-parse/Cargo.toml, sway-types/Cargo.toml, sway-utils/Cargo.toml, swayfmt/Cargo.toml
Includes critical fix https://github.com/FuelLabs/sway/pull/6212
=> Bump to v0.61.2

test/src/e2e_vm_tests/test_programs/should_pass/language/configurable_consts/json_abi_oracle_new_encoding.json, test/src/e2e_vm_tests/test_programs/should_pass/language/configurable_consts/src/main.sw, test/src/e2e_vm_tests/test_programs/should_pass/language/configurable_consts/test.toml
This PR recover configurable tests that were deleted by mistake.
=> fix configurable tests

Cargo.lock, forc-pkg/Cargo.toml, forc-plugins/forc-client/Cargo.toml, forc-plugins/forc-client/proxy_abi/README.md, forc-plugins/forc-crypto/Cargo.toml, forc-plugins/forc-debug/Cargo.toml, forc-plugins/forc-doc/Cargo.toml, forc-plugins/forc-fmt/Cargo.toml, forc-plugins/forc-lsp/Cargo.toml, forc-plugins/forc-tx/Cargo.toml, forc-test/Cargo.toml, forc-tracing/Cargo.toml, forc-util/Cargo.toml, forc/Cargo.toml, sway-ast/Cargo.toml, sway-core/Cargo.toml, sway-error/Cargo.toml, sway-ir/Cargo.toml, sway-ir/sway-ir-macros/Cargo.toml, sway-lsp/Cargo.toml, sway-parse/Cargo.toml, sway-types/Cargo.toml, sway-utils/Cargo.toml, swayfmt/Cargo.toml
=> Bump version to 0.63.1

Cargo.lock, forc-pkg/Cargo.toml, forc-plugins/forc-client/Cargo.toml, forc-plugins/forc-client/proxy_abi/README.md, forc-plugins/forc-crypto/Cargo.toml, forc-plugins/forc-debug/Cargo.toml, forc-plugins/forc-doc/Cargo.toml, forc-plugins/forc-fmt/Cargo.toml, forc-plugins/forc-lsp/Cargo.toml, forc-plugins/forc-tx/Cargo.toml, forc-test/Cargo.toml, forc-tracing/Cargo.toml, forc-util/Cargo.toml, forc/Cargo.toml, sway-ast/Cargo.toml, sway-core/Cargo.toml, sway-error/Cargo.toml, sway-ir/Cargo.toml, sway-ir/sway-ir-macros/Cargo.toml, sway-lsp/Cargo.toml, sway-parse/Cargo.toml, sway-types/Cargo.toml, sway-utils/Cargo.toml, swayfmt/Cargo.toml
=> chore: bump to v0.63.5

Cargo.lock, forc-pkg/Cargo.toml, forc-plugins/forc-client/Cargo.toml, forc-plugins/forc-client/proxy_abi/README.md, forc-plugins/forc-crypto/Cargo.toml, forc-plugins/forc-debug/Cargo.toml, forc-plugins/forc-doc/Cargo.toml, forc-plugins/forc-fmt/Cargo.toml, forc-plugins/forc-lsp/Cargo.toml, forc-plugins/forc-tx/Cargo.toml, forc-test/Cargo.toml, forc-tracing/Cargo.toml, forc-util/Cargo.toml, forc/Cargo.toml, sway-ast/Cargo.toml, sway-core/Cargo.toml, sway-error/Cargo.toml, sway-ir/Cargo.toml, sway-ir/sway-ir-macros/Cargo.toml, sway-lsp/Cargo.toml, sway-parse/Cargo.toml, sway-types/Cargo.toml, sway-utils/Cargo.toml, swayfmt/Cargo.toml
Bumps repo to v0.63.6
waiting on #6555
=> chore: bump to v0.63.6

README.md
Hello. Made changes to the documentation, namely inserted a link to the blockchain
=> docs: added a link to the Fuel blockchain

docs/book/src/blockchain-development/native_assets.md
The single and multi asset examples in the docs hub do not use the latest versions of the SRC3 and SRC20 standard. This has been updated to follow the specifications.
=> Update single and multi asset example in docs hub

.github/workflows/ci.yml, .github/workflows/scripts/verify_tag.sh
Refactor `verify_tag.sh` to check all the places where lockstep versions are present in new workspace configuration.
=> Fix release check script to check new version specs

forc-plugins/forc-client/src/op/deploy.rs
Just some small nits and refactoring to reduce code duplication.
=> Code suggestions for blob deployments for scripts and predicates

Cargo.lock, Cargo.toml
=> chore: bump to v0.65.2

forc-util/src/bytecode.rs
Adding comments per https://github.com/FuelLabs/sway/pull/6674#issuecomment-2485688098
=> Add comments about bytecode test files

Cargo.lock, Cargo.toml
Bumped versions and ran `cargo update`.
=> chore: bump version to 0.66.5

forc-plugins/forc-client/tests/deploy.rs
Description:
Fixed errors and inaccuracies in the project's textual materials.
Type of Change:
Fixing errors (typos, grammatical mistakes, etc.)
Testing:
Changes have been reviewed to ensure no new errors were introduced.
Impact:
Improved readability of texts and documentation.
Additional Notes:
Regular text audits are recommended to maintain a high standard of quality.
=> typo-Update deploy.rs

Cargo.lock, forc-plugins/forc-client/src/op/call/mod.rs
Ran `cargo-update` to get the latest version of fuels-rs and fuel.core.
Updated the test `contract_call_with_abi` to pass. Context: https://fuellabs.slack.com/archives/C01KBNGSWGJ/p1738755301379719?thread_ts=1738755301.379719&cid=C01KBNGSWGJ
=> chore: cargo update

.github/workflows/gh-pages.yml
Unblock https://github.com/FuelLabs/sway/actions/runs/13629058982/job/38092580347
=> ci: Install forc-node in gh-pages.yml

.github/workflows/ci.yml, forc-plugins/forc-debug/src/cli/commands.rs, forc-plugins/forc-debug/tests/cli_integration.rs, forc-plugins/forc-migrate/src/migrations/partial_eq.rs, forc-plugins/forc-migrate/src/modifying/annotated.rs, forc-plugins/forc-migrate/src/modifying/attribute.rs, forc-plugins/forc-migrate/src/modifying/function.rs, forc-plugins/forc-migrate/src/modifying/module.rs, forc-plugins/forc-migrate/src/modifying/storage_field.rs, forc-plugins/forc-node/tests/local.rs, sway-core/src/asm_generation/fuel/fuel_asm_builder.rs, sway-core/src/control_flow_analysis/dead_code_analysis.rs, sway-core/src/lib.rs, sway-core/src/query_engine/mod.rs, sway-core/src/type_system/engine.rs, sway-ir/src/optimize/inline.rs, sway-lsp/src/core/session.rs, sway-lsp/tests/integration/lsp.rs
=> ci: upgrade to rust 1.85.0

docs/breaking-release-checklist.md
This PR adds the first version of the "Breaking Release Checklist" document to the compiler's internal documentation.
=> Add "Breaking Release Checklist" to internal docs

Cargo.lock, Cargo.toml
Patch version bump since there are pending features for the next minor release.
=> chore: bump to 0.66.8

forc-plugins/forc-node/Cargo.toml
Descriptions are required for crates.io published packages.
=> Add description to forc-node

templates/sway-predicate-test-rs/template/Cargo.toml, templates/sway-script-test-rs/template/Cargo.toml, templates/sway-test-rs/template/Cargo.toml
=> chore: update templates to use newer fuels SDK

.github/workflows/ci.yml, Cargo.lock, Cargo.toml, forc-plugins/forc-client/src/op/call/call_function.rs, forc-plugins/forc-client/src/op/call/missing_contracts.rs, forc-plugins/forc-client/src/op/submit.rs, forc-plugins/forc-client/src/util/account.rs, forc-plugins/forc-client/src/util/aws.rs, forc-test/src/ecal.rs, test/src/sdk-harness/Cargo.lock, test/src/sdk-harness/Cargo.toml, test/src/sdk-harness/test_projects/auth/mod.rs, test/src/sdk-harness/test_projects/predicate_data_simple/mod.rs, test/src/sdk-harness/test_projects/predicate_data_struct/mod.rs, test/src/sdk-harness/test_projects/script_data/mod.rs, test/src/sdk-harness/test_projects/storage_vec/testgen.rs, test/src/sdk-harness/test_projects/string_slice/mod.rs, test/src/sdk-harness/test_projects/tx_fields/mod.rs
Dependency bump to get fuels 0.72 and fuel-core 0.43.1 support.
=> chore: bump fuel-core to 0.43.1 and fuels to 0.72

forc-plugins/forc-publish/src/error.rs
=> fix: Print full error in forc-publish

Cargo.lock, forc-plugins/forc-publish/Cargo.toml, forc-util/Cargo.toml, forc-util/src/lib.rs
I noticed that some test dependencies were being included in builds unnecessarily. This PR moves them to dev-dependencies.
=> chore: move test deps to dev-dependencies

sway-core/src/semantic_analysis/ast_node/declaration/function.rs, sway-core/src/semantic_analysis/ast_node/declaration/impl_trait.rs, sway-core/src/semantic_analysis/type_resolve.rs, sway-core/src/type_system/ast_elements/type_parameter.rs, sway-core/src/type_system/monomorphization.rs, sway-core/src/type_system/unify/unifier.rs, sway-error/src/error.rs, test/src/e2e_vm_tests/test_programs/should_fail/const_generics/Forc.lock, test/src/e2e_vm_tests/test_programs/should_fail/const_generics/Forc.toml, test/src/e2e_vm_tests/test_programs/should_fail/const_generics/snapshot.toml, test/src/e2e_vm_tests/test_programs/should_fail/const_generics/src/main.sw, test/src/e2e_vm_tests/test_programs/should_fail/const_generics/stdout.snap, test/src/e2e_vm_tests/test_programs/should_pass/language/const_generics/src/main.sw, test/src/e2e_vm_tests/test_programs/should_pass/language/const_generics/stdout.snap, test/src/snapshot/mod.rs
Fixes https://github.com/FuelLabs/sway/issues/7260.
=> Fix type check for variables in const generics

sway-core/src/language/ty/declaration/const_generic.rs, sway-core/src/language/ty/declaration/function.rs, sway-core/src/language/ty/expression/expression.rs, sway-core/src/semantic_analysis/ast_node/declaration/impl_trait.rs, sway-core/src/semantic_analysis/ast_node/declaration/trait.rs, sway-core/src/semantic_analysis/ast_node/expression/typed_expression/function_application.rs, sway-core/src/semantic_analysis/ast_node/expression/typed_expression/method_application.rs, sway-core/src/type_system/ast_elements/type_parameter.rs, sway-core/src/type_system/substitute/subst_map.rs, sway-lib-std/src/hash.sw
Continuation of https://github.com/FuelLabs/sway/issues/6860.
=> Hash for string arrays

.github/workflows/ci.yml
Attempts to fix error in CI: https://github.com/FuelLabs/sway/actions/runs/17945577761/job/51050235186
Build environment setup for RocksDB:
* Added a step to install required system packages (`build-essential`, `clang`, `llvm-dev`, `libclang-dev`, `pkg-config`) on Linux runners to support building RocksDB and running `bindgen`.
* Configured `LIBCLANG_PATH` and `BINDGEN_EXTRA_CLANG_ARGS` environment variables to ensure `bindgen` can locate the correct Clang libraries and system headers.
=> rocksdb compilation error fix
